#!/bin/bash
hadoop fs -copyFromLocal /tmp/lib/* /lib
runuser -l hdfs -c 'hadoop fs -chown -R yarn:hdfs /lib'
runuser -l yarn -c 'hadoop fs -copyFromLocal /tmp/app/dataplatform /app/dataplatform'
rm -rf /tmp/lib
rm -rf /tmp/app
