#!/bin/bash
echo "____yum___clean"
sudo yum clean all
echo "____yum___group___install"
sudo yum -y groupinstall "Development tools"
echo "____yum___install"
sudo yum -y install zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel readline-devel tk-devel gdbm-devel db4-devel libpcap-devel xz-devel
sudo yum -y install atlas, atlas-devel, blas, blas-devel, lapack lapack-devel gcc