DROP SCHEMA IF EXISTS `ScoringDB`;
CREATE SCHEMA IF NOT EXISTS `ScoringDB`;
GRANT ALL ON ScoringDB.* TO root;
USE `ScoringDB`;

source WSHOME/le-scoring/ddl_scoringdb_mysql5innodb.sql;

drop table if exists `TestLeadsTable`;
drop table if exists `ScoringDeploymentTestNG_Base_LeadsTable`;

CREATE TABLE TestLeadsTable (
  Lead_ID INT NOT NULL AUTO_INCREMENT,
  SEPAL_LENGTH FLOAT,
  SEPAL_WIDTH FLOAT,
  PETAL_LENGTH FLOAT,
  PETAL_WIDTH FLOAT,
  CATEGORY INT NOT NULL,
  MODEL_ID nvarchar(510) NOT NULL,
  PRIMARY KEY(Lead_ID)
);

CREATE TABLE ScoringDeploymentTestNG_Base_LeadsTable (
	`LeadID` nvarchar(50) NULL,
	`ModelingID` bigint NULL,
	`ELQContact_Industry` nvarchar(25) NULL,
	`ELQContact_LeadSource` nvarchar(256) NULL,
	`Physical_Country__c` nvarchar(256) NULL,
	`MCC__c` nvarchar(32) NULL,
	`Sales_Per_Day__c` Double NULL,
	`Total_Sale_Settlements_Amount_Rollup__c` Double NULL,
	`CampaignId` nvarchar(256) NULL,
	`P1_Event` int NULL,
	`twitter_url_exists` nvarchar(10) NULL,
	`linkedin_url_exists` nvarchar(10) NULL,
	`googleplus_url_exists` nvarchar(10) NULL,
	`facebook_url_exists` nvarchar(10) NULL,
	`Ultimate_Parent_Company_Indicator` nvarchar(10) NULL,
	`Tech_Used` nvarchar(1000) NULL,
	`RecentPatents` bigint NULL,
	`Rank` bigint NULL,
	`PercentileModel` nvarchar(32) NULL,
	`PatentID` nvarchar(200) NULL,
	`PatentApplicationID` nvarchar(200) NULL,
	`PatentApplicationFiled` nvarchar(200) NULL,
	`Organic_Traffic` bigint NULL,
	`Organic_Keywords` bigint NULL,
	`Organic_Cost` bigint NULL,
	`ModelAction` nvarchar(60) NULL,
	`MSA_Code` nvarchar(10) NULL,
	`Longitude` Double NULL,
	`LinkedIn_Url` nvarchar(1000) NULL,
	`JobsTrendString` nvarchar(500) NULL,
	`JobsTrend` bigint NULL,
	`JobsSources` nvarchar(500) NULL,
	`JobsLink` nvarchar(400) NULL,
	`JobsDescription` text NULL,
	`ItemID` nvarchar(100) NULL,
	`IQC003` bigint NULL,
	`IQC002` bigint NULL,
	`IQC001` bigint NULL,
	`HPAExecutionFull` bigint NULL,
	`HPAEmailSuffix` nvarchar(500) NULL,
	`GooglePlus_Url` nvarchar(1000) NULL,
	`FundingTotalContracts` bigint NULL,
	`FundingTotalContractedAmount` bigint NULL,
	`FundingStage` text NULL,
	`FundingSources` nvarchar(500) NULL,
	`FundingGovAgency` nvarchar(1000) NULL,
	`FundingFiscalYear` bigint NULL,
	`FundingContractNaics` bigint NULL,
	`FundingContractDescription` text NULL,
	`FundingContractCategory` nvarchar(1000) NULL,
	`FundingContractAmount` bigint NULL,
	`FirmagraphicsSources` nvarchar(500) NULL,
	`FinancialsSources` nvarchar(500) NULL,
	`FeatureExecutionFull` bigint NULL,
	`FeatureExecutionFetch` bigint NULL,
	`FeatureExecutionEvaluate` bigint NULL,
	`FeatureAverageDocumentSizeProcessed` bigint NULL,
	`FeatureAverageDocumentSizeFetched` bigint NULL,
	`Facebook_Url` nvarchar(1000) NULL,
	`ExtractedBy` nvarchar(100) NULL,
	`ExperianCreditRating` nvarchar(2) NULL,
	`CloudTechnologies_MobileTechnologies` bigint NULL,
	`CloudTechnologies_MobileEnterpriseManagement` bigint NULL,
	`CloudTechnologies_Hypervisor` bigint NULL,
	`CloudTechnologies_HRMS_HCM` bigint NULL,
	`CloudTechnologies_ATS` bigint NULL,
	`BusinessZip` nvarchar(100) NULL,
	`BusinessWebsite` text NULL,
	`BusinessUrlNumPages` bigint NULL,
	`BusinessUltimateParentName` nvarchar(240) NULL,
	`BusinessType` nvarchar(120) NULL,
	`BusinessTwitter` text NULL,
	`BusinessTechnologiesRecentTechnologies` text NULL,
	`BusinessTechnologiesRecentTags` text NULL,
	`BusinessState` nvarchar(100) NULL,
	`BusinessPublicCompany` text NULL,
	`BusinessOtherLinks` text NULL,
	`BusinessName` nvarchar(400) NULL,
	`BusinessLinkedIn` text NULL,
	`BusinessLastSocialActivity` nvarchar(40) NULL,
	`BusinessInsuranceParticipants` bigint NULL,
	`BusinessIndustry` text NULL,
	`BusinessInboundLinks` text NULL,
	`BusinessFocus` text NULL,
	`BusinessFacebook` text NULL,
	`BusinessEstablishedMonth` Double NULL,
	`BusinessEmailSuffix` nvarchar(200) NULL,
	`BusinessDescription` text NULL,
	`BusinessCountry` nvarchar(100) NULL,
	`BusinessCompanyPhone` text NULL,
	`BusinessCity` nvarchar(200) NULL,
	`BusinessAddress2` nvarchar(400) NULL,
	`BusinessAddress1` nvarchar(400) NULL,
	`AwardYear` bigint NULL,
	`AlexaViewsRank` bigint NULL,
	`AlexaViewsPerUser` Double NULL,
	`AlexaViewsPerMillion` Double NULL,
	`AlexaTitle` nvarchar(400) NULL,
	`AlexaRelatedLinks` nvarchar(1000) NULL,
	`AlexaReachRank` bigint NULL,
	`AlexaReachPerMillion` Double NULL,
	`AlexaRank` bigint NULL,
	`AlexaKeywords` nvarchar(400) NULL,
	`AlexaDomains` nvarchar(400) NULL,
	`AlexaDescription` text NULL,
	`AlexaCategories` text NULL,
	`AlexLinksIn` bigint NULL,
	`Adwords_Traffic` bigint NULL,
	`Adwords_Keywords` bigint NULL,
	`Adwords_Cost` bigint NULL,
	`ActivitySources` nvarchar(500) NULL,
	`ActiveRetirementParticipants` bigint NULL,
	`CompanyName_Length` int NULL,
	`Domain_Length` int NULL,
	`Title_Length` int NULL,
	`Title_Level` bigint NULL,
	`RelatedLinks_Count` bigint NULL,
	`Number_of_Contacts_for_Domain` bigint NULL,
	`FundingStage1` bigint NULL,
	`JobsTrendString1` bigint NULL,
	`ModelAction1` bigint NULL,
	`Uses_Public_Email_Provider` int NULL,
	`Title_IsAcademic` int NULL,
	`FirstName_SameAs_LastName` int NULL,
	`CompanyName_Entropy` Double NULL,
	`Phone_Entropy` Double NULL,
	`Domain_IsClient` int NULL,
	`Industry_Group` nvarchar(25) NULL,
	`Title_IsTechRelated` int NULL,
	`Most_Recent_Lead_Source` nvarchar(256) NULL,
	`SpamIndicator` int NULL,
	`Rank1` bigint NULL,
	`ReachPerMillion` Double NULL,
	`ViewsPerMillion` Double NULL,
	`ViewsPerUser` Double NULL,
	`AssetsStartOfYear` bigint NULL,
	`AwardCategory` nvarchar(1000) NULL,
	`AwardWebsite` text NULL,
	`Awards12Months` bigint NULL,
	`BankruptcyFiled` nvarchar(2) NULL,
	`BusinessAnnualSalesAbs` bigint NULL,
	`BusinessECommerceSite` text NULL,
	`BusinessEstablishedYear` Double NULL,
	`BusinessEstimatedAnnualSales_k` bigint NULL,
	`BusinessEstimatedEmployees` nvarchar(16) NULL,
	`BusinessFirmographicsParentEmployees` bigint NULL,
	`BusinessFirmographicsParentRevenue` bigint NULL,
	`BusinessPrimarySIC4Digit` nvarchar(8) NULL,
	`BusinessRetirementParticipants` bigint NULL,
	`BusinessSocialPresence` nvarchar(12) NULL,
	`BusinessTechnologiesAds` bigint NULL,
	`BusinessTechnologiesAnalytics` bigint NULL,
	`BusinessTechnologiesCdn` bigint NULL,
	`BusinessTechnologiesCms` bigint NULL,
	`BusinessTechnologiesDocinfo` bigint NULL,
	`BusinessTechnologiesEncoding` bigint NULL,
	`BusinessTechnologiesFeeds` bigint NULL,
	`BusinessTechnologiesFramework` bigint NULL,
	`BusinessTechnologiesHosting` bigint NULL,
	`BusinessTechnologiesJavascript` bigint NULL,
	`BusinessTechnologiesMapping` bigint NULL,
	`BusinessTechnologiesMarketingAutomation` nvarchar(1) NULL,
	`BusinessTechnologiesMedia` bigint NULL,
	`BusinessTechnologiesMx` bigint NULL,
	`BusinessTechnologiesNs` bigint NULL,
	`BusinessTechnologiesOpenSourceAdoption` nvarchar(1) NULL,
	`BusinessTechnologiesParked` bigint NULL,
	`BusinessTechnologiesPayment` bigint NULL,
	`BusinessTechnologiesSeoHeaders` bigint NULL,
	`BusinessTechnologiesSeoMeta` bigint NULL,
	`BusinessTechnologiesSeoTitle` bigint NULL,
	`BusinessTechnologiesServer` bigint NULL,
	`BusinessTechnologiesShop` bigint NULL,
	`BusinessTechnologiesSocialMediaPresence` nvarchar(1) NULL,
	`BusinessTechnologiesSsl` bigint NULL,
	`BusinessTechnologiesWebMaster` bigint NULL,
	`BusinessTechnologiesWebServer` bigint NULL,
	`BusinessTechnologiesWidgets` bigint NULL,
	`BusinessVCFunded` text NULL,
	`CloudTechnologies_CRM_One` bigint NULL,
	`CloudTechnologies_CRM_Two` bigint NULL,
	`CloudTechnologies_CloudService_One` bigint NULL,
	`CloudTechnologies_CloudService_Two` bigint NULL,
	`CloudTechnologies_CommTech_One` bigint NULL,
	`CloudTechnologies_CommTech_Two` bigint NULL,
	`CloudTechnologies_DataCenterSolutions_One` bigint NULL,
	`CloudTechnologies_DataCenterSolutions_Two` bigint NULL,
	`CloudTechnologies_EnterpriseApplications_One` bigint NULL,
	`CloudTechnologies_EnterpriseApplications_Two` bigint NULL,
	`CloudTechnologies_EnterpriseContent_One` bigint NULL,
	`CloudTechnologies_EnterpriseContent_Two` bigint NULL,
	`CloudTechnologies_HardwareBasic_One` bigint NULL,
	`CloudTechnologies_HardwareBasic_Two` bigint NULL,
	`CloudTechnologies_ITGovernance_One` bigint NULL,
	`CloudTechnologies_ITGovernance_Two` bigint NULL,
	`CloudTechnologies_MarketingPerfMgmt_One` bigint NULL,
	`CloudTechnologies_MarketingPerfMgmt_Two` bigint NULL,
	`CloudTechnologies_NetworkComputing_One` bigint NULL,
	`CloudTechnologies_NetworkComputing_Two` bigint NULL,
	`CloudTechnologies_ProductivitySltns_One` bigint NULL,
	`CloudTechnologies_ProductivitySltns_Two` bigint NULL,
	`CloudTechnologies_ProjectMgnt_One` bigint NULL,
	`CloudTechnologies_ProjectMgnt_Two` bigint NULL,
	`CloudTechnologies_SoftwareBasic_One` bigint NULL,
	`CloudTechnologies_SoftwareBasic_Two` bigint NULL,
	`CloudTechnologies_VerticalMarkets_One` bigint NULL,
	`CloudTechnologies_VerticalMarkets_Two` bigint NULL,
	`CloudTechnologies_WebOrntdArch_One` bigint NULL,
	`CloudTechnologies_WebOrntdArch_Two` bigint NULL,
	`DerogatoryIndicator` nvarchar(2) NULL,
	`Facebook_Likes` bigint NULL,
	`FeatureGlobalBag` bigint NULL,
	`FeatureGlobalBasket` bigint NULL,
	`FeatureGlobalCart` bigint NULL,
	`FeatureGlobalProduct` bigint NULL,
	`FeatureGlobalShop` bigint NULL,
	`FeatureGlobalStore` bigint NULL,
	`FeatureHtmlDescription` text NULL,
	`FeatureHtmlKeywords` text NULL,
	`FeatureHtmlTitle` text NULL,
	`FeatureInputValueAddItem` bigint NULL,
	`FeatureInputValueAddToBag` bigint NULL,
	`FeatureInputValueAddToBasket` bigint NULL,
	`FeatureInputValueAddToCart` bigint NULL,
	`FeatureJavaScriptBag` bigint NULL,
	`FeatureJavaScriptBasket` bigint NULL,
	`FeatureJavaScriptCart` bigint NULL,
	`FeatureJavaScriptProduct` bigint NULL,
	`FeatureJavaScriptShop` bigint NULL,
	`FeatureJavaScriptStore` bigint NULL,
	`FeatureNumDocumentsFetched` bigint NULL,
	`FeatureNumDocumentsProcessed` bigint NULL,
	`FeatureProcessed` text NULL,
	`FeatureRefSrcBag` bigint NULL,
	`FeatureRefSrcBasket` bigint NULL,
	`FeatureRefSrcCart` bigint NULL,
	`FeatureRefSrcProduct` bigint NULL,
	`FeatureRefSrcShop` bigint NULL,
	`FeatureRefSrcStore` bigint NULL,
	`FeatureTermAddItem` bigint NULL,
	`FeatureTermAddToBag` bigint NULL,
	`FeatureTermAddToBasket` bigint NULL,
	`FeatureTermAddToCart` bigint NULL,
	`FeatureTermBag` bigint NULL,
	`FeatureTermBargain` bigint NULL,
	`FeatureTermBasket` bigint NULL,
	`FeatureTermBillingAddress` bigint NULL,
	`FeatureTermBuy` bigint NULL,
	`FeatureTermCart` bigint NULL,
	`FeatureTermCatalog` bigint NULL,
	`FeatureTermCheckout` bigint NULL,
	`FeatureTermContinueShopping` bigint NULL,
	`FeatureTermCreateAccount` bigint NULL,
	`FeatureTermCustomerService` bigint NULL,
	`FeatureTermCustomerSupport` bigint NULL,
	`FeatureTermDeal` bigint NULL,
	`FeatureTermFreeShipping` bigint NULL,
	`FeatureTermFrequentlyAskedQuestion` bigint NULL,
	`FeatureTermMyAccount` bigint NULL,
	`FeatureTermOrderHistory` bigint NULL,
	`FeatureTermOrderStatus` bigint NULL,
	`FeatureTermPaymentMethod` bigint NULL,
	`FeatureTermPaymentOption` bigint NULL,
	`FeatureTermPrice` bigint NULL,
	`FeatureTermProduct` bigint NULL,
	`FeatureTermRetail` bigint NULL,
	`FeatureTermReturnPolicy` bigint NULL,
	`FeatureTermReview` bigint NULL,
	`FeatureTermSale` bigint NULL,
	`FeatureTermSearch` bigint NULL,
	`FeatureTermSecureOrder` bigint NULL,
	`FeatureTermShippingAddress` bigint NULL,
	`FeatureTermShippingAndHandling` bigint NULL,
	`FeatureTermShippingInfo` bigint NULL,
	`FeatureTermShippingPolicy` bigint NULL,
	`FeatureTermShop` bigint NULL,
	`FeatureTermShopBy` bigint NULL,
	`FeatureTermStore` bigint NULL,
	`FeatureTermWishList` bigint NULL,
	`FeatureTermYourAccount` bigint NULL,
	`FraudOrDishonesty` nvarchar(20) NULL,
	`FundingAmount` Double NULL,
	`FundingFinanceRound` text NULL,
	`HPANumPages` bigint NULL,
	`Intelliscore` nvarchar(32) NULL,
	`JobsRecentJobs` bigint NULL,
	`JobsTitle` nvarchar(400) NULL,
	`LeasingTrades` nvarchar(32) NULL,
	`PatentGranted` nvarchar(200) NULL,
	`PatentTrend` bigint NULL,
	`RetirementAssetsEOY` bigint NULL,
	`RetirementAssetsYOY` bigint NULL,
	`SemrushAdwordsCost` bigint NULL,
	`SemrushAdwordsKeywords` bigint NULL,
	`SemrushAdwordsTraffic` bigint NULL,
	`SemrushOrganicCost` bigint NULL,
	`SemrushOrganicKeywords` bigint NULL,
	`SemrushOrganicTraffic` bigint NULL,
	`SemrushRank` bigint NULL,
	`TotalParticipantsSOY` bigint NULL,
	`TotalPatents` bigint NULL,
	`Total_Amount_Raised` bigint NULL,
	`Twitter_Followers` bigint NULL,
	`UCCFilings` nvarchar(32) NULL,
	`UCCFilingsPresent` nvarchar(2) NULL,
	`C_Annual_Revenue1` nvarchar(256) NULL,
	`C_Company_Size1` nvarchar(256) NULL,
	`C_Employees1` Double NULL,
	`C_Job_Role1` nvarchar(256) NULL,
	`C_Lead_Source___Original1` nvarchar(256) NULL,
	`C_Product_Solution_of_Interest1` nvarchar(256) NULL,
	`C_SFDC_EmailOptOut1` nvarchar(100) NULL,
	`Model_GUID` varchar(200) NOT NULL
);

LOAD DATA INFILE 'WSHOME/le-scoring/src/test/resources/com/latticeengines/scoring/mysql/nn_train.dat'
INTO TABLE TestLeadsTable
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
(SEPAL_LENGTH, SEPAL_WIDTH, PETAL_LENGTH, PETAL_WIDTH, CATEGORY, MODEL_ID);

LOAD DATA INFILE 'WSHOME/le-scoring/src/test/resources/com/latticeengines/scoring/mysql/nn_test.dat'
INTO TABLE TestLeadsTable
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
(SEPAL_LENGTH, SEPAL_WIDTH, PETAL_LENGTH, PETAL_WIDTH, CATEGORY, MODEL_ID);

LOAD DATA INFILE 'WSHOME/le-scoring/src/test/resources/com/latticeengines/scoring/mysql/ScoringDeploymentTestNG_Base_LeadsTable.txt'
INTO TABLE ScoringDeploymentTestNG_Base_LeadsTable
FIELDS TERMINATED BY '\t' ENCLOSED BY '$'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(LeadID,ModelingID,ELQContact_Industry,ELQContact_LeadSource,Physical_Country__c,MCC__c,Sales_Per_Day__c,Total_Sale_Settlements_Amount_Rollup__c,CampaignId,P1_Event,twitter_url_exists,linkedin_url_exists,googleplus_url_exists,facebook_url_exists,Ultimate_Parent_Company_Indicator,Tech_Used,RecentPatents,Rank,PercentileModel,PatentID,PatentApplicationID,PatentApplicationFiled,Organic_Traffic,Organic_Keywords,Organic_Cost,ModelAction,MSA_Code,Longitude,LinkedIn_Url,JobsTrendString,JobsTrend,JobsSources,JobsLink,JobsDescription,ItemID,IQC003,IQC002,IQC001,HPAExecutionFull,HPAEmailSuffix,GooglePlus_Url,FundingTotalContracts,FundingTotalContractedAmount,FundingStage,FundingSources,FundingGovAgency,FundingFiscalYear,FundingContractNaics,FundingContractDescription,FundingContractCategory,FundingContractAmount,FirmagraphicsSources,FinancialsSources,FeatureExecutionFull,FeatureExecutionFetch,FeatureExecutionEvaluate,FeatureAverageDocumentSizeProcessed,FeatureAverageDocumentSizeFetched,Facebook_Url,ExtractedBy,ExperianCreditRating,CloudTechnologies_MobileTechnologies,CloudTechnologies_MobileEnterpriseManagement,CloudTechnologies_Hypervisor,CloudTechnologies_HRMS_HCM,CloudTechnologies_ATS,BusinessZip,BusinessWebsite,BusinessUrlNumPages,BusinessUltimateParentName,BusinessType,BusinessTwitter,BusinessTechnologiesRecentTechnologies,BusinessTechnologiesRecentTags,BusinessState,BusinessPublicCompany,BusinessOtherLinks,BusinessName,BusinessLinkedIn,BusinessLastSocialActivity,BusinessInsuranceParticipants,BusinessIndustry,BusinessInboundLinks,BusinessFocus,BusinessFacebook,BusinessEstablishedMonth,BusinessEmailSuffix,BusinessDescription,BusinessCountry,BusinessCompanyPhone,BusinessCity,BusinessAddress2,BusinessAddress1,AwardYear,AlexaViewsRank,AlexaViewsPerUser,AlexaViewsPerMillion,AlexaTitle,AlexaRelatedLinks,AlexaReachRank,AlexaReachPerMillion,AlexaRank,AlexaKeywords,AlexaDomains,AlexaDescription,AlexaCategories,AlexLinksIn,Adwords_Traffic,Adwords_Keywords,Adwords_Cost,ActivitySources,ActiveRetirementParticipants,CompanyName_Length,Domain_Length,Title_Length,Title_Level,RelatedLinks_Count,Number_of_Contacts_for_Domain,FundingStage1,JobsTrendString1,ModelAction1,Uses_Public_Email_Provider,Title_IsAcademic,FirstName_SameAs_LastName,CompanyName_Entropy,Phone_Entropy,Domain_IsClient,Industry_Group,Title_IsTechRelated,Most_Recent_Lead_Source,SpamIndicator,Rank1,ReachPerMillion,ViewsPerMillion,ViewsPerUser,AssetsStartOfYear,AwardCategory,AwardWebsite,Awards12Months,BankruptcyFiled,BusinessAnnualSalesAbs,BusinessECommerceSite,BusinessEstablishedYear,BusinessEstimatedAnnualSales_k,BusinessEstimatedEmployees,BusinessFirmographicsParentEmployees,BusinessFirmographicsParentRevenue,BusinessPrimarySIC4Digit,BusinessRetirementParticipants,BusinessSocialPresence,BusinessTechnologiesAds,BusinessTechnologiesAnalytics,BusinessTechnologiesCdn,BusinessTechnologiesCms,BusinessTechnologiesDocinfo,BusinessTechnologiesEncoding,BusinessTechnologiesFeeds,BusinessTechnologiesFramework,BusinessTechnologiesHosting,BusinessTechnologiesJavascript,BusinessTechnologiesMapping,BusinessTechnologiesMarketingAutomation,BusinessTechnologiesMedia,BusinessTechnologiesMx,BusinessTechnologiesNs,BusinessTechnologiesOpenSourceAdoption,BusinessTechnologiesParked,BusinessTechnologiesPayment,BusinessTechnologiesSeoHeaders,BusinessTechnologiesSeoMeta,BusinessTechnologiesSeoTitle,BusinessTechnologiesServer,BusinessTechnologiesShop,BusinessTechnologiesSocialMediaPresence,BusinessTechnologiesSsl,BusinessTechnologiesWebMaster,BusinessTechnologiesWebServer,BusinessTechnologiesWidgets,BusinessVCFunded,CloudTechnologies_CRM_One,CloudTechnologies_CRM_Two,CloudTechnologies_CloudService_One,CloudTechnologies_CloudService_Two,CloudTechnologies_CommTech_One,CloudTechnologies_CommTech_Two,CloudTechnologies_DataCenterSolutions_One,CloudTechnologies_DataCenterSolutions_Two,CloudTechnologies_EnterpriseApplications_One,CloudTechnologies_EnterpriseApplications_Two,CloudTechnologies_EnterpriseContent_One,CloudTechnologies_EnterpriseContent_Two,CloudTechnologies_HardwareBasic_One,CloudTechnologies_HardwareBasic_Two,CloudTechnologies_ITGovernance_One,CloudTechnologies_ITGovernance_Two,CloudTechnologies_MarketingPerfMgmt_One,CloudTechnologies_MarketingPerfMgmt_Two,CloudTechnologies_NetworkComputing_One,CloudTechnologies_NetworkComputing_Two,CloudTechnologies_ProductivitySltns_One,CloudTechnologies_ProductivitySltns_Two,CloudTechnologies_ProjectMgnt_One,CloudTechnologies_ProjectMgnt_Two,CloudTechnologies_SoftwareBasic_One,CloudTechnologies_SoftwareBasic_Two,CloudTechnologies_VerticalMarkets_One,CloudTechnologies_VerticalMarkets_Two,CloudTechnologies_WebOrntdArch_One,CloudTechnologies_WebOrntdArch_Two,DerogatoryIndicator,Facebook_Likes,FeatureGlobalBag,FeatureGlobalBasket,FeatureGlobalCart,FeatureGlobalProduct,FeatureGlobalShop,FeatureGlobalStore,FeatureHtmlDescription,FeatureHtmlKeywords,FeatureHtmlTitle,FeatureInputValueAddItem,FeatureInputValueAddToBag,FeatureInputValueAddToBasket,FeatureInputValueAddToCart,FeatureJavaScriptBag,FeatureJavaScriptBasket,FeatureJavaScriptCart,FeatureJavaScriptProduct,FeatureJavaScriptShop,FeatureJavaScriptStore,FeatureNumDocumentsFetched,FeatureNumDocumentsProcessed,FeatureProcessed,FeatureRefSrcBag,FeatureRefSrcBasket,FeatureRefSrcCart,FeatureRefSrcProduct,FeatureRefSrcShop,FeatureRefSrcStore,FeatureTermAddItem,FeatureTermAddToBag,FeatureTermAddToBasket,FeatureTermAddToCart,FeatureTermBag,FeatureTermBargain,FeatureTermBasket,FeatureTermBillingAddress,FeatureTermBuy,FeatureTermCart,FeatureTermCatalog,FeatureTermCheckout,FeatureTermContinueShopping,FeatureTermCreateAccount,FeatureTermCustomerService,FeatureTermCustomerSupport,FeatureTermDeal,FeatureTermFreeShipping,FeatureTermFrequentlyAskedQuestion,FeatureTermMyAccount,FeatureTermOrderHistory,FeatureTermOrderStatus,FeatureTermPaymentMethod,FeatureTermPaymentOption,FeatureTermPrice,FeatureTermProduct,FeatureTermRetail,FeatureTermReturnPolicy,FeatureTermReview,FeatureTermSale,FeatureTermSearch,FeatureTermSecureOrder,FeatureTermShippingAddress,FeatureTermShippingAndHandling,FeatureTermShippingInfo,FeatureTermShippingPolicy,FeatureTermShop,FeatureTermShopBy,FeatureTermStore,FeatureTermWishList,FeatureTermYourAccount,FraudOrDishonesty,FundingAmount,FundingFinanceRound,HPANumPages,Intelliscore,JobsRecentJobs,JobsTitle,LeasingTrades,PatentGranted,PatentTrend,RetirementAssetsEOY,RetirementAssetsYOY,SemrushAdwordsCost,SemrushAdwordsKeywords,SemrushAdwordsTraffic,SemrushOrganicCost,SemrushOrganicKeywords,SemrushOrganicTraffic,SemrushRank,TotalParticipantsSOY,TotalPatents,Total_Amount_Raised,Twitter_Followers,UCCFilings,UCCFilingsPresent,C_Annual_Revenue1,C_Company_Size1,C_Employees1,C_Job_Role1,C_Lead_Source___Original1,C_Product_Solution_of_Interest1,C_SFDC_EmailOptOut1,Model_GUID);

COMMIT;