DROP SCHEMA IF EXISTS DellEBI;

CREATE SCHEMA IF NOT EXISTS DellEBI;

GRANT ALL ON DellEBI.* TO root@localhost;
ALTER DATABASE DellEBI CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
USE `DellEBI`;

DROP TABLE IF EXISTS  STG_WARRANTY_GLOBAL;
DROP TABLE IF EXISTS  STG_SKU_MANUFACTURER;

CREATE TABLE STG_WARRANTY_GLOBAL(
  `ORDER_BUSINESS_UNIT_ID` int NOT NULL,
  `LOCAL_CHANNEL` char(5) NOT NULL,
  `SERVICE_TAG_ID` varchar(15),
  `EXPRESS_SERVICE_CODE` decimal(38, 0),
  `ORDER_NUMBER` varchar(20),
  `SERVICE_CONTRACT_ORDER_NUMBER` varchar(20) NOT NULL,
  `SHIP_DATE` datetime(3),
  `SERVICE_CONTRACT_START_DATE` Datetime(6),
  `SERVICE_CONTRACT_END_DATE` Datetime(6),
  `SERVICE_LEVEL_DESC` varchar(100),
  `WARRANTY_ITEM_NUM` varchar(30),
  `BRAND_DESC` varchar(30),
  `SERVICE_LEVEL_CODE` varchar(15),
  `CUSTOMER_NUMBER` varchar(20),
  `SERVICE_CONTRACT_CUSTOMER_NUMBER` varchar(20),
  `PRODUCT_LINE_PARENT` varchar(15),
  `PRODUCT_LINE_DESC` varchar(150),
  `PRODUCT_LINE` varchar(45),
  `SERVICE_CONTRACT_STATUS_DESC` varchar(150),
  `FAMILY` varchar(40),
  `SOURCE_SYSTEM_UPDATE_DATE` Datetime(6),
  `REGION_CODE` varchar(10)
) engine=InnoDB;


CREATE TABLE STG_SKU_MANUFACTURER(
  `DW_SKU_NUM` varchar(20),
  `MFG_NAME` varchar(80),
  `SUBCLASS_DESC` varchar(500),
  `ITM_SHRT_DESC` varchar(1000),
  `MFG_PART_NUM` varchar(1000)
) engine=InnoDB;

