


IF OBJECT_ID('ALGORITHM', 'U') IS NOT NULL
   DROP TABLE ALGORITHM
IF OBJECT_ID('THROTTLE_CONFIGURATION', 'U') IS NOT NULL
   DROP TABLE THROTTLE_CONFIGURATION
IF OBJECT_ID('JOB', 'U') IS NOT NULL
   DROP TABLE JOB
IF OBJECT_ID('MODEL', 'U') IS NOT NULL
   DROP TABLE MODEL
IF OBJECT_ID('MODEL_DEFINITION', 'U') IS NOT NULL
   DROP TABLE MODEL_DEFINITION


/****** Object:  Table [dbo].[THROTTLE_CONFIGURATION]    Script Date: 05/28/2014 18:00:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[THROTTLE_CONFIGURATION](
	[PID] [int] NOT NULL IDENTITY (1000, 1),
	[TIMESTAMP] [datetime] NOT NULL,
	[JOB_RANK_CUTOFF] [smallint] NOT NULL,
	[IMMEDIATE] [bit] NOT NULL,
	[ENABLED] [bit] NOT NULL,
 CONSTRAINT [PK_THROTTLE_CONFIGURATION] PRIMARY KEY CLUSTERED 
(
	[PID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MODEL_DEFINITION]    Script Date: 05/28/2014 18:00:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MODEL_DEFINITION](
	[PID] [int] NOT NULL IDENTITY (1000, 1),
	[NAME] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_MODEL_DEFINITION] PRIMARY KEY CLUSTERED 
(
	[PID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ALGORITHM]    Script Date: 05/28/2014 18:00:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ALGORITHM](
	[PID] [int] NOT NULL IDENTITY (1000, 1),
	[NAME] [nvarchar](100) NOT NULL,
        [ALGO_TYPE] varchar(50) NOT NULL,
	[SCRIPT] [nvarchar](500) NULL,
	[CONTAINER_PROPERTIES] [nvarchar](max) NULL,
	[ALGORITHM_PROPERTIES] [nvarchar](max) NULL,
	[PRIORITY] [smallint] NOT NULL,
	[SAMPLE_NAME] [nvarchar](100) NULL,
	[FK_MODEL_DEF_ID] [int] NOT NULL,
 CONSTRAINT [PK_ALGORITHM] PRIMARY KEY CLUSTERED 
(
	[PID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MODEL]    Script Date: 05/28/2014 18:00:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MODEL](
	[PID] [int] NOT NULL IDENTITY (1000, 1),
	[MODEL_ID] [varchar](50) NOT NULL,
	[NAME] [nvarchar](100) NULL,
	[DATA_HDFS_PATH] [varchar](200) NULL,
    [METADATA_HDFS_PATH] [varchar](200) NULL,
	[SCHEMA_HDFS_PATH] [varchar](200) NULL,
	[MODEL_HDFS_DIR] [varchar](200) NULL,
	[FEATURES] [nvarchar](max) NULL,
	[TARGETS] [nvarchar](100) NULL,
	[KEYCOLS] [nvarchar](500) NULL,
	[FK_MODEL_DEF_ID] [int] NOT NULL,
	[DATA_FORMAT] [nvarchar](50) NULL,
	[CUSTOMER] [nvarchar](100) NULL,
	[TABLE_NAME] [nvarchar](100) NULL,
	[METADATA_TABLE] [nvarchar](100) NULL,
 CONSTRAINT [PK_MODEL_1] PRIMARY KEY CLUSTERED 
(
	[PID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[JOB]    Script Date: 05/28/2014 18:00:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[JOB](
	[PID] [int] NOT NULL IDENTITY (1000, 1),
	[JOB_ID] [varchar](50) NOT NULL,
	[CLIENT] [nvarchar](50) NOT NULL,
	[APPMASTER_PROPERTIES] [nvarchar](max) NULL,
	[CONTAINER_PROPERTIES] [nvarchar](max) NULL,
	[CHILD_JOB_IDS] [varchar](100) NULL,
	[FK_MODEL_ID] [int] NOT NULL,
	[PARENT_JOB_ID] [int] NULL,
 CONSTRAINT [PK_JOB_1] PRIMARY KEY CLUSTERED 
(
	[PID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  ForeignKey [FK_ALGORITHM_MODEL_DEFINITION]    Script Date: 05/28/2014 18:00:04 ******/
ALTER TABLE [dbo].[ALGORITHM]  WITH CHECK ADD  CONSTRAINT [FK_ALGORITHM_MODEL_DEFINITION] FOREIGN KEY([FK_MODEL_DEF_ID])
REFERENCES [dbo].[MODEL_DEFINITION] ([PID])
GO
ALTER TABLE [dbo].[ALGORITHM] CHECK CONSTRAINT [FK_ALGORITHM_MODEL_DEFINITION]
GO
/****** Object:  ForeignKey [FK_JOB_JOB]    Script Date: 05/28/2014 18:00:04 ******/
ALTER TABLE [dbo].[JOB]  WITH CHECK ADD  CONSTRAINT [FK_JOB_JOB] FOREIGN KEY([PARENT_JOB_ID])
REFERENCES [dbo].[JOB] ([PID])
GO
ALTER TABLE [dbo].[JOB] CHECK CONSTRAINT [FK_JOB_JOB]
GO
/****** Object:  ForeignKey [FK_JOB_MODEL1]    Script Date: 05/28/2014 18:00:04 ******/
ALTER TABLE [dbo].[JOB]  WITH CHECK ADD  CONSTRAINT [FK_JOB_MODEL1] FOREIGN KEY([FK_MODEL_ID])
REFERENCES [dbo].[MODEL] ([PID])
GO
ALTER TABLE [dbo].[JOB] CHECK CONSTRAINT [FK_JOB_MODEL1]
GO
/****** Object:  ForeignKey [FK_MODEL_MODEL_DEFINITION]    Script Date: 05/28/2014 18:00:04 ******/
ALTER TABLE [dbo].[MODEL]  WITH CHECK ADD  CONSTRAINT [FK_MODEL_MODEL_DEFINITION] FOREIGN KEY([FK_MODEL_DEF_ID])
REFERENCES [dbo].[MODEL_DEFINITION] ([PID])
GO
ALTER TABLE [dbo].[MODEL] CHECK CONSTRAINT [FK_MODEL_MODEL_DEFINITION]
GO

