#!/bin/bash
rm -rf /opt/jetty/webapps/le-pls-*.war
rm -rf /etc/ledp/db.properties
rm -rf /etc/ledp/pls.properties
rm -rf /etc/ledp/security.properties
rm -rf /opt/jetty/bin/jetty.sh
rm -rf /opt/jetty/start.ini
rm -rf /opt/jetty/etc/jetty.xml
rm -rf /opt/jetty/etc/jetty-rewrite.xml
rm -rf /home/yarn/.bashrc
rm -rf /tmp/jetty-*
adduser yarn
groupadd yarn
mkdir -p /var/log/ledp
mkdir -p /home/yarn/logs
chmod -R 755 /var/log/ledp
chmod -R 755 /home/yarn/logs
chown -R yarn:yarn /var/log/ledp
chown -R yarn:yarn /home/yarn/logs
chown -R yarn:yarn /opt/jetty
