#!/bin/bash -x
source /etc/profile
echo "getting environment information"
echo $ENV_TYPE
echo $CATALINA_HOME
cd /tmp/webapps/pls

JARFILE=`ls le-pls-*.war`
VERSION=`echo $JARFILE | cut -d \- -f 3`
SNAPSHOT=`echo $JARFILE | cut -d \- -f 4`

if test $SNAPSHOT = "SNAPSHOT"
    then
        VERSION=$VERSION-"SNAPSHOT"
fi
echo $VERSION

echo "copying files from temporary folders"
cp le-pls-*.war $CATALINA_HOME/webapps/pls/ROOT.war
cp /etc/ledp/pls/$ENV_TYPE/*.properties /etc/ledp/
cp /etc/ledp/pls/$ENV_TYPE/laca-ldap.dev.lattice.local.jks /etc/ledp/

echo "cleaning up"
rm -rf /etc/ledp/pls
rm -rf /home/yarn/pls
rm -rf /home/yarn/logs/*
rm -rf /tmp/webapps/pls

echo "finishing"
ls $CATALINA_HOME/webapp/pls/*.war
