#!/bin/bash -x
source /etc/profile
echo "getting environment information"
echo $ENV_TYPE
echo $CATALINA_HOME
cd /tmp/webapps/oauth2

JARFILE=`ls le-oauth2-*.war`
VERSION=`echo $JARFILE | cut -d \- -f 3`
SNAPSHOT=`echo $JARFILE | cut -d \- -f 4`

if test $SNAPSHOT = "SNAPSHOT"
    then
        VERSION=$VERSION-"SNAPSHOT"
fi
echo $VERSION

echo "copying files from temporary folders"
cp le-oauth2-*.war $CATALINA_HOME/webapps/oauth/ROOT.war
cp /etc/ledp/oauth2/$ENV_TYPE/*.properties /etc/ledp/

echo "cleaning up"
rm -rf /etc/ledp/oauth2
rm -rf /home/yarn/oauth2
rm -rf /home/yarn/logs/*
rm -rf /tmp/webapps/oauth2

echo "finishing"
chown -R root:tomcat $CATALINA_HOME/webapps
ls $CATALINA_HOME/webapps/oauth/*.war