#!/bin/bash -x
source /etc/profile
echo "getting environment information"
echo $ENV_TYPE
echo $CATALINA_HOME
cd /tmp/webapps/oauth2

JAVAFILE=`ls le-oauth2-*.war`
VERSION=`echo $JAVAFILE | cut -d\- -f3`
SNAPSHOT=`echo $JAVAFILE | cut -d\- -f4`
if test $SNAPSHOT='SNAPSHOT'
then
    VERSION=$VERSION-$SHAPSHOT
fi

echo "copying files from temporary folders"
cp le-oauth2-*.war $CATALINA_HOME/webapps/oauth2/oauth2\#\#$VERSION.war
cp ROOT.war $CATALINA_HOME/webapps/oauth2/ROOT.war
cp /etc/ledp/oauth2/$ENV_TYPE/*.properties /etc/ledp/

echo "cleaning up"
rm -rf /etc/ledp/oauth2
rm -rf /home/yarn/oauth2
rm -rf /home/yarn/logs/*
rm -rf /tmp/webapps/oauth2

echo "finishing"
ls $CATALINA_HOME/webapps/oauth2/*.war