#!/bin/bash
source /etc/profile
rm -rf $CATALINA_HOME/webapps/oauth2/le-oauth2-*.war
rm -rf $CATALINA_HOME/webapps/oauth2/ROOT.war
rm -rf /tmp/webapps/oauth2/le-oauth2-*.war
rm -rf /tmp/webapps/oauth2/ROOT.war
rm -rf /etc/ledp/oauth2.properties
adduser yarn
groupadd yarn
mkdir -p /var/log/ledp
mkdir -p /home/yarn/logs
chmod -R 755 /var/log/ledp
chmod -R 755 /home/yarn/logs
chown -R yarn:yarn /var/log/ledp
chown -R yarn:yarn /home/yarn/logs