USE `PLS_MultiTenant`;

CREATE PROCEDURE `UpdatePLSTables`()
BEGIN
    ALTER TABLE `PLAY_LAUNCH`
      ADD COLUMN `FK_WORKFLOW_ID` bigint DEFAULT NULL,
      ADD COLUMN `FK_DELTA_CALC_WORKFLOW_ID` bigint DEFAULT NULL,
      ADD COLUMN `IS_SCHEDULED_LAUNCH` BIT DEFAULT 0 NOT NULL;

    UPDATE `PLAY_LAUNCH`
      SET IS_SCHEDULED_LAUNCH = CASE WHEN CREATED_BY = 'build-admin@lattice-engines.com' THEN 1 ELSE 0 END; -- build@lattice-engines.com for QA

    ALTER TABLE `TENANT` ADD COLUMN `ENTITLED_APPS` varchar(255) DEFAULT NULL;
    UPDATE `TENANT` SET ENTITLED_APPS="Lattice";

    CREATE TABLE `STRING_TEMPLATE` (
          `PID` bigint(20) NOT NULL AUTO_INCREMENT,
          `NAME` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
          `TEMPLATE` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
          PRIMARY KEY (`PID`),
          UNIQUE KEY `UK32mlafkdqky1cgch77plnbrir` (`NAME`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

    ALTER TABLE `PLS_MultiTenant`.`ACTIVITY_METRIC_GROUP`
            CHANGE COLUMN `DESCRIPTION_TMPL` `DESCRIPTION_TMPL` BIGINT(20) NULL DEFAULT NULL ,
            CHANGE COLUMN `DISPLAY_NAME_TMPL` `DISPLAY_NAME_TMPL` BIGINT(20) NOT NULL ,
            CHANGE COLUMN `SUBCATEGORY_TMPL` `SUBCATEGORY_TMPL` BIGINT(20) NOT NULL ,
            ADD COLUMN `NULL_IMP` varchar(255) DEFAULT NULL ,
            ADD COLUMN `REDUCER` json DEFAULT NULL;

    ALTER TABLE `PLS_MultiTenant`.`ACTIVITY_METRIC_GROUP`
        ADD CONSTRAINT `DISPLAY_NAME_TMPL`
          FOREIGN KEY (`DISPLAY_NAME_TMPL`)
          REFERENCES `PLS_MultiTenant`.`STRING_TEMPLATE` (`PID`)
          ON DELETE NO ACTION
          ON UPDATE NO ACTION,
        ADD CONSTRAINT `DESCRIPTION_TMPL`
          FOREIGN KEY (`DESCRIPTION_TMPL`)
          REFERENCES `PLS_MultiTenant`.`STRING_TEMPLATE` (`PID`)
          ON DELETE NO ACTION
          ON UPDATE NO ACTION,
        ADD CONSTRAINT `SUBCATEGORY_TMPL`
          FOREIGN KEY (`SUBCATEGORY_TMPL`)
          REFERENCES `PLS_MultiTenant`.`STRING_TEMPLATE` (`PID`)
          ON DELETE NO ACTION
          ON UPDATE NO ACTION;

    /* Changes after this are found from the diff */
    ALTER TABLE `PLS_MultiTenant`.`WORKFLOW_JOB_EXECUTION_CONTEXT`
        DROP FOREIGN KEY JOB_EXEC_CTX_FK;

    ALTER TABLE `PLS_MultiTenant`.`ATLAS_CATALOG`
        CHANGE COLUMN `CATALOG_ID` `CATALOG_ID` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL;

    ALTER TABLE `PLS_MultiTenant`.`ATLAS_S3_IMPORT_SYSTEM`
        CHANGE COLUMN `PRIORITY` `PRIORITY` int(11) DEFAULT NULL,
        CHANGE COLUMN `MAP_TO_LATTICE_ACCOUNT` `MAP_TO_LATTICE_ACCOUNT` BIT DEFAULT 0,
        CHANGE COLUMN `MAP_TO_LATTICE_CONTACT` `MAP_TO_LATTICE_CONTACT` BIT DEFAULT 0;

    ALTER TABLE `PLS_MultiTenant`.`ATLAS_STREAM`
        CHANGE COLUMN `STREAM_ID` `STREAM_ID` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
        ADD COLUMN `REDUCER` json DEFAULT NULL;

     ALTER TABLE `PLS_MultiTenant`.`ATLAS_STREAM_DIMENSION`
        CHANGE COLUMN `USAGES` `USAGES` json DEFAULT NULL;

     ALTER TABLE `PLS_MultiTenant`.`DATAFEED_EXECUTION`
        CHANGE COLUMN `UPDATED` `UPDATED` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        CHANGE COLUMN `CREATED` `CREATED` datetime DEFAULT CURRENT_TIMESTAMP;

     ALTER TABLE `PLS_MultiTenant`.`DATAFEED_TASK`
        CHANGE COLUMN `LAST_UPDATED` `LAST_UPDATED` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

     ALTER TABLE `PLS_MultiTenant`.`METADATA_DATA_COLLECTION_STATUS`
        CHANGE COLUMN `Detail` `DETAIL` json DEFAULT NULL;
END;
//
DELIMITER;

CALL `UpdatePLSTables`();
