#!/bin/bash -x
source /etc/profile
echo "getting environment information"
echo $ENV_TYPE

echo "copying files from temporary folders"
cp /tmp/ledp/$ENV_TYPE/*.properties /etc/ledp/
chmod 755 /etc/ledp/*

echo "cleaning up"
rm -rf /tmp/ledp

echo "finishing"
ll /etc/ledp/
