#!/bin/bash -x
source /etc/profile

echo "getting environment information"
echo $LE_ENVIRONMENT
echo $LE_STACK
echo $STACK_PROFILE


echo "copying files"
cd /tmp/le-ui
tar xzf le-ui.tar.gz

cat ${STACK_PROFILE}

for kv in $(cat ${STACK_PROFILE});
do
	key=$(echo $kv | cut -d = -f 1)
	value=$(echo $kv | cut -d = -f 2-)
	echo $key $value
	sed -i "s|\${${key}}|${value}|g" /tmp/le-ui/conf/env/${LE_ENVIRONMENT}/ENV_VARS
done


cd le-ui
cp -rf . /opt/node/latest
cp /opt/node/latest/conf/env/$LE_ENVIRONMENT/ENV_VARS /opt/node/latest
chmod -R 755 /opt/node/latest

echo "cleaning up"
rm -rf /opt/node/latest/conf


