#!/bin/bash -x
source /etc/profile

echo "getting environment information"
echo $LE_ENVIRONMENT
echo $LE_STACK
echo $STACK_PROFILE


echo "copying files"
cd /tmp/le-ui
tar xzf le-ui.tar.gz

cd le-ui
cp -rf . /opt/node/latest
cp /opt/node/latest/conf/env/${LE_ENVIRONMENT}/ENV_VARS /opt/node/latest
chmod -R 755 /opt/node/latest

cat ${STACK_PROFILE}
ls /opt/node/latest/conf/env/${LE_ENVIRONMENT}/
python replace_token.py /opt/node/latest/conf/env/${LE_ENVIRONMENT}/ ${STACK_PROFILE}

echo "cleaning up"
rm -rf /opt/node/latest/conf
cat /opt/node/latest/conf/ENV_VARS


