#!/bin/bash -x

adduser ledp
groupadd ledp

if [ ! -d "/opt/node/latest" ]; then
    mkdir -p /opt/node/latest
fi
rm -rf /opt/node/latest/*

if [ ! -d "/tmp/le-ui" ]; then
    mkdir -p /tmp/le-ui
fi
rm -rf /tmp/le-ui/*