alter table `ALGORITHM` drop foreign key FKB388C44F5FB2DB1E;
alter table `DATAFLOW_JOB` drop foreign key FK4E6B9EB6E88B2327;
alter table `EAI_JOB` drop foreign key FKB529FB8BE88B2327;
alter table `METADATA_ATTRIBUTE` drop foreign key FKE2E7316C5FC50F27;
alter table `METADATA_EXTRACT` drop foreign key FKCD56DB515FC50F27;
alter table `METADATA_LASTMODIFIED_KEY` drop foreign key FK56B5EC6F5FC50F27;
alter table `METADATA_PRIMARY_KEY` drop foreign key FKA4B6A5525FC50F27;
alter table `METADATA_TABLE` drop foreign key FK4176B29E36865BC;
alter table `MODELING_JOB` drop foreign key FK92A4EA77AC061AB1;
alter table `MODELING_JOB` drop foreign key FK92A4EA77E88B2327;
alter table `MODEL_SUMMARY` drop foreign key FKCEB8C450AC2B0EB2;
alter table `MODEL_SUMMARY` drop foreign key FKCEB8C45036865BC;
alter table `MODEL` drop foreign key FK46203095FB2DB1E;
alter table `OAUTH2_ACCESS_TOKEN` drop foreign key FK5FB0F86236865BC;
alter table `PREDICTOR_ELEMENT` drop foreign key FKC39535F9F9802A4B;
alter table `PREDICTOR` drop foreign key FK55BF005C8807F0C9;
alter table `QUOTA` drop foreign key FK49D465836865BC;
alter table `REPORT` drop foreign key FK8FDF4934AC2B0EB2;
alter table `REPORT` drop foreign key FK8FDF493436865BC;
alter table `SEGMENT` drop foreign key FKA0702B1336865BC;
alter table `SOURCE_FILE` drop foreign key FK7D04A32036865BC;
alter table `TARGET_MARKET_DATA_FLOW_OPTION` drop foreign key FK18B26886AFC9B7C6;
alter table `TARGET_MARKET_REPORT_MAP` drop foreign key FK16FEE466799FEF17;
alter table `TARGET_MARKET_REPORT_MAP` drop foreign key FK16FEE466AFC9B7C6;
alter table `TARGET_MARKET` drop foreign key FKDD9CEAAA36865BC;
alter table `WORKFLOW_JOB` drop foreign key FKE7361F1D36865BC;
drop table if exists `ALGORITHM`;
drop table if exists `AccountMaster_Accounts`;
drop table if exists `AccountMaster_Attributes`;
drop table if exists `AccountMaster_Contacts`;
drop table if exists `DATAFLOW_JOB`;
drop table if exists `EAI_JOB`;
drop table if exists `JOB`;
drop table if exists `KEY_VALUE`;
drop table if exists `METADATA_ATTRIBUTE`;
drop table if exists `METADATA_EXTRACT`;
drop table if exists `METADATA_LASTMODIFIED_KEY`;
drop table if exists `METADATA_PRIMARY_KEY`;
drop table if exists `METADATA_TABLE`;
drop table if exists `MODELING_JOB`;
drop table if exists `MODEL_DEFINITION`;
drop table if exists `MODEL_SUMMARY`;
drop table if exists `MODEL`;
drop table if exists `OAUTH2_ACCESS_TOKEN`;
drop table if exists `PREDICTOR_ELEMENT`;
drop table if exists `PREDICTOR`;
drop table if exists `PROSPECT_DISCOVERY_OPTION`;
drop table if exists `QUOTA`;
drop table if exists `REPORT`;
drop table if exists `SALESFORCE_URL`;
drop table if exists `SEGMENT`;
drop table if exists `SOURCE_FILE`;
drop table if exists `TARGET_MARKET_DATA_FLOW_OPTION`;
drop table if exists `TARGET_MARKET_REPORT_MAP`;
drop table if exists `TARGET_MARKET`;
drop table if exists `TENANT_DEPLOYMENT`;
drop table if exists `TENANT`;
drop table if exists `THROTTLE_CONFIGURATION`;
drop table if exists `WORKFLOW_JOB`;
create table `ALGORITHM` (`ALGO_TYPE` varchar(31) not null, `PID` bigint not null auto_increment unique, `ALGORITHM_PROPERTIES` longtext, `CONTAINER_PROPERTIES` longtext, `NAME` varchar(255) not null, `PIPELINE_DRIVER` varchar(255), `PIPELINE_LIB_SCRIPT` varchar(255), `PIPELINE_PROPERTIES` longtext, `PIPELINE_SCRIPT` varchar(255), `PRIORITY` integer not null, `SAMPLE_NAME` varchar(255), `SCRIPT` varchar(500), FK_MODEL_DEF_ID bigint, primary key (`PID`)) ENGINE=InnoDB;
create table `AccountMaster_Accounts` (`LatticeAccountID` bigint not null unique, `City` varchar(255), `Country` varchar(255), `Domain` varchar(255), `EmployeesRange` varchar(255), `Industry` varchar(255), `InsideViewID` integer, `Name` varchar(255), `ParentID` bigint, `Region` varchar(255), `RevenueRange` varchar(255), `State` varchar(255), `Street` varchar(255), `SubIndustry` varchar(255), primary key (`LatticeAccountID`)) ENGINE=InnoDB;
create table `AccountMaster_Attributes` (`PID` bigint not null auto_increment unique, `AttrKey` varchar(255) not null, `AttrValue` varchar(255) not null, `ParentKey` varchar(255), `ParentValue` varchar(255), `Source` varchar(255), primary key (`PID`)) ENGINE=InnoDB;
create table `AccountMaster_Contacts` (`PID` bigint not null unique, `ContactID` varchar(255) not null unique, `CompanyID` bigint, `Email` varchar(255), `FirstName` varchar(255), `JobLevel` varchar(255), `JobType` varchar(255), `LastName` varchar(255), `Phone` varchar(255), `Titles` varchar(255), primary key (`PID`, `ContactID`)) ENGINE=InnoDB;
create table `DATAFLOW_JOB` (`CUSTOMER` varchar(255), `DATAFLOW_BEAN_NAME` varchar(255), `JOB_PID` bigint not null, primary key (`JOB_PID`)) ENGINE=InnoDB;
create table `EAI_JOB` (`TABLES` varchar(255), `JOB_PID` bigint not null, primary key (`JOB_PID`)) ENGINE=InnoDB;
create table `JOB` (`JOB_PID` bigint not null auto_increment unique, `APPMASTER_PROPERTIES` longtext, `CLIENT` varchar(255) not null, `CONTAINER_PROPERTIES` longtext, `CUSTOMER` varchar(255), `JOB_ID` varchar(255) not null, primary key (`JOB_PID`)) ENGINE=InnoDB;
create table `KEY_VALUE` (`PID` bigint not null auto_increment unique, `DATA` longblob not null, `OWNER_TYPE` varchar(255) not null, `TENANT_ID` bigint not null, primary key (`PID`)) ENGINE=InnoDB;
create table `METADATA_ATTRIBUTE` (`PID` bigint not null auto_increment unique, `ENUM_VALUES` varchar(2048), `DISPLAY_NAME` varchar(255) not null, `LENGTH` integer, `LOGICAL_DATA_TYPE` varchar(255), `NAME` varchar(255) not null, `NULLABLE` boolean not null, `DATA_TYPE` varchar(255) not null, `PRECISION` integer, `PROPERTIES` longblob not null, `SCALE` integer, `SOURCE_LOGICAL_DATA_TYPE` varchar(255), `TENANT_ID` bigint not null, `VALIDATORS` longblob, FK_TABLE_ID bigint not null, primary key (`PID`)) ENGINE=InnoDB;
create table `METADATA_EXTRACT` (`PID` bigint not null auto_increment unique, `EXTRACTION_TS` bigint not null, `NAME` varchar(255) not null, `PATH` varchar(255) not null, `PROCESSED_RECORDS` bigint not null, `TENANT_ID` bigint not null, FK_TABLE_ID bigint not null, primary key (`PID`)) ENGINE=InnoDB;
create table `METADATA_LASTMODIFIED_KEY` (`PID` bigint not null auto_increment unique, `ATTRIBUTES` varchar(2048) not null, `DISPLAY_NAME` varchar(255) not null, `NAME` varchar(255) not null, `LAST_MODIFIED_TS` bigint not null, FK_TABLE_ID bigint not null, primary key (`PID`)) ENGINE=InnoDB;
create table `METADATA_PRIMARY_KEY` (`PID` bigint not null auto_increment unique, `ATTRIBUTES` varchar(2048) not null, `DISPLAY_NAME` varchar(255) not null, `NAME` varchar(255) not null, FK_TABLE_ID bigint not null, primary key (`PID`)) ENGINE=InnoDB;
create table `METADATA_TABLE` (`PID` bigint not null auto_increment unique, `DISPLAY_NAME` varchar(255) not null, `INTERPRETATION` varchar(255), `MARKED_FOR_PURGE` boolean not null, `NAME` varchar(255) not null, `TYPE` integer not null, `TENANT_ID` bigint not null, FK_TENANT_ID bigint not null, primary key (`PID`), unique (`TENANT_ID`, `NAME`, `TYPE`)) ENGINE=InnoDB;
create table `MODELING_JOB` (`CHILD_JOB_IDS` varchar(255), `PARENT_PID` bigint, `JOB_PID` bigint not null, FK_MODEL_ID bigint, primary key (`JOB_PID`)) ENGINE=InnoDB;
create table `MODEL_DEFINITION` (`PID` bigint not null auto_increment unique, `NAME` varchar(255) not null, primary key (`PID`)) ENGINE=InnoDB;
create table `MODEL_SUMMARY` (`PID` bigint not null auto_increment unique, `APPLICATION_ID` varchar(255), `CONSTRUCTION_TIME` bigint not null, `DISPLAY_NAME` varchar(255), `DOWNLOADED` boolean not null, `EVENT_TABLE_NAME` varchar(255), `ID` varchar(255) not null unique, `INCOMPLETE` boolean not null, `LOOKUP_ID` varchar(255) not null, `NAME` varchar(255) not null, `ROC_SCORE` double precision not null, `SOURCE_SCHEMA_INTERPRETATION` varchar(255), `STATUS` integer not null, `TENANT_ID` bigint not null, `TEST_CONVERSION_COUNT` bigint not null, `TEST_ROW_COUNT` bigint not null, `TOP_10_PCT_LIFT` double precision, `TOP_20_PCT_LIFT` double precision, `TOP_30_PCT_LIFT` double precision, `TOTAL_CONVERSION_COUNT` bigint not null, `TOTAL_ROW_COUNT` bigint not null, `TRAINING_CONVERSION_COUNT` bigint not null, `TRAINING_ROW_COUNT` bigint not null, `TRAINING_TABLE_NAME` varchar(255), `UPLOADED` boolean not null, FK_KEY_VALUE_ID bigint not null, FK_TENANT_ID bigint not null, primary key (`PID`), unique (`ID`), unique (`NAME`, `TENANT_ID`)) ENGINE=InnoDB;
create table `MODEL` (`MODEL_PID` bigint not null auto_increment unique, `CUSTOMER` varchar(255), `DATA_FORMAT` varchar(255), `DATA_HDFS_PATH` varchar(255), `DISPLAY_NAME` varchar(255), `FEATURES` longtext, `MODEL_ID` varchar(255), `KEYCOLS` varchar(500), `METADATA_HDFS_PATH` varchar(255), `METADATA_TABLE` varchar(255), `MODEL_HDFS_DIR` varchar(255), `NAME` varchar(255), `PROVENANCE_PROPERTIES` varchar(2048), `SCHEMA_HDFS_PATH` varchar(255), `TABLE_NAME` varchar(255), `TARGETS` varchar(255), FK_MODEL_DEF_ID bigint, primary key (`MODEL_PID`)) ENGINE=InnoDB;
create table `OAUTH2_ACCESS_TOKEN` (`PID` bigint not null auto_increment unique, `ACCESS_TOKEN` varchar(255) not null, `TENANT_ID` bigint not null, FK_TENANT_ID bigint not null, primary key (`PID`), unique (`TENANT_ID`)) ENGINE=InnoDB;
create table `PREDICTOR_ELEMENT` (`PID` bigint not null auto_increment unique, `CORRELATION_SIGN` integer not null, `COUNT` bigint not null, `LIFT` double precision not null, `LOWER_INCLUSIVE` double precision, `NAME` varchar(255) not null, `TENANT_ID` bigint not null, `UNCERTAINTY_COEFF` double precision not null, `UPPER_EXCLUSIVE` double precision, `VALUES` longtext, `VISIBLE` boolean not null, FK_PREDICTOR_ID bigint not null, primary key (`PID`)) ENGINE=InnoDB;
create table `PREDICTOR` (`PID` bigint not null auto_increment unique, `APPROVED_USAGE` varchar(255), `CATEGORY` varchar(255), `DISPLAY_NAME` varchar(255), `RF_FEATURE_IMPORTANCE` double precision, `FUNDAMENTAL_TYPE` varchar(255), `NAME` varchar(255) not null, `TENANT_ID` bigint not null, `UNCERTAINTY_COEFF` double precision, `USED_FOR_BI` boolean not null, FK_MODELSUMMARY_ID bigint not null, primary key (`PID`)) ENGINE=InnoDB;
create table `PROSPECT_DISCOVERY_OPTION` (`PID` bigint not null auto_increment unique, `OPTION` varchar(255) not null, `TENANT_ID` bigint not null, `VALUE` varchar(255), primary key (`PID`)) ENGINE=InnoDB;
create table `QUOTA` (`PID` bigint not null auto_increment unique, `BALANCE` integer not null, `ID` varchar(255) not null unique, `TENANT_ID` bigint not null, FK_TENANT_ID bigint not null, primary key (`PID`)) ENGINE=InnoDB;
create table `REPORT` (`PID` bigint not null auto_increment unique, `CREATED` datetime not null, `IS_OUT_OF_DATE` boolean not null, `NAME` varchar(255) not null, `PURPOSE` varchar(255) not null, `TENANT_ID` bigint not null, `UPDATED` datetime not null, FK_KEY_VALUE_ID bigint not null, FK_TENANT_ID bigint not null, primary key (`PID`), unique (`NAME`, `TENANT_ID`)) ENGINE=InnoDB;
create table `SALESFORCE_URL` (`PID` bigint not null auto_increment unique, `URL` varchar(255) not null, `NAME` varchar(255) not null unique, primary key (`PID`)) ENGINE=InnoDB;
create table `SEGMENT` (`PID` bigint not null auto_increment unique, `MODEL_ID` varchar(255), `NAME` varchar(255) not null, `PRIORITY` integer not null, `TENANT_ID` bigint not null, FK_TENANT_ID bigint not null, primary key (`PID`), unique (`NAME`, `TENANT_ID`)) ENGINE=InnoDB;
create table `SOURCE_FILE` (`PID` bigint not null auto_increment unique, `APPLICATION_ID` varchar(255), `CREATED` datetime, `DESCRIPTION` varchar(255), `DISPLAY_NAME` varchar(255), `NAME` varchar(255) not null, `PATH` varchar(255) not null, `SCHEMA_INTERPRETATION` varchar(255), `STATE` varchar(255), `TABLE_NAME` varchar(255), `TENANT_ID` bigint not null, `UPDATED` datetime, FK_TENANT_ID bigint not null, primary key (`PID`), unique (`NAME`, `TENANT_ID`)) ENGINE=InnoDB;
create table `TARGET_MARKET_DATA_FLOW_OPTION` (`PID` bigint not null auto_increment unique, `OPTION` varchar(255) not null, `VALUE` varchar(255), TARGET_MARKET_ID bigint not null, primary key (`PID`)) ENGINE=InnoDB;
create table `TARGET_MARKET_REPORT_MAP` (`PID` bigint not null auto_increment unique, REPORT_ID bigint not null, TARGET_MARKET_ID bigint not null, primary key (`PID`)) ENGINE=InnoDB;
create table `TARGET_MARKET` (`PID` bigint not null auto_increment unique, `ACCOUNT_FILTER` varchar(255), `APPLICATION_ID` varchar(255), `CONTACT_FILTER` varchar(255), `CREATION_TIMESTAMP` bigint not null, `DESCRIPTION` varchar(255) not null, `EVENT_COLUMN_NAME` varchar(255), `IS_DEFAULT` boolean, `MODEL_ID` varchar(255), `NAME` varchar(255) not null, `NUM_PROSPECTS_DESIRED` integer, `OFFSET` integer not null, `SELECTED_INTENT` varchar(255), `TENANT_ID` bigint not null, FK_TENANT_ID bigint not null, primary key (`PID`)) ENGINE=InnoDB;
create table `TENANT_DEPLOYMENT` (`PID` bigint not null auto_increment unique, `CREATE_TIME` datetime not null, `CREATED_BY` varchar(255) not null, `CURRENT_LAUNCH_ID` bigint, `MESSAGE` longtext, `MODEL_ID` varchar(255), `STATUS` integer not null, `STEP` integer not null, `TENANT_ID` bigint not null, primary key (`PID`)) ENGINE=InnoDB;
create table `TENANT` (`TENANT_PID` bigint not null auto_increment unique, `TENANT_ID` varchar(255) not null unique, `NAME` varchar(255) not null unique, `REGISTERED_TIME` bigint not null, `UI_VERSION` varchar(255) not null, primary key (`TENANT_PID`)) ENGINE=InnoDB;
create table `THROTTLE_CONFIGURATION` (`PID` bigint not null auto_increment unique, `ENABLED` boolean not null, `IMMEDIATE` boolean not null, `JOB_RANK_CUTOFF` integer not null, `TIMESTAMP` datetime not null, primary key (`PID`)) ENGINE=InnoDB;
create table `WORKFLOW_JOB` (`PID` bigint not null auto_increment unique, `APPLICATION_ID` varchar(255), `ERROR_DETAILS` longtext, `INPUT_CONTEXT` varchar(4000), `START_TIME` bigint, `STATE` varchar(255), `TENANT_ID` bigint not null, `USER_ID` varchar(255), `WORKFLOW_ID` bigint, FK_TENANT_ID bigint not null, primary key (`PID`)) ENGINE=InnoDB;
alter table `ALGORITHM` add index FKB388C44F5FB2DB1E (FK_MODEL_DEF_ID), add constraint FKB388C44F5FB2DB1E foreign key (FK_MODEL_DEF_ID) references `MODEL_DEFINITION` (`PID`);
alter table `DATAFLOW_JOB` add index FK4E6B9EB6E88B2327 (`JOB_PID`), add constraint FK4E6B9EB6E88B2327 foreign key (`JOB_PID`) references `JOB` (`JOB_PID`);
alter table `EAI_JOB` add index FKB529FB8BE88B2327 (`JOB_PID`), add constraint FKB529FB8BE88B2327 foreign key (`JOB_PID`) references `JOB` (`JOB_PID`);
create index KEY_VALUE_TENANT_ID_IDX on `KEY_VALUE` (`TENANT_ID`);
alter table `METADATA_ATTRIBUTE` add index FKE2E7316C5FC50F27 (FK_TABLE_ID), add constraint FKE2E7316C5FC50F27 foreign key (FK_TABLE_ID) references `METADATA_TABLE` (`PID`) on delete cascade;
alter table `METADATA_EXTRACT` add index FKCD56DB515FC50F27 (FK_TABLE_ID), add constraint FKCD56DB515FC50F27 foreign key (FK_TABLE_ID) references `METADATA_TABLE` (`PID`) on delete cascade;
alter table `METADATA_LASTMODIFIED_KEY` add index FK56B5EC6F5FC50F27 (FK_TABLE_ID), add constraint FK56B5EC6F5FC50F27 foreign key (FK_TABLE_ID) references `METADATA_TABLE` (`PID`) on delete cascade;
alter table `METADATA_PRIMARY_KEY` add index FKA4B6A5525FC50F27 (FK_TABLE_ID), add constraint FKA4B6A5525FC50F27 foreign key (FK_TABLE_ID) references `METADATA_TABLE` (`PID`) on delete cascade;
alter table `METADATA_TABLE` add index FK4176B29E36865BC (FK_TENANT_ID), add constraint FK4176B29E36865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`) on delete cascade;
alter table `MODELING_JOB` add index FK92A4EA77AC061AB1 (FK_MODEL_ID), add constraint FK92A4EA77AC061AB1 foreign key (FK_MODEL_ID) references `MODEL` (`MODEL_PID`);
alter table `MODELING_JOB` add index FK92A4EA77E88B2327 (`JOB_PID`), add constraint FK92A4EA77E88B2327 foreign key (`JOB_PID`) references `JOB` (`JOB_PID`);
create index MODEL_SUMMARY_ID_IDX on `MODEL_SUMMARY` (`ID`);
create index MODEL_SUMMARY_NAME_IDX on `MODEL_SUMMARY` (`NAME`);
alter table `MODEL_SUMMARY` add index FKCEB8C450AC2B0EB2 (FK_KEY_VALUE_ID), add constraint FKCEB8C450AC2B0EB2 foreign key (FK_KEY_VALUE_ID) references `KEY_VALUE` (`PID`) on delete cascade;
alter table `MODEL_SUMMARY` add index FKCEB8C45036865BC (FK_TENANT_ID), add constraint FKCEB8C45036865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`) on delete cascade;
alter table `MODEL` add index FK46203095FB2DB1E (FK_MODEL_DEF_ID), add constraint FK46203095FB2DB1E foreign key (FK_MODEL_DEF_ID) references `MODEL_DEFINITION` (`PID`);
alter table `OAUTH2_ACCESS_TOKEN` add index FK5FB0F86236865BC (FK_TENANT_ID), add constraint FK5FB0F86236865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`) on delete cascade;
alter table `PREDICTOR_ELEMENT` add index FKC39535F9F9802A4B (FK_PREDICTOR_ID), add constraint FKC39535F9F9802A4B foreign key (FK_PREDICTOR_ID) references `PREDICTOR` (`PID`) on delete cascade;
alter table `PREDICTOR` add index FK55BF005C8807F0C9 (FK_MODELSUMMARY_ID), add constraint FK55BF005C8807F0C9 foreign key (FK_MODELSUMMARY_ID) references `MODEL_SUMMARY` (`PID`) on delete cascade;
create index PROSPECT_DISCOVERY_OPTION_OPTION_IDX on `PROSPECT_DISCOVERY_OPTION` (`OPTION`);
create index PROSPECT_DISCOVERY_OPTION_TENANT_ID_IDX on `PROSPECT_DISCOVERY_OPTION` (`TENANT_ID`);
alter table `QUOTA` add index FK49D465836865BC (FK_TENANT_ID), add constraint FK49D465836865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`) on delete cascade;
alter table `REPORT` add index FK8FDF4934AC2B0EB2 (FK_KEY_VALUE_ID), add constraint FK8FDF4934AC2B0EB2 foreign key (FK_KEY_VALUE_ID) references `KEY_VALUE` (`PID`);
alter table `REPORT` add index FK8FDF493436865BC (FK_TENANT_ID), add constraint FK8FDF493436865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`) on delete cascade;
alter table `SEGMENT` add index FKA0702B1336865BC (FK_TENANT_ID), add constraint FKA0702B1336865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`) on delete cascade;
alter table `SOURCE_FILE` add index FK7D04A32036865BC (FK_TENANT_ID), add constraint FK7D04A32036865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`) on delete cascade;
create index PROSPECT_DISCOVERY_OPTION_OPTION_IDX on `TARGET_MARKET_DATA_FLOW_OPTION` (`OPTION`);
alter table `TARGET_MARKET_DATA_FLOW_OPTION` add index FK18B26886AFC9B7C6 (TARGET_MARKET_ID), add constraint FK18B26886AFC9B7C6 foreign key (TARGET_MARKET_ID) references `TARGET_MARKET` (`PID`) on delete cascade;
alter table `TARGET_MARKET_REPORT_MAP` add index FK16FEE466799FEF17 (REPORT_ID), add constraint FK16FEE466799FEF17 foreign key (REPORT_ID) references `REPORT` (`PID`);
alter table `TARGET_MARKET_REPORT_MAP` add index FK16FEE466AFC9B7C6 (TARGET_MARKET_ID), add constraint FK16FEE466AFC9B7C6 foreign key (TARGET_MARKET_ID) references `TARGET_MARKET` (`PID`);
alter table `TARGET_MARKET` add index FKDD9CEAAA36865BC (FK_TENANT_ID), add constraint FKDD9CEAAA36865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`);
alter table `WORKFLOW_JOB` add index FKE7361F1D36865BC (FK_TENANT_ID), add constraint FKE7361F1D36865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`) on delete cascade;
