alter table `ColumnMapping` drop foreign key FK9166C0784570DE77;
alter table `MatchBlock` drop foreign key FKE46329E8592F5320;
alter table `PublicationProgress` drop foreign key FKB19FA459DFA664;
drop table if exists `ArchiveProgress`;
drop table if exists `ColumnMapping`;
drop table if exists `ExternalColumn`;
drop table if exists `MatchBlock`;
drop table if exists `MatchCommand`;
drop table if exists `PublicationProgress`;
drop table if exists `Publication`;
drop table if exists `RefreshProgress`;
drop table if exists `SourceColumn`;
drop table if exists `TransformationProgress`;
create table `ArchiveProgress` (`ProgressID` bigint not null auto_increment unique, `CreateTime` datetime, `CreatedBy` varchar(255), `EndDate` datetime, `ErrorMessage` varchar(255), `LatestStatusUpdate` datetime, `NumRetries` integer, `RootOperationUID` varchar(255) not null unique, `RowsDownloadedToHDFS` bigint, `RowsUploadedToSQL` bigint, `SourceName` varchar(255) not null, `StartDate` datetime, `Status` varchar(255), `StatusBeforeFailed` varchar(255), primary key (`ProgressID`));
create table `ColumnMapping` (`PID` bigint not null auto_increment unique, `Priority` integer, `SourceColumn` varchar(100), `SourceName` varchar(100) not null, ExternalColumnID varchar(100) not null, primary key (`PID`));
create table `ExternalColumn` (`ExternalColumnID` varchar(100) not null, `ApprovedUsage` varchar(255), `Category` varchar(50), `DataType` varchar(50) not null, `DefaultColumnName` varchar(100) not null, `Description` longtext not null, `DisplayDiscretizationStrategy` longtext, `DisplayName` varchar(255), `FundamentalType` varchar(50), `PID` bigint not null unique, `StatisticalType` varchar(50), `Tags` longtext, primary key (`ExternalColumnID`));
create table `MatchBlock` (`PID` bigint not null auto_increment, `ApplicationId` varchar(255), `ApplicationState` varchar(20) not null, `BlockOperationUID` varchar(100) not null, `CreateTime` datetime, `ErrorMessage` varchar(255), `LatestStatusUpdate` datetime, `NumRetries` integer, `NumRows` integer not null, `Progress` float, `StateBeforeFailed` varchar(20), FK_MatchCommand bigint not null, primary key (`PID`));
create table `MatchCommand` (`PID` bigint not null auto_increment, `ApplicationId` varchar(50), `ColumnSelection` varchar(50), `CreateTime` datetime, `Customer` varchar(200), `ErrorMessage` longtext, `LatestStatusUpdate` datetime, `MatchStatus` varchar(20) not null, `NumRetries` integer, `Progress` float, `ResultLocation` longtext, `RootOperationUID` varchar(100) not null unique, `RowsMatched` integer, `RowsRequested` integer not null, `StatusBeforeFailed` varchar(20), primary key (`PID`));
create table `PublicationProgress` (`PID` bigint not null auto_increment, `ApplicationId` varchar(255), `CreateTime` datetime not null, `CreatedBy` varchar(255) not null, `Destination` longtext not null, `ErrorMessage` longtext, `LatestStatusUpdate` datetime not null, `Progress` float, `Retries` integer, `SourceVersion` varchar(50) not null, `Status` varchar(20) not null, FK_Publication bigint not null, primary key (`PID`));
create table `Publication` (`PID` bigint not null auto_increment, `CronExpression` varchar(20), `DestinationConfig` longtext not null, `NewJobMaxRetry` integer, `NewJobRetryInterval` bigint, `PublicationName` varchar(100) not null unique, `PublicationType` varchar(20) not null, `SchedularEnabled` boolean, `SourceName` varchar(100) not null, primary key (`PID`));
create table `RefreshProgress` (`ProgressID` bigint not null auto_increment unique, `BaseSourceVersion` varchar(255), `CreateTime` datetime, `CreatedBy` varchar(255), `ErrorMessage` varchar(255), `LatestStatusUpdate` datetime, `NumRetries` integer, `PivotDate` datetime, `RootOperationUID` varchar(255) not null unique, `RowsGeneratedInHDFS` bigint, `RowsUploadedToSQL` bigint, `SourceName` varchar(255) not null, `Status` varchar(255), `StatusBeforeFailed` varchar(255), primary key (`ProgressID`));
create table `SourceColumn` (`SourceColumnID` bigint not null auto_increment unique, `Arguments` longtext, `BaseSource` varchar(100), `Calculation` varchar(50) not null, `ColumnName` varchar(100) not null, `ColumnType` varchar(50) not null, `GroupBy` varchar(100), `Groups` varchar(255) not null, `Preparation` longtext, `Priority` integer not null, `SourceName` varchar(100) not null, primary key (`SourceColumnID`));
create table `TransformationProgress` (`ProgressID` bigint not null auto_increment unique, `CreateTime` datetime, `CreatedBy` varchar(255), `EndDate` datetime, `ErrorMessage` varchar(255), `LatestStatusUpdate` datetime, `NumRetries` integer, `RootOperationUID` varchar(255) not null unique, `SourceName` varchar(255) not null, `StartDate` datetime, `Status` varchar(255), `Version` varchar(255), primary key (`ProgressID`));
alter table `ColumnMapping` add index FK9166C0784570DE77 (ExternalColumnID), add constraint FK9166C0784570DE77 foreign key (ExternalColumnID) references `ExternalColumn` (`ExternalColumnID`);
create index IX_UID on `MatchBlock` (`BlockOperationUID`);
alter table `MatchBlock` add index FKE46329E8592F5320 (FK_MatchCommand), add constraint FKE46329E8592F5320 foreign key (FK_MatchCommand) references `MatchCommand` (`PID`);
create index IX_UID on `MatchCommand` (`RootOperationUID`);
alter table `PublicationProgress` add index FKB19FA459DFA664 (FK_Publication), add constraint FKB19FA459DFA664 foreign key (FK_Publication) references `Publication` (`PID`);
