alter table [ColumnMapping] drop constraint FK9166C0784570DE77;
alter table [MatchBlock] drop constraint FKE46329E8592F5320;
alter table [PublicationProgress] drop constraint FKB19FA459DFA664;
drop table [ArchiveProgress];
drop table [ColumnMapping];
drop table [ExternalColumn];
drop table [MatchBlock];
drop table [MatchCommand];
drop table [PublicationProgress];
drop table [Publication];
drop table [RefreshProgress];
drop table [SourceColumn];
drop table [TransformationProgress];
create table [ArchiveProgress] ([ProgressID] bigint identity not null unique, [CreateTime] datetime2, [CreatedBy] nvarchar(255), [EndDate] datetime2, [ErrorMessage] nvarchar(255), [LatestStatusUpdate] datetime2, [NumRetries] int, [RootOperationUID] nvarchar(255) not null unique, [RowsDownloadedToHDFS] bigint, [RowsUploadedToSQL] bigint, [SourceName] nvarchar(255) not null, [StartDate] datetime2, [Status] nvarchar(255), [StatusBeforeFailed] nvarchar(255), primary key ([ProgressID]));
create table [ColumnMapping] ([PID] bigint identity not null unique, [Priority] int, [SourceColumn] nvarchar(100), [SourceName] nvarchar(100) not null, ExternalColumnID nvarchar(100) not null, primary key ([PID]));
create table [ExternalColumn] ([ExternalColumnID] nvarchar(100) not null, [ApprovedUsage] nvarchar(255), [Category] nvarchar(50), [DataType] nvarchar(50) not null, [DefaultColumnName] nvarchar(100) not null, [Description] nvarchar(1000) not null, [DisplayDiscretizationStrategy] nvarchar(1000), [DisplayName] nvarchar(255), [FundamentalType] nvarchar(50), [PID] bigint not null unique, [StatisticalType] nvarchar(50), [Tags] nvarchar(500), primary key ([ExternalColumnID]));
create table [MatchBlock] ([PID] bigint identity not null, [ApplicationId] nvarchar(255), [ApplicationState] nvarchar(20) not null, [BlockOperationUID] nvarchar(100) not null, [CreateTime] datetime2, [ErrorMessage] nvarchar(255), [LatestStatusUpdate] datetime2, [NumRetries] int, [NumRows] int not null, [Progress] float, [StateBeforeFailed] nvarchar(20), FK_MatchCommand bigint not null, primary key ([PID]));
create table [MatchCommand] ([PID] bigint identity not null, [ApplicationId] nvarchar(50), [ColumnSelection] nvarchar(50), [CreateTime] datetime2, [Customer] nvarchar(200), [ErrorMessage] nvarchar(1000), [LatestStatusUpdate] datetime2, [MatchStatus] nvarchar(20) not null, [NumRetries] int, [Progress] float, [ResultLocation] nvarchar(400), [RootOperationUID] nvarchar(100) not null unique, [RowsMatched] int, [RowsRequested] int not null, [StatusBeforeFailed] nvarchar(20), primary key ([PID]));
create table [PublicationProgress] ([PID] bigint identity not null, [ApplicationId] nvarchar(255), [CreateTime] datetime2 not null, [CreatedBy] nvarchar(255) not null, [Destination] nvarchar(1000) not null, [ErrorMessage] nvarchar(1000), [LatestStatusUpdate] datetime2 not null, [Progress] float, [Retries] int, [SourceVersion] nvarchar(50) not null, [Status] nvarchar(20) not null, FK_Publication bigint not null, primary key ([PID]));
create table [Publication] ([PID] bigint identity not null, [CronExpression] nvarchar(20), [DestinationConfig] nvarchar(1000) not null, [NewJobMaxRetry] int, [NewJobRetryInterval] bigint, [PublicationName] nvarchar(100) not null unique, [PublicationType] nvarchar(20) not null, [SchedularEnabled] bit, [SourceName] nvarchar(100) not null, primary key ([PID]));
create table [RefreshProgress] ([ProgressID] bigint identity not null unique, [BaseSourceVersion] nvarchar(255), [CreateTime] datetime2, [CreatedBy] nvarchar(255), [ErrorMessage] nvarchar(255), [LatestStatusUpdate] datetime2, [NumRetries] int, [PivotDate] datetime2, [RootOperationUID] nvarchar(255) not null unique, [RowsGeneratedInHDFS] bigint, [RowsUploadedToSQL] bigint, [SourceName] nvarchar(255) not null, [Status] nvarchar(255), [StatusBeforeFailed] nvarchar(255), primary key ([ProgressID]));
create table [SourceColumn] ([SourceColumnID] bigint identity not null unique, [Arguments] nvarchar(1000), [BaseSource] nvarchar(100), [Calculation] nvarchar(50) not null, [ColumnName] nvarchar(100) not null, [ColumnType] nvarchar(50) not null, [GroupBy] nvarchar(100), [Groups] nvarchar(255) not null, [Preparation] nvarchar(1000), [Priority] int not null, [SourceName] nvarchar(100) not null, primary key ([SourceColumnID]));
create table [TransformationProgress] ([ProgressID] bigint identity not null unique, [CreateTime] datetime2, [CreatedBy] nvarchar(255), [EndDate] datetime2, [ErrorMessage] nvarchar(255), [LatestStatusUpdate] datetime2, [NumRetries] int, [RootOperationUID] nvarchar(255) not null unique, [SourceName] nvarchar(255) not null, [StartDate] datetime2, [Status] nvarchar(255), [Version] nvarchar(255), primary key ([ProgressID]));
alter table [ColumnMapping] add constraint FK9166C0784570DE77 foreign key (ExternalColumnID) references [ExternalColumn] on delete cascade;
create index IX_UID on [MatchBlock] ([BlockOperationUID]);
alter table [MatchBlock] add constraint FKE46329E8592F5320 foreign key (FK_MatchCommand) references [MatchCommand] on delete cascade;
create index IX_UID on [MatchCommand] ([RootOperationUID]);
alter table [PublicationProgress] add constraint FKB19FA459DFA664 foreign key (FK_Publication) references [Publication] on delete cascade;
