alter table [ALGORITHM] drop constraint FKB388C44F5FB2DB1E;
alter table [DATAFLOW_JOB] drop constraint FK4E6B9EB6E88B2327;
alter table [EAI_JOB] drop constraint FKB529FB8BE88B2327;
alter table [METADATA_ATTRIBUTE] drop constraint FKE2E7316C5FC50F27;
alter table [METADATA_EXTRACT] drop constraint FKCD56DB515FC50F27;
alter table [METADATA_LASTMODIFIED_KEY] drop constraint FK56B5EC6F5FC50F27;
alter table [METADATA_PRIMARY_KEY] drop constraint FKA4B6A5525FC50F27;
alter table [METADATA_TABLE] drop constraint FK4176B29E36865BC;
alter table [MODELING_JOB] drop constraint FK92A4EA77AC061AB1;
alter table [MODELING_JOB] drop constraint FK92A4EA77E88B2327;
alter table [MODEL_SUMMARY] drop constraint FKCEB8C450AC2B0EB2;
alter table [MODEL_SUMMARY] drop constraint FKCEB8C45036865BC;
alter table [MODEL] drop constraint FK46203095FB2DB1E;
alter table [OAUTH2_ACCESS_TOKEN] drop constraint FK5FB0F86236865BC;
alter table [PREDICTOR_ELEMENT] drop constraint FKC39535F9F9802A4B;
alter table [PREDICTOR] drop constraint FK55BF005C8807F0C9;
alter table [QUOTA] drop constraint FK49D465836865BC;
alter table [REPORT] drop constraint FK8FDF4934AC2B0EB2;
alter table [REPORT] drop constraint FK8FDF493436865BC;
alter table [SEGMENT] drop constraint FKA0702B1336865BC;
alter table [SOURCE_FILE] drop constraint FK7D04A32036865BC;
alter table [TARGET_MARKET_DATA_FLOW_OPTION] drop constraint FK18B26886AFC9B7C6;
alter table [TARGET_MARKET_REPORT_MAP] drop constraint FK16FEE466799FEF17;
alter table [TARGET_MARKET_REPORT_MAP] drop constraint FK16FEE466AFC9B7C6;
alter table [TARGET_MARKET] drop constraint FKDD9CEAAA36865BC;
alter table [WORKFLOW_JOB] drop constraint FKE7361F1D36865BC;
drop table [ALGORITHM];
drop table [AccountMaster_Accounts];
drop table [AccountMaster_Attributes];
drop table [AccountMaster_Contacts];
drop table [DATAFLOW_JOB];
drop table [EAI_JOB];
drop table [JOB];
drop table [KEY_VALUE];
drop table [METADATA_ATTRIBUTE];
drop table [METADATA_EXTRACT];
drop table [METADATA_LASTMODIFIED_KEY];
drop table [METADATA_PRIMARY_KEY];
drop table [METADATA_TABLE];
drop table [MODELING_JOB];
drop table [MODEL_DEFINITION];
drop table [MODEL_SUMMARY];
drop table [MODEL];
drop table [OAUTH2_ACCESS_TOKEN];
drop table [PREDICTOR_ELEMENT];
drop table [PREDICTOR];
drop table [PROSPECT_DISCOVERY_OPTION];
drop table [QUOTA];
drop table [REPORT];
drop table [SALESFORCE_URL];
drop table [SEGMENT];
drop table [SOURCE_FILE];
drop table [TARGET_MARKET_DATA_FLOW_OPTION];
drop table [TARGET_MARKET_REPORT_MAP];
drop table [TARGET_MARKET];
drop table [TENANT_DEPLOYMENT];
drop table [TENANT];
drop table [THROTTLE_CONFIGURATION];
drop table [WORKFLOW_JOB];
create table [ALGORITHM] ([ALGO_TYPE] nvarchar(31) not null, [PID] bigint identity not null unique, [ALGORITHM_PROPERTIES] nvarchar(MAX), [CONTAINER_PROPERTIES] nvarchar(MAX), [NAME] nvarchar(255) not null, [PIPELINE_DRIVER] nvarchar(255), [PIPELINE_LIB_SCRIPT] nvarchar(255), [PIPELINE_PROPERTIES] nvarchar(MAX), [PIPELINE_SCRIPT] nvarchar(255), [PRIORITY] int not null, [SAMPLE_NAME] nvarchar(255), [SCRIPT] nvarchar(500), FK_MODEL_DEF_ID bigint, primary key ([PID]));
create table [AccountMaster_Accounts] ([LatticeAccountID] bigint not null unique, [City] nvarchar(255), [Country] nvarchar(255), [Domain] nvarchar(255), [EmployeesRange] nvarchar(255), [Industry] nvarchar(255), [InsideViewID] int, [Name] nvarchar(255), [ParentID] bigint, [Region] nvarchar(255), [RevenueRange] nvarchar(255), [State] nvarchar(255), [Street] nvarchar(255), [SubIndustry] nvarchar(255), primary key ([LatticeAccountID]));
create table [AccountMaster_Attributes] ([PID] bigint identity not null unique, [AttrKey] nvarchar(255) not null, [AttrValue] nvarchar(255) not null, [ParentKey] nvarchar(255), [ParentValue] nvarchar(255), [Source] nvarchar(255), primary key ([PID]));
create table [AccountMaster_Contacts] ([PID] bigint not null unique, [ContactID] nvarchar(255) not null unique, [CompanyID] bigint, [Email] nvarchar(255), [FirstName] nvarchar(255), [JobLevel] nvarchar(255), [JobType] nvarchar(255), [LastName] nvarchar(255), [Phone] nvarchar(255), [Titles] nvarchar(255), primary key ([PID], [ContactID]));
create table [DATAFLOW_JOB] ([CUSTOMER] nvarchar(255), [DATAFLOW_BEAN_NAME] nvarchar(255), [JOB_PID] bigint not null, primary key ([JOB_PID]));
create table [EAI_JOB] ([TABLES] nvarchar(255), [JOB_PID] bigint not null, primary key ([JOB_PID]));
create table [JOB] ([JOB_PID] bigint identity not null unique, [APPMASTER_PROPERTIES] nvarchar(MAX), [CLIENT] nvarchar(255) not null, [CONTAINER_PROPERTIES] nvarchar(MAX), [CUSTOMER] nvarchar(255), [JOB_ID] nvarchar(255) not null, primary key ([JOB_PID]));
create table [KEY_VALUE] ([PID] bigint identity not null unique, [DATA] varbinary(MAX) not null, [OWNER_TYPE] nvarchar(255) not null, [TENANT_ID] bigint not null, primary key ([PID]));
create table [METADATA_ATTRIBUTE] ([PID] bigint identity not null unique, [ENUM_VALUES] nvarchar(2048), [DISPLAY_NAME] nvarchar(255) not null, [LENGTH] int, [LOGICAL_DATA_TYPE] nvarchar(255), [NAME] nvarchar(255) not null, [NULLABLE] bit not null, [DATA_TYPE] nvarchar(255) not null, [PRECISION] int, [PROPERTIES] varbinary(MAX) not null, [SCALE] int, [SOURCE_LOGICAL_DATA_TYPE] nvarchar(255), [TENANT_ID] bigint not null, [VALIDATORS] varbinary(MAX), FK_TABLE_ID bigint not null, primary key ([PID]));
create table [METADATA_EXTRACT] ([PID] bigint identity not null unique, [EXTRACTION_TS] bigint not null, [NAME] nvarchar(255) not null, [PATH] nvarchar(255) not null, [PROCESSED_RECORDS] bigint not null, [TENANT_ID] bigint not null, FK_TABLE_ID bigint not null, primary key ([PID]));
create table [METADATA_LASTMODIFIED_KEY] ([PID] bigint identity not null unique, [ATTRIBUTES] nvarchar(2048) not null, [DISPLAY_NAME] nvarchar(255) not null, [NAME] nvarchar(255) not null, [LAST_MODIFIED_TS] bigint not null, FK_TABLE_ID bigint not null, primary key ([PID]));
create table [METADATA_PRIMARY_KEY] ([PID] bigint identity not null unique, [ATTRIBUTES] nvarchar(2048) not null, [DISPLAY_NAME] nvarchar(255) not null, [NAME] nvarchar(255) not null, FK_TABLE_ID bigint not null, primary key ([PID]));
create table [METADATA_TABLE] ([PID] bigint identity not null unique, [DISPLAY_NAME] nvarchar(255) not null, [INTERPRETATION] nvarchar(255), [MARKED_FOR_PURGE] bit not null, [NAME] nvarchar(255) not null, [TYPE] int not null, [TENANT_ID] bigint not null, FK_TENANT_ID bigint not null, primary key ([PID]), unique ([TENANT_ID], [NAME], [TYPE]));
create table [MODELING_JOB] ([CHILD_JOB_IDS] nvarchar(255), [PARENT_PID] bigint, [JOB_PID] bigint not null, FK_MODEL_ID bigint, primary key ([JOB_PID]));
create table [MODEL_DEFINITION] ([PID] bigint identity not null unique, [NAME] nvarchar(255) not null, primary key ([PID]));
create table [MODEL_SUMMARY] ([PID] bigint identity not null unique, [APPLICATION_ID] nvarchar(255), [CONSTRUCTION_TIME] bigint not null, [DISPLAY_NAME] nvarchar(255), [DOWNLOADED] bit not null, [EVENT_TABLE_NAME] nvarchar(255), [ID] nvarchar(255) not null unique, [INCOMPLETE] bit not null, [LOOKUP_ID] nvarchar(255) not null, [NAME] nvarchar(255) not null, [ROC_SCORE] double precision not null, [SOURCE_SCHEMA_INTERPRETATION] nvarchar(255), [STATUS] int not null, [TENANT_ID] bigint not null, [TEST_CONVERSION_COUNT] bigint not null, [TEST_ROW_COUNT] bigint not null, [TOP_10_PCT_LIFT] double precision, [TOP_20_PCT_LIFT] double precision, [TOP_30_PCT_LIFT] double precision, [TOTAL_CONVERSION_COUNT] bigint not null, [TOTAL_ROW_COUNT] bigint not null, [TRAINING_CONVERSION_COUNT] bigint not null, [TRAINING_ROW_COUNT] bigint not null, [TRAINING_TABLE_NAME] nvarchar(255), [UPLOADED] bit not null, FK_KEY_VALUE_ID bigint not null, FK_TENANT_ID bigint not null, primary key ([PID]), unique ([ID]), unique ([NAME], [TENANT_ID]));
create table [MODEL] ([MODEL_PID] bigint identity not null unique, [CUSTOMER] nvarchar(255), [DATA_FORMAT] nvarchar(255), [DATA_HDFS_PATH] nvarchar(255), [DISPLAY_NAME] nvarchar(255), [FEATURES] nvarchar(MAX), [MODEL_ID] nvarchar(255), [KEYCOLS] nvarchar(500), [METADATA_HDFS_PATH] nvarchar(255), [METADATA_TABLE] nvarchar(255), [MODEL_HDFS_DIR] nvarchar(255), [NAME] nvarchar(255), [PROVENANCE_PROPERTIES] nvarchar(2048), [SCHEMA_HDFS_PATH] nvarchar(255), [TABLE_NAME] nvarchar(255), [TARGETS] nvarchar(255), FK_MODEL_DEF_ID bigint, primary key ([MODEL_PID]));
create table [OAUTH2_ACCESS_TOKEN] ([PID] bigint identity not null unique, [ACCESS_TOKEN] nvarchar(255) not null, [TENANT_ID] bigint not null, FK_TENANT_ID bigint not null, primary key ([PID]), unique ([TENANT_ID]));
create table [PREDICTOR_ELEMENT] ([PID] bigint identity not null unique, [CORRELATION_SIGN] int not null, [COUNT] bigint not null, [LIFT] double precision not null, [LOWER_INCLUSIVE] double precision, [NAME] nvarchar(255) not null, [TENANT_ID] bigint not null, [UNCERTAINTY_COEFF] double precision not null, [UPPER_EXCLUSIVE] double precision, [VALUES] nvarchar(MAX), [VISIBLE] bit not null, FK_PREDICTOR_ID bigint not null, primary key ([PID]));
create table [PREDICTOR] ([PID] bigint identity not null unique, [APPROVED_USAGE] nvarchar(255), [CATEGORY] nvarchar(255), [DISPLAY_NAME] nvarchar(255), [RF_FEATURE_IMPORTANCE] double precision, [FUNDAMENTAL_TYPE] nvarchar(255), [NAME] nvarchar(255) not null, [TENANT_ID] bigint not null, [UNCERTAINTY_COEFF] double precision, [USED_FOR_BI] bit not null, FK_MODELSUMMARY_ID bigint not null, primary key ([PID]));
create table [PROSPECT_DISCOVERY_OPTION] ([PID] bigint identity not null unique, [OPTION] nvarchar(255) not null, [TENANT_ID] bigint not null, [VALUE] nvarchar(255), primary key ([PID]));
create table [QUOTA] ([PID] bigint identity not null unique, [BALANCE] int not null, [ID] nvarchar(255) not null unique, [TENANT_ID] bigint not null, FK_TENANT_ID bigint not null, primary key ([PID]));
create table [REPORT] ([PID] bigint identity not null unique, [CREATED] datetime2 not null, [IS_OUT_OF_DATE] bit not null, [NAME] nvarchar(255) not null, [PURPOSE] nvarchar(255) not null, [TENANT_ID] bigint not null, [UPDATED] datetime2 not null, FK_KEY_VALUE_ID bigint not null, FK_TENANT_ID bigint not null, primary key ([PID]), unique ([NAME], [TENANT_ID]));
create table [SALESFORCE_URL] ([PID] bigint identity not null unique, [URL] nvarchar(255) not null, [NAME] nvarchar(255) not null unique, primary key ([PID]));
create table [SEGMENT] ([PID] bigint identity not null unique, [MODEL_ID] nvarchar(255), [NAME] nvarchar(255) not null, [PRIORITY] int not null, [TENANT_ID] bigint not null, FK_TENANT_ID bigint not null, primary key ([PID]), unique ([NAME], [TENANT_ID]));
create table [SOURCE_FILE] ([PID] bigint identity not null unique, [APPLICATION_ID] nvarchar(255), [CREATED] datetime2, [DESCRIPTION] nvarchar(255), [DISPLAY_NAME] nvarchar(255), [NAME] nvarchar(255) not null, [PATH] nvarchar(255) not null, [SCHEMA_INTERPRETATION] nvarchar(255), [STATE] nvarchar(255), [TABLE_NAME] nvarchar(255), [TENANT_ID] bigint not null, [UPDATED] datetime2, FK_TENANT_ID bigint not null, primary key ([PID]), unique ([NAME], [TENANT_ID]));
create table [TARGET_MARKET_DATA_FLOW_OPTION] ([PID] bigint identity not null unique, [OPTION] nvarchar(255) not null, [VALUE] nvarchar(255), TARGET_MARKET_ID bigint not null, primary key ([PID]));
create table [TARGET_MARKET_REPORT_MAP] ([PID] bigint identity not null unique, REPORT_ID bigint not null, TARGET_MARKET_ID bigint not null, primary key ([PID]));
create table [TARGET_MARKET] ([PID] bigint identity not null unique, [ACCOUNT_FILTER] nvarchar(255), [APPLICATION_ID] nvarchar(255), [CONTACT_FILTER] nvarchar(255), [CREATION_TIMESTAMP] bigint not null, [DESCRIPTION] nvarchar(255) not null, [EVENT_COLUMN_NAME] nvarchar(255), [IS_DEFAULT] bit, [MODEL_ID] nvarchar(255), [NAME] nvarchar(255) not null, [NUM_PROSPECTS_DESIRED] int, [OFFSET] int not null, [SELECTED_INTENT] nvarchar(255), [TENANT_ID] bigint not null, FK_TENANT_ID bigint not null, primary key ([PID]));
create table [TENANT_DEPLOYMENT] ([PID] bigint identity not null unique, [CREATE_TIME] datetime2 not null, [CREATED_BY] nvarchar(255) not null, [CURRENT_LAUNCH_ID] bigint, [MESSAGE] nvarchar(MAX), [MODEL_ID] nvarchar(255), [STATUS] int not null, [STEP] int not null, [TENANT_ID] bigint not null, primary key ([PID]));
create table [TENANT] ([TENANT_PID] bigint identity not null unique, [TENANT_ID] nvarchar(255) not null unique, [NAME] nvarchar(255) not null unique, [REGISTERED_TIME] bigint not null, [UI_VERSION] nvarchar(255) not null, primary key ([TENANT_PID]));
create table [THROTTLE_CONFIGURATION] ([PID] bigint identity not null unique, [ENABLED] bit not null, [IMMEDIATE] bit not null, [JOB_RANK_CUTOFF] int not null, [TIMESTAMP] datetime2 not null, primary key ([PID]));
create table [WORKFLOW_JOB] ([PID] bigint identity not null unique, [APPLICATION_ID] nvarchar(255), [ERROR_DETAILS] varchar(MAX), [INPUT_CONTEXT] nvarchar(4000), [START_TIME] bigint, [STATE] nvarchar(255), [TENANT_ID] bigint not null, [USER_ID] nvarchar(255), [WORKFLOW_ID] bigint, FK_TENANT_ID bigint not null, primary key ([PID]));
alter table [ALGORITHM] add constraint FKB388C44F5FB2DB1E foreign key (FK_MODEL_DEF_ID) references [MODEL_DEFINITION];
alter table [DATAFLOW_JOB] add constraint FK4E6B9EB6E88B2327 foreign key ([JOB_PID]) references [JOB];
alter table [EAI_JOB] add constraint FKB529FB8BE88B2327 foreign key ([JOB_PID]) references [JOB];
create index KEY_VALUE_TENANT_ID_IDX on [KEY_VALUE] ([TENANT_ID]);
alter table [METADATA_ATTRIBUTE] add constraint FKE2E7316C5FC50F27 foreign key (FK_TABLE_ID) references [METADATA_TABLE] on delete cascade;
alter table [METADATA_EXTRACT] add constraint FKCD56DB515FC50F27 foreign key (FK_TABLE_ID) references [METADATA_TABLE] on delete cascade;
alter table [METADATA_LASTMODIFIED_KEY] add constraint FK56B5EC6F5FC50F27 foreign key (FK_TABLE_ID) references [METADATA_TABLE] on delete cascade;
alter table [METADATA_PRIMARY_KEY] add constraint FKA4B6A5525FC50F27 foreign key (FK_TABLE_ID) references [METADATA_TABLE] on delete cascade;
alter table [METADATA_TABLE] add constraint FK4176B29E36865BC foreign key (FK_TENANT_ID) references [TENANT] on delete cascade;
alter table [MODELING_JOB] add constraint FK92A4EA77AC061AB1 foreign key (FK_MODEL_ID) references [MODEL];
alter table [MODELING_JOB] add constraint FK92A4EA77E88B2327 foreign key ([JOB_PID]) references [JOB];
create index MODEL_SUMMARY_ID_IDX on [MODEL_SUMMARY] ([ID]);
create index MODEL_SUMMARY_NAME_IDX on [MODEL_SUMMARY] ([NAME]);
alter table [MODEL_SUMMARY] add constraint FKCEB8C450AC2B0EB2 foreign key (FK_KEY_VALUE_ID) references [KEY_VALUE] on delete cascade;
alter table [MODEL_SUMMARY] add constraint FKCEB8C45036865BC foreign key (FK_TENANT_ID) references [TENANT] on delete cascade;
alter table [MODEL] add constraint FK46203095FB2DB1E foreign key (FK_MODEL_DEF_ID) references [MODEL_DEFINITION];
alter table [OAUTH2_ACCESS_TOKEN] add constraint FK5FB0F86236865BC foreign key (FK_TENANT_ID) references [TENANT] on delete cascade;
alter table [PREDICTOR_ELEMENT] add constraint FKC39535F9F9802A4B foreign key (FK_PREDICTOR_ID) references [PREDICTOR] on delete cascade;
alter table [PREDICTOR] add constraint FK55BF005C8807F0C9 foreign key (FK_MODELSUMMARY_ID) references [MODEL_SUMMARY] on delete cascade;
create index PROSPECT_DISCOVERY_OPTION_OPTION_IDX on [PROSPECT_DISCOVERY_OPTION] ([OPTION]);
create index PROSPECT_DISCOVERY_OPTION_TENANT_ID_IDX on [PROSPECT_DISCOVERY_OPTION] ([TENANT_ID]);
alter table [QUOTA] add constraint FK49D465836865BC foreign key (FK_TENANT_ID) references [TENANT] on delete cascade;
alter table [REPORT] add constraint FK8FDF4934AC2B0EB2 foreign key (FK_KEY_VALUE_ID) references [KEY_VALUE];
alter table [REPORT] add constraint FK8FDF493436865BC foreign key (FK_TENANT_ID) references [TENANT] on delete cascade;
alter table [SEGMENT] add constraint FKA0702B1336865BC foreign key (FK_TENANT_ID) references [TENANT] on delete cascade;
alter table [SOURCE_FILE] add constraint FK7D04A32036865BC foreign key (FK_TENANT_ID) references [TENANT] on delete cascade;
create index PROSPECT_DISCOVERY_OPTION_OPTION_IDX on [TARGET_MARKET_DATA_FLOW_OPTION] ([OPTION]);
alter table [TARGET_MARKET_DATA_FLOW_OPTION] add constraint FK18B26886AFC9B7C6 foreign key (TARGET_MARKET_ID) references [TARGET_MARKET] on delete cascade;
alter table [TARGET_MARKET_REPORT_MAP] add constraint FK16FEE466799FEF17 foreign key (REPORT_ID) references [REPORT];
alter table [TARGET_MARKET_REPORT_MAP] add constraint FK16FEE466AFC9B7C6 foreign key (TARGET_MARKET_ID) references [TARGET_MARKET];
alter table [TARGET_MARKET] add constraint FKDD9CEAAA36865BC foreign key (FK_TENANT_ID) references [TENANT];
alter table [WORKFLOW_JOB] add constraint FKE7361F1D36865BC foreign key (FK_TENANT_ID) references [TENANT] on delete cascade;
