alter table `LeadScoringCommandLog` drop foreign key FK73D5FC0CB951A41C;
alter table `LeadScoringCommandParameter` drop foreign key FK318F5671B951A41C;
alter table `LeadScoringCommandState` drop foreign key FKD6AC0B59B951A41C;
drop table if exists `LeadScoringCommandId`;
drop table if exists `LeadScoringCommandLog`;
drop table if exists `LeadScoringCommandParameter`;
drop table if exists `LeadScoringCommandState`;
drop table if exists `LeadScoringCommand`;
drop table if exists `LeadScoringResult`;
create table `LeadScoringCommandId` (`CommandId` bigint not null auto_increment unique, `CreateTime` datetime not null, `CreatedBy` varchar(255) not null, primary key (`CommandId`)) ENGINE=InnoDB;
create table `LeadScoringCommandLog` (`PID` bigint not null auto_increment unique, `Created` datetime not null, `Message` varchar(65535) not null, CommandId bigint not null, primary key (`PID`)) ENGINE=InnoDB;
create table `LeadScoringCommandParameter` (`Key` varchar(255) not null, `Value` varchar(65535), CommandId bigint not null, primary key (`Key`, CommandId)) ENGINE=InnoDB;
create table `LeadScoringCommandState` (`PID` bigint not null auto_increment unique, `Created` datetime not null, `Diagnostics` varchar(65535), `ElapsedTimeInMillis` bigint, `ModelCommandStep` varchar(255) not null, `Progress` float, `Status` varchar(255), `TrackingUrl` varchar(65535), `YarnApplicationId` varchar(255), CommandId bigint not null, primary key (`PID`)) ENGINE=InnoDB;
create table `LeadScoringCommand` (`CommandId` bigint not null, `CommandStatus` integer not null, `Contract_External_ID` varchar(255) not null, `Deployment_External_ID` varchar(255) not null, `LeadInputTableName` varchar(255) not null, `ModelCommandStep` varchar(255), `ModelId` varchar(255) not null, primary key (`CommandId`)) ENGINE=InnoDB;
create table `LeadScoringResult` (`CommandId` bigint not null unique, `BeginTime` datetime not null, `EndTime` datetime not null, `ProcessStatus` integer not null, primary key (`CommandId`)) ENGINE=InnoDB;
alter table `LeadScoringCommandLog` add index FK73D5FC0CB951A41C (CommandId), add constraint FK73D5FC0CB951A41C foreign key (CommandId) references `LeadScoringCommand` (`CommandId`);
alter table `LeadScoringCommandParameter` add index FK318F5671B951A41C (CommandId), add constraint FK318F5671B951A41C foreign key (CommandId) references `LeadScoringCommand` (`CommandId`);
alter table `LeadScoringCommandState` add index FKD6AC0B59B951A41C (CommandId), add constraint FKD6AC0B59B951A41C foreign key (CommandId) references `LeadScoringCommand` (`CommandId`);
