#!/bin/bash
rm -rf /opt/jetty2/webapps/le-propdata-*.war
rm -rf /etc/propdata/pls.properties
rm -rf /opt/jetty2/bin/jetty.sh
adduser yarn
groupadd yarn
mkdir -p /var/log/propdata
mkdir -p /home/yarn/logs
chmod -R 755 /var/log/propdata
chmod -R 755 /home/yarn/logs
chown -R yarn:yarn /var/log/propdata
chown -R yarn:yarn /home/yarn/logs
chown -R yarn:yarn /opt/jetty2/logs