#!/bin/bash -x
source /etc/profile
echo "getting environment information"
echo $LE_ENVIRONMENT
echo $LE_STACK

echo "copying files from temporary folders"
cp /tmp/ledp/conf/$LE_ENVIRONMENT/*.properties /etc/ledp/
chmod 755 /etc/ledp/*

echo "cleaning up"
rm -rf /tmp/ledp

echo "finishing"
ll /etc/ledp/
