#!/bin/bash -x
source /etc/profile
echo "getting environment information"
echo $LE_ENVIRONMENT
echo $LE_STACK
echo $STACK_PROFILE

echo "replace tokens"
cd /tmp/ledp
cat ${STACK_PROFILE}
python replace_token.py /tmp/ledp/${LE_ENVIRONMENT} ${STACK_PROFILE}

echo "copying files from temporary folders"
mkdir -p /etc/ledp
cp /tmp/ledp/${LE_ENVIRONMENT}/latticeengines.properties /etc/ledp/
chmod 755 /etc/ledp/latticeengines.properties

echo "cleaning up"
rm -rf /tmp/ledp

echo "finishing"
ll /etc/ledp/
