package com.latticeengines.cdl.workflow.steps.merge;

import static com.latticeengines.domain.exposed.metadata.InterfaceName.CDLCreatedTemplate;
import static com.latticeengines.domain.exposed.metadata.InterfaceName.LatticeAccountId;
import static com.latticeengines.domain.exposed.metadata.TableRoleInCollection.ConsolidateWebVisit;
import static com.latticeengines.domain.exposed.query.BusinessEntity.Account;
import static com.latticeengines.domain.exposed.query.BusinessEntity.LatticeAccount;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import java.util.stream.Collectors;

import org.apache.commons.collections4.CollectionUtils;
import org.apache.commons.collections4.MapUtils;
import org.apache.commons.collections4.SetUtils;
import org.apache.commons.lang3.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.config.ConfigurableBeanFactory;
import org.springframework.context.annotation.Lazy;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.Preconditions;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableSet;
import com.latticeengines.common.exposed.util.JsonUtils;
import com.latticeengines.common.exposed.validator.annotation.NotNull;
import com.latticeengines.domain.exposed.camille.CustomerSpace;
import com.latticeengines.domain.exposed.cdl.activity.ActivityImport;
import com.latticeengines.domain.exposed.cdl.activity.AtlasStream;
import com.latticeengines.domain.exposed.datacloud.manage.Column;
import com.latticeengines.domain.exposed.datacloud.match.MatchInput;
import com.latticeengines.domain.exposed.datacloud.match.MatchKey;
import com.latticeengines.domain.exposed.datacloud.match.OperationalMode;
import com.latticeengines.domain.exposed.datacloud.transformation.PipelineTransformationRequest;
import com.latticeengines.domain.exposed.datacloud.transformation.config.impl.MatchTransformerConfig;
import com.latticeengines.domain.exposed.datacloud.transformation.step.TransformationStepConfig;
import com.latticeengines.domain.exposed.metadata.InterfaceName;
import com.latticeengines.domain.exposed.propdata.manage.ColumnSelection;
import com.latticeengines.domain.exposed.security.Tenant;
import com.latticeengines.domain.exposed.serviceflows.cdl.steps.process.ProcessActivityStreamStepConfiguration;
import com.latticeengines.domain.exposed.util.TableUtils;

@Component(MergeWebVisit.BEAN_NAME)
@Lazy
@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
public class MergeWebVisit extends BaseActivityStreamStep<ProcessActivityStreamStepConfiguration> {

    /**
     * this step used when tenant enable SSVI flag, disable CDL flag.
     * if enable CDL flag, will skip this step.
     */

    static final String BEAN_NAME = "mergeWebVisit";

    private static final Logger log = LoggerFactory.getLogger(MergeWebVisit.class);

    // matched table of merged imports
    private static final String WEBVISIT_MATCHED_PREFIX_FORMAT = "Matched_WebVisit_%s";
    // matched table merged with existing batch store, used as input of rematch step
    private static final String WEBVISIT_PRE_REMATCH_TABLE_PREFIX_FORMAT = "PreReMatch_WebVisit_%s";
    // rematched table of merged imports + active batch store
    private static final String WEBVISIT_REMATCHED_TABLE_PREFIX_FORMAT = "ReMatched_WebVisit_%s";

    private static final Set<String> DISCARD_ATTRS_IN_REMATCH = ImmutableSet.of(LatticeAccountId.name(),
            CDLCreatedTemplate.name()); // attrs generated by match and should be removed before rematch

    private static final List<String> WEBVISIT_LDC_ATTRIBUTES = ImmutableList.of("LE_GlobalUlt_salesUSD",
            "LE_DomUlt_SalesUSD", "LE_GlobalULt_EmployeeTotal", "LE_DomUlt_EmployeeTotal", "LDC_DUNS", "DOMESTIC_ULTIMATE_DUNS_NUMBER",
            "GLOBAL_ULTIMATE_DUNS_NUMBER", "LE_SIC_CODE", "LE_Site_NAICS_Code", "LE_INDUSTRY", "LE_EMPLOYEE_RANGE",
            "LE_REVENUE_RANGE", "LE_IS_PRIMARY_DOMAIN", "LDC_Domain", "LDC_Name", "LDC_Country", "LDC_State",
            "LDC_City", "LE_DNB_TYPE");

    //set of column names
    private Set<String> webVisitImportColumnNames;
    private AtlasStream webVisitStream;
    //tableName, original import file name
    @JsonProperty("stream_imports")
    private List<ActivityImport> webVisitImports;
    //table prefix of matched webVisit raw streams imports processed by
    // transformation request
    private String matchedTablePrefix;
    private String webVisitBatchStoreTable;
    private long currentTime;

    @Override
    protected void initializeConfiguration() {
        super.initializeConfiguration();
        currentTime = getCurrentTimestamp();
        log.info("Timestamp used as current time to build raw stream = {}", currentTime);
        log.info("IsRematch={}, isReplace={}", configuration.isRematchMode(), configuration.isReplaceMode());
        getWebVisitStream();
        buildWebVisitImportColumnNames();
    }

    @Override
    protected PipelineTransformationRequest getConsolidateRequest() {
        if (Boolean.FALSE.equals(getObjectFromContext(IS_SSVI_TENANT, Boolean.class))) {
            return null;
        }
        if (Boolean.TRUE.equals(getObjectFromContext(IS_CDL_TENANT, Boolean.class))) {
            log.info("This is CDL Tenant, skip this step.");
            return null;
        }

        if (CollectionUtils.isEmpty(webVisitImports) || webVisitStream == null) {
            log.info("no import or atlasStream is null, will skip this step.");
            return null;
        }

        PipelineTransformationRequest request = new PipelineTransformationRequest();
        request.setName(BEAN_NAME);

        List<TransformationStepConfig> steps = new ArrayList<>();

        /*-
         * normal steps:
         * 1. merge imports
         * 2. match against current universe
         */
        List<String> importTables = webVisitImports.stream() //
                .map(ActivityImport::getTableName) //
                .collect(Collectors.toList());
        if (CollectionUtils.isEmpty(importTables)) {
            return null;
        }
        Integer matchedStepIdx = concatAndMatchStreamImports(webVisitStream.getStreamId(), importTables, steps);

        /*-
         * additional rematch steps:
         * 1. merge matched imports with batch store (if exist) and treat as a huge import
         * 2. rematch against empty universe
         */
        if (configuration.isRematchMode()) {
            log.info("Adding rematch steps, matchedStepIdx = {}", matchedStepIdx);
            webVisitBatchStoreTable = dataCollectionProxy.getTableName(configuration.getCustomerSpace().toString(),
                    ConsolidateWebVisit, null);
            putObjectInContext(SSVI_WEBVISIT_RAW_TABLE, webVisitBatchStoreTable);
            appendRawStream(steps, webVisitStream, currentTime, matchedStepIdx, webVisitBatchStoreTable,
                    WEBVISIT_PRE_REMATCH_TABLE_PREFIX_FORMAT, DISCARD_ATTRS_IN_REMATCH).ifPresent(pair -> {
                int appendStepIdx = pair.getValue();
                // input table columns = [ import columns ] union [ active batch store columns ]
                Set<String> columns = new HashSet<>(webVisitImportColumnNames);
                if (webVisitBatchStoreTable != null) {
                    columns.addAll(getTableColumnNames(webVisitBatchStoreTable));
                }
                addMatchStep(webVisitStream, columns, steps, appendStepIdx, true);
            });
        }

        if (CollectionUtils.isEmpty(steps)) {
            log.info("No existing/new webvisit found, skip MergeWebVisit step");
            return null;
        }

        request.setSteps(steps);
        return request;
    }

    @Override
    protected void onPostTransformationCompleted() {
        String matchedTableName = getFullTableName(matchedTablePrefix);
        log.info("Matched webVisit tables, tables={}, pipelineVersion={}", matchedTableName, pipelineVersion);
        putObjectInContext(SSVI_MATCH_STREAM_TARGETTABLE, matchedTableName);
    }

    private void getWebVisitStream() {
        if (MapUtils.isEmpty(configuration.getActivityStreamMap())) {
            return;
        }
        configuration.getActivityStreamMap().forEach((streamId, stream) -> {
            if (AtlasStream.StreamType.WebVisit.equals(stream.getStreamType())) {
                webVisitStream = stream;
                if (configuration.getStreamImports().get(streamId) != null) {
                    webVisitImports = configuration.getStreamImports().get(streamId);
                }
            }
        });
    }

    private Integer concatAndMatchStreamImports(@NotNull String streamId, @NotNull List<String> importTables,
                                                @NotNull List<TransformationStepConfig> steps) {
        Preconditions.checkNotNull(webVisitStream, String.format("Stream %s is not in config", webVisitStream));
        Preconditions.checkArgument(CollectionUtils.isNotEmpty(webVisitStream.getMatchEntities()),
                String.format("Stream %s does not have match entities", streamId));

        // concat import
        steps.add(dedupAndConcatTables(null, false, importTables));
        addMatchStep(webVisitStream, webVisitImportColumnNames, steps, steps.size() - 1, false);
        return steps.size() - 1;
    }

    private void addMatchStep(@NotNull AtlasStream stream, @NotNull Set<String> importTableColumns,
                              @NotNull List<TransformationStepConfig> steps, int matchInputTableIdx, boolean isRematchMode) {
        String tablePrefixFormat = isRematchMode ? WEBVISIT_REMATCHED_TABLE_PREFIX_FORMAT
                : WEBVISIT_MATCHED_PREFIX_FORMAT;
        // record the final table prefix for webVisit stream
        matchedTablePrefix = String.format(tablePrefixFormat, stream.getStreamId());
        String matchConfig;
        MatchInput baseMatchInput = getBaseMatchInput();
        // set stream type to source entity to get higher concurrency
        baseMatchInput.setSourceEntity(stream.getStreamType().name());
        if (configuration.getEntityMatchConfiguration() != null) {
            log.info("found custom entity match configuration = {}", configuration.getEntityMatchConfiguration());
            baseMatchInput.setEntityMatchConfiguration(configuration.getEntityMatchConfiguration());
        }
        // streamId -> root operation uid used for bulk match
        String matchRootOperationUid = UUID.randomUUID().toString();
        // match entity
        matchConfig = getAllocateIdMatchConfigForAccount(customerSpace.toString(), baseMatchInput,
                importTableColumns, matchRootOperationUid);
        steps.add(match(matchInputTableIdx, matchedTablePrefix, matchConfig));
    }

    private String getAllocateIdMatchConfigForAccount(String customer, MatchInput baseMatchInput,
                                                            Set<String> columnNames, String rootOperationUid) {
        MatchTransformerConfig config = new MatchTransformerConfig();
        baseMatchInput.setOperationalMode(OperationalMode.CDL_LOOKUP);
        baseMatchInput.setTargetEntity(LatticeAccount.name());
        baseMatchInput.setAllocateId(true);
        baseMatchInput.setOutputNewEntities(false);

        if (StringUtils.isNotBlank(rootOperationUid)) {
            config.setRootOperationUid(rootOperationUid);
        }
        baseMatchInput.setIncludeLineageFields(true);
        baseMatchInput.setCustomSelection(setCustomFieldSelection());
        baseMatchInput.setTenant(new Tenant(CustomerSpace.parse(customer).toString()));
        baseMatchInput.setKeyMap(getAccountMatchKeys(columnNames, MatchUtils.getSkippedMatchFields(baseMatchInput,
                Account.name())));
        baseMatchInput.setUseDnBCache(true);
        baseMatchInput.setUseRemoteDnB(true);

        config.setMatchInput(baseMatchInput);
        return JsonUtils.serialize(config);
    }

    private ColumnSelection setCustomFieldSelection() {
        List<Column> customFields =
                WEBVISIT_LDC_ATTRIBUTES.stream().map( col -> new Column(col, col)).collect(Collectors.toList());
        ColumnSelection customFieldSelection = new ColumnSelection();
        customFieldSelection.setColumns(customFields);
        return customFieldSelection;
    }

    private static Map<MatchKey, List<String>> getAccountMatchKeys(Set<String> columnNames, Set<String> fieldsToSkip) {

        Set<String> skippedFields = SetUtils.emptyIfNull(fieldsToSkip);
        log.info("Account match fields to skip from input {}, fields actually skipped {}", skippedFields,
                SetUtils.intersection(columnNames, skippedFields));
        columnNames = SetUtils.difference(columnNames, skippedFields);

        Map<MatchKey, List<String>> matchKeys = new HashMap<>();
        MatchUtils.addMatchKeyIfExists(columnNames, matchKeys, MatchKey.Domain, InterfaceName.Website.name());
        MatchUtils.addMatchKeyIfExists(columnNames, matchKeys, MatchKey.DUNS, InterfaceName.DUNS.name());
        MatchUtils.addMatchKeyIfExists(columnNames, matchKeys, MatchKey.Name, InterfaceName.CompanyName.name());
        MatchUtils.addMatchKeyIfExists(columnNames, matchKeys, MatchKey.City, InterfaceName.City.name());
        MatchUtils.addMatchKeyIfExists(columnNames, matchKeys, MatchKey.State, InterfaceName.State.name());
        MatchUtils.addMatchKeyIfExists(columnNames, matchKeys, MatchKey.Country, InterfaceName.Country.name());
        MatchUtils.addMatchKeyIfExists(columnNames, matchKeys, MatchKey.PhoneNumber, InterfaceName.PhoneNumber.name());
        MatchUtils.addMatchKeyIfExists(columnNames, matchKeys, MatchKey.Zipcode, InterfaceName.PostalCode.name());
        log.info("Account match keys = {}", JsonUtils.serialize(matchKeys));
        return matchKeys;
    }

    private void buildWebVisitImportColumnNames() {
        if (CollectionUtils.isEmpty(webVisitImports)) {
            return;
        }

        String[] importTables = webVisitImports.stream().map(ActivityImport::getTableName).toArray(String[]::new);
        Set<String> columns = getTableColumnNames(importTables);
        log.info("WebVisit has {} imports, {} total columns", webVisitImports.size(), columns.size());
        webVisitImportColumnNames.addAll(columns);
    }

    private String getFullTableName(String tablePrefix) {
        if (StringUtils.isEmpty(tablePrefix)) {
            return "";
        }
        return TableUtils.getFullTableName(tablePrefix, pipelineVersion);
    }
}
