#!/bin/bash
chmod 755 /tmp/app/scoring/scripts
rm /tmp/app/scoring/scripts/*.pyc
rm /tmp/app/scoring/scripts/*.pyo

su -l yarn -c 'hadoop dfs -mkdir /app/scoring'
su -l yarn -c 'hadoop dfs -copyFromLocal /tmp/app/scoring /app/scoring'
rm -rf /tmp/app/scoring