#!/bin/bash

echo "getting environment information"
echo $LE_ENVIRONMENT
echo $LE_STACK
echo $STACK_PROFILE
echo $USE_AWS

if [ "${USE_AWS}" = "true"  ]; then
    LE_STACK="${LE_STACK}_aws"
fi
echo $LE_STACK

JARFILE=`ls /tmp/app/scoring/lib/le-scoring*-shaded.jar`
VERSION=`echo $JARFILE | cut -d \- -f 3`
SNAPSHOT=`echo $JARFILE | cut -d \- -f 4`

if test $SNAPSHOT = "SNAPSHOT"
    then
        VERSION=$VERSION-"SNAPSHOT"
fi

if [ ! -z "$LE_STACK" -a "$LE_STACK" != " " ]; then
    VERSION=${LE_STACK}/${VERSION}
fi

chmod 755 -R /tmp/app/scoring
rm /tmp/app/scoring/scripts/*.pyc
rm /tmp/app/scoring/scripts/*.pyo

su -l yarn -c "hadoop dfs -mkdir -p /app/$VERSION" || true
su -l yarn -c "hadoop dfs -copyFromLocal /tmp/app/scoring /app/$VERSION"
rm -rf /tmp/app/scoring