#!/bin/bash

RPMFILE=`ls /tmp/le-scoring-hdfs-*.rpm`
VERSION=`echo $RPMFILE | cut -d \- -f 4`
SNAPSHOT=`echo $RPMFILE | cut -d \- -f 5`

if [[ $SNAPSHOT = SNAPSHOT* ]]
    then
        VERSION=$VERSION-"SNAPSHOT"
fi

rm -rf /tmp/app/scoring
hdfs dfs -rm -f -r /app/$VERSION/scoring || true