package com.latticeengines.domain.exposed.scoringapi;

public enum FieldSource {
    // Provided along with the scoring request.
    REQUEST,

    // Available through the internal Prop Data system.
    PROPRIETARY,

    // Generated by transforms.
    TRANSFORMS,

    // Extracted from customer systems through a secondary process.
    CUSTOMER
}
