#!/bin/bash
echo 'Running Postinstall'

echo "getting environment information"
echo $LE_ENVIRONMENT
echo $LE_STACK
echo $STACK_PROFILE
echo $USE_AWS

if [ "${USE_AWS}" = "true"  ]; then
    LE_STACK="${LE_STACK}_aws"
fi
echo $LE_STACK

JARFILE=`ls /tmp/app/dellebi/le-dellebi*-shaded.jar`
VERSION=`echo $JARFILE | cut -d \- -f 3`
SNAPSHOT=`echo $JARFILE | cut -d \- -f 4`

if test $SNAPSHOT = "SNAPSHOT"
    then
        VERSION=$VERSION-"SNAPSHOT"
fi

if [ ! -z "$LE_STACK" -a "$LE_STACK" != " " ]; then
    VERSION=${LE_STACK}/${VERSION}
fi

echo $VERSION

hdfs dfs -rm -r -f /app/$VERSION/dellebi/lib/*
hdfs dfs -put /tmp/app/dellebi/le-dellebi*-shaded.jar /app/$VERSION/dellebi/lib
hdfs dfs -copyFromLocal /tmp/app/dellebi/dellebi.properties /app/$VERSION/dellebi
rm -rf /tmp/app/dellebi/
