#!/bin/bash
echo 'check env var STACK_NAME'
echo $STACK_NAME

echo 'Running Preinstall'

RPMFILE=`ls /tmp/le-dellebi-hdfs-*.rpm`
VERSION=`echo $RPMFILE | cut -d \- -f 5`
SNAPSHOT=`echo $RPMFILE | cut -d \- -f 6`

if [[ $SNAPSHOT = SNAPSHOT* ]]
    then
        VERSION=$VERSION-"SNAPSHOT"
fi

if [ ! -z "$STACK_NAME" -a "$STACK_NAME" != " " ]; then
    VERSION=${STACK_NAME}/${VERSION}
fi

echo $VERSION

if [ -d "/tmp/app/dellebi" ]; then
    rm -rf /tmp/app/dellebi/le-dellebi*-shaded.jar
else
    mkdir -p /tmp/app/dellebi
fi
hdfs dfs -mkdir -p /app/$VERSION/dellebi/lib || true
hdfs dfs -rm -f /app/$VERSION/dellebi/lib/le-dellebi*-shaded.jar || true
hdfs dfs -rm -f /app/$VERSION/dellebi/dellebi.properties || true

