#
# $LastChangedBy: mwilson $
# $LastChangedDate: 2015-11-13 14:56:48 +0800 (Fri, 13 Nov 2015) $
# $Rev: 70934 $
#

from lxml import etree
from appsequence import Applicability, StepBase
import appsequence
import liaison


class LP_020400_LG_Update_Services(StepBase):
  name = 'LP_020400_LG_MissingLeadReport'
  description = 'LP_020400_LG_Update_Services'
  version = '$Rev: 70934 $'

  def __init__(self, forceApply=False):
    super(LP_020400_LG_Update_Services, self).__init__(forceApply)

  def getApplicability(self, appseq):

    lgm = appseq.getLoadGroupMgr()
    conn_mgr = appseq.getConnectionMgr()

    if lgm.hasLoadGroup('LoadCRMData_Extended') and lgm.hasLoadGroup('Download_ExtendedDataset') and lgm.hasLoadGroup('Download_ExtendedDataset') and lgm.hasLoadGroup('Update_LatestScoredLeadsToVisiDB'):
      return Applicability.alreadyAppliedPass
    return Applicability.canApply

  def apply(self, appseq):

    success = False
    lgm = appseq.getLoadGroupMgr()
    type = appseq.getText( 'template_type' )
    customerId = appseq.getText('customer_id')

#Create Load Group 'Download_ExtendedDataset'
    #Create LoadCRMData_Extended
    lgm.createLoadGroup('LoadCRMData_Extended', 'BulkScoring\Standard',  'LoadCRMData_Extended', True, True)
    lce_xml = ''
    lce_xml= etree.fromstring(lgm.getLoadGroup('LoadCRMData_Extended').encode('ascii', 'xmlcharrefreplace'))
    if type == 'MKTO':
      lce_xml = '''
    <group name="LoadCRMData_Extended" alias="LoadCRMData_Extended" w="Workspace" type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000" launchExpiredDays="7" createdBy="YTian@Lattice-Engines.com" path="BulkScoring\Standard" autoGenerated="False" validationValidMinutes="120" autoClearOnFailure="False" mergeRulesSaved="True" ng="False">
      <schemas/>
      <visiDBConfigurationWithMacros/>
      <targetQueries/>
      <targetQuerySequences/>
      <gvqs/>
      <rdss>
        <rds n="SFDC_Lead" w="Workspace" sn="SFDC_Lead" cn="SFDC_DataProvider" u="False" ss="" tn="Lead" nmo="1" f="@datediff(#ExtendedDataset_UpperLimitTime, month(6))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="False" eo="1" emd="True" eo_sftp="1">
          <ts>
            <t n="ExtendedDataset_LowerLimitTime" t="1" qn="Q_Services_ExtractLeadsRange" cn="ExtendedDataset_LowerLimitTime" m="0">
              <schemas/>
              <specs/>
            </t>
          </ts>
          <mcs>
            <mc cn="Id"/>
          </mcs>
        </rds>
        <rds n="SFDC_Opportunity" w="Workspace" sn="SFDC_Opportunity" cn="SFDC_DataProvider" u="False" ss="" tn="Opportunity" nmo="1" f="@datediff(#ExtendedDataset_UpperLimitTime, month(6))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="False" eo="1" emd="True" eo_sftp="1">
          <ts>
            <t n="ExtendedDataset_UpperLimitTime" t="1" qn="Q_Services_ExtractLeadsRange" cn="ExtendedDataset_UpperLimitTime" m="0">
              <schemas/>
              <specs/>
            </t>
          </ts>
          <mcs>
            <mc cn="Id"/>
          </mcs>
        </rds>
        <rds n="SFDC_User" w="Workspace" sn="SFDC_User" cn="SFDC_DataProvider" u="False" ss="" tn="User" nmo="1" f="@datediff(#ExtendedDataset_UpperLimitTime, month(6))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="False" eo="1" emd="False" eo_sftp="1">
          <ts>
            <t n="ExtendedDataset_UpperLimitTime" t="1" qn="Q_Services_ExtractLeadsRange" cn="ExtendedDataset_UpperLimitTime" m="0">
              <schemas/>
              <specs/>
            </t>
          </ts>
          <mcs>
            <mc cn="Id"/>
          </mcs>
        </rds>
        <rds n="SFDC_Contact" w="Workspace" sn="SFDC_Contact" cn="SFDC_DataProvider" u="False" ss="" tn="Contact" nmo="1" f="@datediff(#ExtendedDataset_UpperLimitTime, month(6))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="False" eo="1" emd="True" eo_sftp="1">
          <ts>
            <t n="ExtendedDataset_UpperLimitTime" t="1" qn="Q_Services_ExtractLeadsRange" cn="ExtendedDataset_UpperLimitTime" m="0">
              <schemas/>
              <specs/>
            </t>
          </ts>
          <mcs>
            <mc cn="Id"/>
          </mcs>
        </rds>
        <rds n="SFDC_OpportunityContactRole" w="Workspace" sn="SFDC_OpportunityContactRole" cn="SFDC_DataProvider" u="False" ss="" tn="OpportunityContactRole" nmo="1" f="@datediff(#ExtendedDataset_UpperLimitTime, month(6))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="False" eo="1" emd="True" eo_sftp="1">
          <ts>
            <t n="ExtendedDataset_UpperLimitTime" t="1" qn="Q_Services_ExtractLeadsRange" cn="ExtendedDataset_UpperLimitTime" m="0">
              <schemas/>
              <specs/>
            </t>
          </ts>
          <mcs>
            <mc cn="ContactId"/>
            <mc cn="CreatedById"/>
            <mc cn="CreatedDate"/>
            <mc cn="Id"/>
            <mc cn="IsDeleted"/>
            <mc cn="IsPrimary"/>
            <mc cn="LastModifiedById"/>
            <mc cn="LastModifiedDate"/>
            <mc cn="OpportunityId"/>
            <mc cn="Role"/>
            <mc cn="SystemModstamp"/>
          </mcs>
        </rds>
      </rdss>
      <validationExtracts/>
      <ces/>
      <extractQueries>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_DownloadedSFDC_Leads" queryAlias="Q_Timestamp_DownloadedSFDC_Leads" sw="Workspace" schemaName="Timestamp_DownloadedSFDC_Leads" at="False" ucm="True">
          <schemas/>
          <specs/>
          <cms>
            <cm qcn="SFDC_Lead_ID" itcn="SFDC_Lead_ID"/>
            <cm qcn="Time_OfComepletion_DownloadedSFDC_Leads" itcn="Time_OfComepletion_DownloadedSFDC_Leads"/>
          </cms>
        </extractQuery>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_DownloadedSFDC_Contacts" queryAlias="Q_Timestamp_DownloadedSFDC_Contacts" sw="Workspace" schemaName="Timestamp_DownloadedSFDC_Contacts" at="False" ucm="True">
          <schemas/>
          <specs/>
          <cms>
            <cm qcn="SFDC_Contact_ID" itcn="SFDC_Contact_ID"/>
            <cm qcn="Time_OfComepletion_DownloadedSFDC_Contacts" itcn="Time_OfComepletion_DownloadedSFDC_Contacts"/>
          </cms>
        </extractQuery>
      </extractQueries>
      <extractQuerySequences/>
      <leafExtracts/>
      <launchExtracts/>
      <jobs/>
      <pdmatches/>
      <leadscroings/>
      <lssbardins/>
      <lssbardouts/>
      <lds/>
      <ecs/>
      <gCs/>
    </group>'''
    elif type =='ELQ':
      lce_xml = '''
    <group name="LoadCRMData_Extended" alias="LoadCRMData_Extended" w="Workspace" type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000" launchExpiredDays="7" createdBy="YTian@Lattice-Engines.com" path="BulkScoring\Standard" autoGenerated="False" validationValidMinutes="120" autoClearOnFailure="False" mergeRulesSaved="True" ng="False">
      <schemas/>
      <visiDBConfigurationWithMacros/>
      <targetQueries/>
      <targetQuerySequences/>
      <gvqs/>
      <rdss>
        <rds n="SFDC_Lead" w="Workspace" sn="SFDC_Lead" cn="SFDC_DataProvider" u="False" ss="" tn="Lead" nmo="1" f="@datediff(#ExtendedDataset_UpperLimitTime, month(6))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="False" eo="1" emd="True" eo_sftp="1">
          <ts>
            <t n="ExtendedDataset_UpperLimitTime" t="1" qn="Q_Services_ExtractLeadsRange" cn="ExtendedDataset_UpperLimitTime" m="0">
              <schemas/>
              <specs/>
            </t>
          </ts>
          <mcs>
            <mc cn="Id"/>
          </mcs>
        </rds>
        <rds n="SFDC_Opportunity" w="Workspace" sn="SFDC_Opportunity" cn="SFDC_DataProvider" u="False" ss="" tn="Opportunity" nmo="1" f="@datediff(#ExtendedDataset_UpperLimitTime, month(6))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="False" eo="1" emd="True" eo_sftp="1">
          <ts>
            <t n="ExtendedDataset_UpperLimitTime" t="1" qn="Q_Services_ExtractLeadsRange" cn="ExtendedDataset_UpperLimitTime" m="0">
              <schemas/>
              <specs/>
            </t>
          </ts>
          <mcs>
            <mc cn="Id"/>
          </mcs>
        </rds>
        <rds n="SFDC_User" w="Workspace" sn="SFDC_User" cn="SFDC_DataProvider" u="False" ss="" tn="User" nmo="1" f="@datediff(#ExtendedDataset_UpperLimitTime, month(6))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="False" eo="1" emd="False" eo_sftp="1">
          <ts>
            <t n="ExtendedDataset_UpperLimitTime" t="1" qn="Q_Services_ExtractLeadsRange" cn="ExtendedDataset_UpperLimitTime" m="0">
              <schemas/>
              <specs/>
            </t>
          </ts>
          <mcs>
            <mc cn="Id"/>
          </mcs>
        </rds>
        <rds n="SFDC_Contact" w="Workspace" sn="SFDC_Contact" cn="SFDC_DataProvider" u="False" ss="" tn="Contact" nmo="1" f="@datediff(#ExtendedDataset_UpperLimitTime, month(6))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="False" eo="1" emd="True" eo_sftp="1">
          <ts>
            <t n="ExtendedDataset_UpperLimitTime" t="1" qn="Q_Services_ExtractLeadsRange" cn="ExtendedDataset_UpperLimitTime" m="0">
              <schemas/>
              <specs/>
            </t>
          </ts>
          <mcs>
            <mc cn="Id"/>
          </mcs>
        </rds>
        <rds n="SFDC_OpportunityContactRole" w="Workspace" sn="SFDC_OpportunityContactRole" cn="SFDC_DataProvider" u="False" ss="" tn="OpportunityContactRole" nmo="1" f="@datediff(#ExtendedDataset_UpperLimitTime, month(6))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="False" eo="1" emd="True" eo_sftp="1">
          <ts>
            <t n="ExtendedDataset_UpperLimitTime" t="1" qn="Q_Services_ExtractLeadsRange" cn="ExtendedDataset_UpperLimitTime" m="0">
              <schemas/>
              <specs/>
            </t>
          </ts>
        </rds>
      </rdss>
      <validationExtracts/>
      <ces/>
      <extractQueries>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_DownloadedSFDC_Leads" queryAlias="Q_Timestamp_DownloadedSFDC_Leads" sw="Workspace" schemaName="Timestamp_DownloadedSFDC_Leads" at="False" ucm="True">
          <schemas/>
          <specs/>
          <cms>
            <cm qcn="SFDC_Lead_ID" itcn="SFDC_Lead_ID"/>
            <cm qcn="Time_OfComepletion_DownloadedSFDC_Leads" itcn="Time_OfComepletion_DownloadedSFDC_Leads"/>
          </cms>
        </extractQuery>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_DownloadedSFDC_Contacts" queryAlias="Q_Timestamp_DownloadedSFDC_Contacts" sw="Workspace" schemaName="Timestamp_DownloadedSFDC_Contacts" at="False" ucm="True">
          <schemas/>
          <specs/>
          <cms>
            <cm qcn="SFDC_Contact_ID" itcn="SFDC_Contact_ID"/>
            <cm qcn="Time_OfComepletion_DownloadedSFDC_Contacts" itcn="Time_OfComepletion_DownloadedSFDC_Contacts"/>
          </cms>
        </extractQuery>
      </extractQueries>
      <extractQuerySequences/>
      <leafExtracts/>
      <launchExtracts/>
      <jobs/>
      <pdmatches/>
      <leadscroings/>
      <lssbardins/>
      <lssbardouts/>
      <lds/>
      <ecs/>
      <gCs/>
    </group>'''
    else:
      lce_xml = '''
    <group name="LoadCRMData_Extended" alias="LoadCRMData_Extended" w="Workspace" type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000" launchExpiredDays="7" createdBy="YTian@Lattice-Engines.com" path="BulkScoring\Standard" autoGenerated="False" validationValidMinutes="120" autoClearOnFailure="False" mergeRulesSaved="True" ng="False">
      <schemas/>
      <visiDBConfigurationWithMacros/>
      <targetQueries/>
      <targetQuerySequences/>
      <gvqs/>
      <rdss>
        <rds n="SFDC_Contact" w="Workspace" sn="SFDC_Contact" cn="SFDC_DataProvider" u="False" ss="" tn="Contact" nmo="1" f="@datediff(#ExtendedDataset_UpperLimitTime, month(6))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="True" eo_sftp="2">
          <ts>
            <t n="ExtendedDataset_UpperLimitTime" t="1" qn="Q_Services_ExtractLeadsRange" cn="ExtendedDataset_UpperLimitTime" m="0">
              <schemas/>
              <specs/>
            </t>
          </ts>
          <mcs>
            <mc cn="Id"/>
            <mc cn="LastModifiedDate"/>
          </mcs>
        </rds>
        <rds n="SFDC_Lead" w="Workspace" sn="SFDC_Lead" cn="SFDC_DataProvider" u="False" ss="" tn="Lead" nmo="1" f="@datediff(#ExtendedDataset_UpperLimitTime, month(6))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="False" eo_sftp="2">
          <ts>
            <t n="ExtendedDataset_UpperLimitTime" t="1" qn="Q_Services_ExtractLeadsRange" cn="ExtendedDataset_UpperLimitTime" m="0">
              <schemas/>
              <specs/>
            </t>
          </ts>
          <mcs>
            <mc cn="Id"/>
            <mc cn="LastModifiedDate"/>
          </mcs>
        </rds>
        <rds n="SFDC_Account" w="Workspace" sn="SFDC_Account" cn="SFDC_DataProvider" u="False" ss="" tn="Account" nmo="1" f="@datediff(#ExtendedDataset_UpperLimitTime, month(6))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="True" eo_sftp="2">
          <ts>
            <t n="ExtendedDataset_UpperLimitTime" t="1" qn="Q_Services_ExtractLeadsRange" cn="ExtendedDataset_UpperLimitTime" m="0">
              <schemas/>
              <specs/>
            </t>
          </ts>
          <mcs>
            <mc cn="Id"/>
          </mcs>
        </rds>
        <rds n="SFDC_Opportunity" w="Workspace" sn="SFDC_Opportunity" cn="SFDC_DataProvider" u="False" ss="" tn="Opportunity" nmo="1" f="@datediff(#ExtendedDataset_UpperLimitTime, month(6))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="True" eo_sftp="2">
          <ts>
            <t n="ExtendedDataset_UpperLimitTime" t="1" qn="Q_Services_ExtractLeadsRange" cn="ExtendedDataset_UpperLimitTime" m="0">
              <schemas/>
              <specs/>
            </t>
          </ts>
          <mcs>
            <mc cn="Id"/>
            <mc cn="LastModifiedDate"/>
          </mcs>
        </rds>
        <rds n="SFDC_User" w="Workspace" sn="SFDC_User" cn="SFDC_DataProvider" u="False" ss="" tn="User" nmo="1" f="@datediff(#ExtendedDataset_UpperLimitTime, month(6))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="False" eo_sftp="2">
          <ts>
            <t n="ExtendedDataset_UpperLimitTime" t="1" qn="Q_Services_ExtractLeadsRange" cn="ExtendedDataset_UpperLimitTime" m="0">
              <schemas/>
              <specs/>
            </t>
          </ts>
          <mcs>
            <mc cn="Id"/>
            <mc cn="LastModifiedDate"/>
          </mcs>
        </rds>
        <rds n="SFDC_OpportunityContactRole" w="Workspace" sn="SFDC_OpportunityContactRole" cn="SFDC_DataProvider" u="False" ss="" tn="OpportunityContactRole" nmo="1" f="@datediff(#ExtendedDataset_UpperLimitTime, month(6))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="True" eo_sftp="2">
          <ts>
            <t n="ExtendedDataset_UpperLimitTime" t="1" qn="Q_Services_ExtractLeadsRange" cn="ExtendedDataset_UpperLimitTime" m="0">
              <schemas/>
              <specs/>
            </t>
          </ts>
          <mcs>
            <mc cn="Id"/>
            <mc cn="LastModifiedDate"/>
          </mcs>
        </rds>
      </rdss>
      <validationExtracts/>
      <ces/>
      <extractQueries>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_Downloaded_Lead_Contact" queryAlias="Q_Timestamp_Downloaded_Lead_Contact" sw="Workspace" schemaName="Timestamp_Downloaded_Lead_Contact" at="False" ucm="True">
          <schemas/>
          <specs/>
          <cms>
            <cm qcn="SFDC_Lead_Contact_ID" itcn="SFDC_Lead_Contact_ID"/>
            <cm qcn="Time_OfCompletion_DownloadedLeads" itcn="Time_OfCompletion_DownloadedLeads"/>
            <cm qcn="Days_SinceLastScoreAtTimeOfDownload" itcn="Days_SinceLastScoreAtTimeOfDownload"/>
            <cm qcn="ContactID" itcn="ContactID"/>
          </cms>
        </extractQuery>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_DownloadedOtherTables" queryAlias="Q_Timestamp_DownloadedOtherTables" sw="Workspace" schemaName="Timestamp_DownloadedOtherTables" at="False" ucm="True">
          <schemas/>
          <specs/>
          <cms>
            <cm qcn="Time_OfCompletion_DownladedOtherTables" itcn="Time_OfCompletion_DownladedOtherTables"/>
          </cms>
        </extractQuery>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_PreScoringIncr" queryAlias="Q_Timestamp_PreScoringIncr" sw="Workspace" schemaName="Timestamp_PushToScoring" at="False" ucm="True">
          <schemas/>
          <specs/>
          <cms>
            <cm qcn="SFDC_Lead_Contact_ID" itcn="SFDC_Lead_Contact_ID"/>
            <cm qcn="Time_OfSubmission_PushToScoring" itcn="Time_OfSubmission_PushToScoring"/>
            <cm qcn="ContactID" itcn="ContactID"/>
          </cms>
        </extractQuery>
      </extractQueries>
      <extractQuerySequences/>
      <leafExtracts/>
      <launchExtracts/>
      <jobs/>
      <pdmatches/>
      <leadscroings/>
      <lssbardins/>
      <lssbardouts/>
      <lds/>
      <ecs/>
      <gCs/>
    </group>'''
    lgm.setLoadGroup(lce_xml)

    #Create LoadMAPData_Extended for ELQ and LoadMAPDataForModeling_ActivityRecord_Extended for MKTO
    lme_xml = ''
    if type == 'MKTO':
      lgm.createLoadGroup('LoadMAPDataForModeling_ActivityRecord_Extended', 'BulkScoring\Standard',  'LoadMAPDataForModeling_ActivityRecord_Extended', True, False)
      lme_xml = '''<group name="LoadMAPDataForModeling_ActivityRecord_Extended" alias="LoadMAPDataForModeling_ActivityRecord_Extended" w="Workspace" type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000" launchExpiredDays="7" createdBy="YTian@Lattice-Engines.com" path="BulkScoring\Standard" autoGenerated="False" validationValidMinutes="120" autoClearOnFailure="False" mergeRulesSaved="True" ng="False">
      <schemas/>
      <visiDBConfigurationWithMacros/>
      <targetQueries/>
      <targetQuerySequences/>
      <gvqs/>
      <rdss>
        <rds n="ActivityRecord_OtherThanNewLead" w="Workspace" sn="MKTO_ActivityRecord" cn="Marketo_DataProvider" u="False" ss="" tn="ActivityRecord" nmo="1" f="@datediff(#ExtendedDataset_UpperLimitTime, month(6)) AND activityType = 'Click Link'" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="True" sr="50000" htw="24" mtw="60" emt="True" acd="True" mgf="False" eo="1" emd="True" eo_sftp="1">
          <ts>
            <t n="ExtendedDataset_UpperLimitTime" t="1" qn="Q_Services_ExtractLeadsRange" cn="ExtendedDataset_UpperLimitTime" m="0">
              <schemas/>
              <specs/>
            </t>
          </ts>
          <mcs>
            <mc cn="activityDateTime"/>
            <mc cn="activityType"/>
            <mc cn="campaign"/>
            <mc cn="foreignSysId"/>
            <mc cn="foreignSysOrgId"/>
            <mc cn="id"/>
            <mc cn="mktgAssetName"/>
            <mc cn="mktPersonId"/>
            <mc cn="orgName"/>
            <mc cn="personName"/>
          </mcs>
        </rds>
        <rds n="ActivityRecord_OtherThanNewLead_2" w="Workspace" sn="MKTO_ActivityRecord" cn="Marketo_DataProvider" u="False" ss="" tn="ActivityRecord" nmo="1" f="@datediff(#ExtendedDataset_UpperLimitTime, month(6)) AND activityType = 'Visit Webpage'" ad="True" em="False" td="False" ic="50000" dd="24" l="1000" tw="True" sr="50000" htw="24" mtw="60" emt="True" acd="True" mgf="True" eo="1" emd="True" eo_sftp="2">
          <ts>
            <t n="ExtendedDataset_UpperLimitTime" t="1" qn="Q_Services_ExtractLeadsRange" cn="ExtendedDataset_UpperLimitTime" m="0">
              <schemas/>
              <specs/>
            </t>
          </ts>
        </rds>
        <rds n="ActivityRecord_OtherThanNewLead_3" w="Workspace" sn="MKTO_ActivityRecord" cn="Marketo_DataProvider" u="False" ss="" tn="ActivityRecord" nmo="1" f="@datediff(#ExtendedDataset_UpperLimitTime, month(6))  AND activityType = 'Interesting Moment'" ad="True" em="False" td="False" ic="50000" dd="24" l="1000" tw="True" sr="50000" htw="24" mtw="60" emt="True" acd="True" mgf="True" eo="1" emd="True" eo_sftp="2">
          <ts>
            <t n="ExtendedDataset_UpperLimitTime" t="1" qn="Q_Services_ExtractLeadsRange" cn="ExtendedDataset_UpperLimitTime" m="0">
              <schemas/>
              <specs/>
            </t>
          </ts>
        </rds>
        <rds n="ActivityRecord_OtherThanNewLead_4" w="Workspace" sn="MKTO_ActivityRecord" cn="Marketo_DataProvider" u="False" ss="" tn="ActivityRecord" nmo="1" f="@datediff(#ExtendedDataset_UpperLimitTime, month(6)) AND activityType = 'Open Email'" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="True" sr="50000" htw="24" mtw="60" emt="True" acd="True" mgf="True" eo="1" emd="True" eo_sftp="2">
          <ts>
            <t n="ExtendedDataset_UpperLimitTime" t="1" qn="Q_Services_ExtractLeadsRange" cn="ExtendedDataset_UpperLimitTime" m="0">
              <schemas/>
              <specs/>
            </t>
          </ts>
        </rds>
        <rds n="ActivityRecord_OtherThanNewLead_5" w="Workspace" sn="MKTO_ActivityRecord" cn="Marketo_DataProvider" u="False" ss="" tn="ActivityRecord" nmo="1" f="@datediff(#ExtendedDataset_UpperLimitTime, month(6)) AND activityType = 'Email Bounced Soft'" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="True" sr="50000" htw="24" mtw="60" emt="True" acd="True" mgf="True" eo="1" emd="True" eo_sftp="2">
          <ts>
            <t n="ExtendedDataset_UpperLimitTime" t="1" qn="Q_Services_ExtractLeadsRange" cn="ExtendedDataset_UpperLimitTime" m="0">
              <schemas/>
              <specs/>
            </t>
          </ts>
        </rds>
        <rds n="ActivityRecord_OtherThanNewLead_6" w="Workspace" sn="MKTO_ActivityRecord" cn="Marketo_DataProvider" u="False" ss="" tn="ActivityRecord" nmo="1" f="@datediff(#ExtendedDataset_UpperLimitTime, month(6)) AND activityType = 'Fill Out Form'" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="True" sr="50000" htw="24" mtw="60" emt="True" acd="True" mgf="True" eo="1" emd="True" eo_sftp="2">
          <ts>
            <t n="ExtendedDataset_UpperLimitTime" t="1" qn="Q_Services_ExtractLeadsRange" cn="ExtendedDataset_UpperLimitTime" m="0">
              <schemas/>
              <specs/>
            </t>
          </ts>
        </rds>
        <rds n="ActivityRecord_OtherThanNewLead_7" w="Workspace" sn="MKTO_ActivityRecord" cn="Marketo_DataProvider" u="False" ss="" tn="ActivityRecord" nmo="1" f="@datediff(#ExtendedDataset_UpperLimitTime, month(6)) AND activityType = 'Unsubscribe Email'" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="True" sr="50000" htw="24" mtw="60" emt="True" acd="True" mgf="True" eo="1" emd="True" eo_sftp="2">
          <ts>
            <t n="ExtendedDataset_UpperLimitTime" t="1" qn="Q_Services_ExtractLeadsRange" cn="ExtendedDataset_UpperLimitTime" m="0">
              <schemas/>
              <specs/>
            </t>
          </ts>
        </rds>
        <rds n="ActivityRecord_OtherThanNewLead_8" w="Workspace" sn="MKTO_ActivityRecord" cn="Marketo_DataProvider" u="False" ss="" tn="ActivityRecord" nmo="1" f="@datediff(#ExtendedDataset_UpperLimitTime, month(6))  AND activityType = 'Click Email'" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="True" sr="50000" htw="24" mtw="60" emt="True" acd="True" mgf="True" eo="1" emd="True" eo_sftp="2">
          <ts>
            <t n="ExtendedDataset_UpperLimitTime" t="1" qn="Q_Services_ExtractLeadsRange" cn="ExtendedDataset_UpperLimitTime" m="0">
              <schemas/>
              <specs/>
            </t>
          </ts>
        </rds>
      </rdss>
      <validationExtracts/>
      <ces/>
      <extractQueries>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_DownloadedActivity" queryAlias="Q_Timestamp_DownloadedActivity" sw="Workspace" schemaName="Timestamp_DownloadedActivity" at="False" ucm="True">
          <schemas/>
          <specs/>
          <cms>
            <cm qcn="MKTO_ActivityRecord_ID" itcn="MKTO_ActivityRecord_ID"/>
            <cm qcn="Time_OfCompletion_DownloadedActivity" itcn="Time_OfCompletion_DownloadedActivity"/>
          </cms>
        </extractQuery>
      </extractQueries>
      <extractQuerySequences/>
      <leafExtracts/>
      <launchExtracts/>
      <jobs/>
      <pdmatches/>
      <leadscroings/>
      <lssbardins/>
      <lssbardouts/>
      <lds/>
      <ecs/>
      <gCs/>
    </group>'''
      lgm.setLoadGroup(lme_xml)
    elif type == 'ELQ':
       lme_xml = ''
       lgm.createLoadGroup('LoadMAPData_Extended', 'BulkScoring\Standard',  'LoadMAPData_Extended', True, True)
       lme_xml = '''<group name="LoadMAPData_Extended" alias="LoadMAPData_Extended" w="Workspace" type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000" launchExpiredDays="7" createdBy="YTian@Lattice-Engines.com" path="BulkScoring\Standard" autoGenerated="False" validationValidMinutes="120" autoClearOnFailure="False" mergeRulesSaved="True" ng="False">
      <schemas/>
      <visiDBConfigurationWithMacros/>
      <targetQueries/>
      <targetQuerySequences/>
      <gvqs/>
      <rdss>
        <rds n="ELQ_Contact" w="Workspace" sn="ELQ_Contact" cn="Eloqua_DataProvider" u="False" ss="" tn="Contact" nmo="1" f="@datediff(#ExtendedDataset_UpperLimitTime, month(6)) AND @recordcount(1000000)" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="True" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="True" eo_sftp="1">
          <ts>
            <t n="ExtendedDataset_UpperLimitTime" t="1" qn="Q_Services_ExtractLeadsRange" cn="ExtendedDataset_UpperLimitTime" m="0">
              <schemas/>
              <specs/>
            </t>
          </ts>
          <mcs>
            <mc cn="C_Address1"/>
            <mc cn="C_Annual_Revenue1"/>
            <mc cn="C_BusPhone"/>
            <mc cn="C_City"/>
            <mc cn="C_Company"/>
            <mc cn="C_Company_Size1"/>
            <mc cn="C_Country"/>
            <mc cn="C_DateCreated"/>
            <mc cn="C_DateModified"/>
            <mc cn="C_EmailAddress"/>
            <mc cn="C_FirstName"/>
            <mc cn="C_Industry1"/>
            <mc cn="C_Job_Role1"/>
            <mc cn="C_LastName"/>
            <mc cn="C_Lead_Source___Most_Recent1"/>
            <mc cn="C_Lead_Source___Original1"/>
            <mc cn="C_Product_Solution_of_Interest1"/>
            <mc cn="C_SFDC_EmailOptOut1"/>
            <mc cn="C_SFDCLeadID"/>
            <mc cn="C_State_Prov"/>
            <mc cn="C_Title"/>
            <mc cn="C_Zip_Postal"/>
            <mc cn="ContactID"/>
          </mcs>
        </rds>
      </rdss>
      <validationExtracts/>
      <ces/>
      <extractQueries>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_DownloadedLeads" queryAlias="Q_Timestamp_DownloadedLeads" sw="Workspace" schemaName="Timestamp_DownloadedLeads" at="False" ucm="True">
          <schemas/>
          <specs/>
          <cms>
            <cm qcn="ELQ_Contact_ContactID" itcn="ELQ_Contact_ContactID"/>
            <cm qcn="Time_OfCompletion_DownloadedLeads" itcn="Time_OfCompletion_DownloadedLeads"/>
            <cm qcn="Days_SinceLastScoreAtTimeOfDownload" itcn="Days_SinceLastScoreAtTimeOfDownload"/>
          </cms>
        </extractQuery>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_PreScoringIncr" queryAlias="Q_Timestamp_PreScoringIncr" sw="Workspace" schemaName="Timestamp_PushToScoring" at="False" ucm="True">
          <schemas/>
          <specs/>
          <cms>
            <cm qcn="ELQ_Contact_ContactID" itcn="ELQ_Contact_ContactID"/>
            <cm qcn="Time_OfSubmission_PushToScoring" itcn="Time_OfSubmission_PushToScoring"/>
          </cms>
        </extractQuery>
      </extractQueries>
      <extractQuerySequences/>
      <leafExtracts/>
      <launchExtracts/>
      <jobs/>
      <pdmatches/>
      <leadscroings/>
      <lssbardins/>
      <lssbardouts/>
      <lds/>
      <ecs/>
      <gCs/>
    </group>'''
       lgm.setLoadGroup(lme_xml)
    elif type == 'SFDC':
      pass

    #Create Download_ExtendedDataset
    lme_xml = ''
    if type == 'MKTO':
      lgm.createLoadGroup('Download_ExtendedDataset', 'Services', 'Download: Extended Dataset', True, True)
      DED = etree.fromstring(lgm.getLoadGroup('Download_ExtendedDataset').encode('ascii', 'xmlcharrefreplace'))
      lgm.setLoadGroup(etree.tostring(DED))
      ngsxml_DED = '<ngs><ng n="LoadCRMData_Extended"/><ng n="LoadMAPDataForModeling_ActivityRecord_Extended"/><ng n="LoadMAPDataForModeling_LeadRecord"/><ng n="PropDataMatch"/></ngs>'
      lgm.setLoadGroupFunctionality('Download_ExtendedDataset', ngsxml_DED)
    elif type == 'ELQ':
      lgm.createLoadGroup('Download_ExtendedDataset', 'Services', 'Download: Extended Dataset', True, True)
      DED = etree.fromstring(lgm.getLoadGroup('Download_ExtendedDataset').encode('ascii', 'xmlcharrefreplace'))
      lgm.setLoadGroup(etree.tostring(DED))
      ngsxml_DED = '<ngs><ng n="LoadCRMData_Extended"/><ng n="LoadMAPData_Extended"/><ng n="PropDataMatch"/></ngs>'
      lgm.setLoadGroupFunctionality('Download_ExtendedDataset', ngsxml_DED)
    else:
      lgm.createLoadGroup('Download_ExtendedDataset', 'Services', 'Download: Extended Dataset', True, True)
      DED = etree.fromstring(lgm.getLoadGroup('Download_ExtendedDataset').encode('ascii', 'xmlcharrefreplace'))
      lgm.setLoadGroup(etree.tostring(DED))
      ngsxml_DED = '<ngs><ng n="LoadCRMData_Extended"/><ng n="PropDataMatch"/></ngs>'
      lgm.setLoadGroupFunctionality('Download_ExtendedDataset', ngsxml_DED)

    #Create Load Group 'Update_LatestScoredLeadsToVisiDB'
    usl_xml = ''
    if type == 'MKTO':
      lgm.createLoadGroup('Update_LatestScoredLeadsToVisiDB', 'Services', 'Update_LatestScoredLeadsToVisiDB', True, True)
      usl_xml ='''
      <group name="Update_LatestScoredLeadsToVisiDB" alias="Update: Latest Scored Leads to visiDB" w="Workspace" type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000" launchExpiredDays="7" createdBy="YTian@Lattice-Engines.com" path="Services" autoGenerated="False" validationValidMinutes="120" autoClearOnFailure="False" mergeRulesSaved="True" ng="True">
      <schemas/>
      <ngs>
        <ng n="BulkScoring_PullFromScoringDB"/>
      </ngs>
      <visiDBConfigurationWithMacros/>
      <targetQueries/>
      <targetQuerySequences/>
      <gvqs/>
      <rdss/>
      <validationExtracts/>
      <ces/>
      <extractQueries/>
      <extractQuerySequences/>
      <leafExtracts/>
      <launchExtracts/>
      <jobs/>
      <pdmatches/>
      <leadscroings/>
      <lssbardins/>
      <lssbardouts/>
      <lds/>
      <ecs/>
      <gCs/>
    </group>'''
    elif type == 'ELQ':
      lgm.createLoadGroup('Update_LatestScoredLeadsToVisiDB', 'Services', 'Update_LatestScoredLeadsToVisiDB', True, True)
      usl_xml ='''
      <group name="Update_LatestScoredLeadsToVisiDB" alias="Update: Latest Scored Leads to visiDB" w="Workspace" type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000" launchExpiredDays="7" createdBy="YTian@Lattice-Engines.com" path="Services" autoGenerated="False" validationValidMinutes="120" autoClearOnFailure="False" mergeRulesSaved="True" ng="True">
      <schemas/>
      <ngs>
        <ng n="BulkScoring_PullFromScoringDB"/>
      </ngs>
      <visiDBConfigurationWithMacros/>
      <targetQueries/>
      <targetQuerySequences/>
      <gvqs/>
      <rdss/>
      <validationExtracts/>
      <ces/>
      <extractQueries/>
      <extractQuerySequences/>
      <leafExtracts/>
      <launchExtracts/>
      <jobs/>
      <pdmatches/>
      <leadscroings/>
      <lssbardins/>
      <lssbardouts/>
      <lds/>
      <ecs/>
      <gCs/>
    </group>'''
    else:
      lgm.createLoadGroup('Update_LatestScoredLeadsToVisiDB', 'Services', 'Update_LatestScoredLeadsToVisiDB', True, True)
      usl_xml ='''<group name="Update_LatestScoredLeadsToVisiDB" alias="Update: Latest Scored Leads to visiDB" w="Workspace" type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000" launchExpiredDays="7" createdBy="YTian@Lattice-Engines.com" path="Services" autoGenerated="False" validationValidMinutes="120" autoClearOnFailure="False" mergeRulesSaved="True" ng="True">
      <schemas/>
      <ngs>
        <ng n="BulkScoring_PullFromScoringDB"/>
      </ngs>
      <visiDBConfigurationWithMacros/>
      <targetQueries/>
      <targetQuerySequences/>
      <gvqs/>
      <rdss/>
      <validationExtracts/>
      <ces/>
      <extractQueries/>
      <extractQuerySequences/>
      <leafExtracts/>
      <launchExtracts/>
      <jobs/>
      <pdmatches/>
      <leadscroings/>
      <lssbardins/>
      <lssbardouts/>
      <lds/>
      <ecs/>
      <gCs/>
    </group>'''
    lgm.setLoadGroup(usl_xml)

    #Change Nested Load Group "Initialize"
    lme_xml = ''
    if type == 'MKTO':
      initialize = etree.fromstring(lgm.getLoadGroup('Initialize').encode('ascii', 'xmlcharrefreplace'))
      lgm.setLoadGroup(etree.tostring(initialize))
      ngsxml_initialize = '<ngs><ng n="ImportMetaData"/><ng n="ImportCfgTables"/><ng n="LoadCRMData_2Days"/><ng n="LoadMAPDataForModeling_ActivityRecord_NewLead"/><ng n="LoadMAPDataForModeling_ActivityRecord_2Days"/><ng n="LoadMAPDataForModeling_LeadRecord"/><ng n="PropDataMatch"/><ng n="CreateEventTableQueries"/></ngs>'
      lgm.setLoadGroupFunctionality('Initialize', ngsxml_initialize)
    elif type == 'ELQ':
      initialize = etree.fromstring(lgm.getLoadGroup('Initialize').encode('ascii', 'xmlcharrefreplace'))
      lgm.setLoadGroup(etree.tostring(initialize))
      ngsxml_initialize = '<ngs><ng n="ImportMetaData"/><ng n="ImportCfgTables"/><ng n="LoadCRMData_2Days"/><ng n="LoadMAPData_2Days"/><ng n="PropDataMatch"/><ng n="CreateEventTableQueries"/></ngs>'
      lgm.setLoadGroupFunctionality('Initialize', ngsxml_initialize)
    else:
      initialize = etree.fromstring(lgm.getLoadGroup('Initialize').encode('ascii', 'xmlcharrefreplace'))
      lgm.setLoadGroup(etree.tostring(initialize))
      ngsxml_initialize = '<ngs><ng n="ImportMetaData"/><ng n="ImportCfgTables"/><ng n="LoadCRMData_2Days"/><ng n="PropDataMatch"/><ng n="CreateEventTableQueries"/></ngs>'
      lgm.setLoadGroupFunctionality('Initialize', ngsxml_initialize)

    #Delete Load Group "CreatePOCEventTableQueries"
    if lgm.hasLoadGroup('CreatePOCEventTableQueries'):
      lgm.deleteLoadGroup('CreatePOCEventTableQueries')
    else:
      pass
    success = True

    return success
