#!/bin/bash
cd /tmp/Python-2.7.6
./configure --prefix=/usr/local --enable-unicode=ucs4 --enable-shared LDFLAGS="-Wl,-rpath /usr/local/lib"
make && make altinstall
# First get the setup script for Setuptools:
cd /tmp
wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py
# Then install it for Python 2.7:
/usr/local/bin/python2.7 ez_setup.py
# Now install pip using the newly installed setuptools:
cd /usr/local/bin
./easy_install-2.7 pip
./pip2.7 uninstall -y numpy scipy scikit-learn fastavro openpyxl pandas pasty statsmodels
./pip2.7 install numpy==1.8.1
./pip2.7 install scipy==0.13.3
./pip2.7 install scikit-learn==0.14.1
./pip2.7 install fastavro==0.7.7
./pip2.7 install openpyxl==1.8.6
./pip2.7 install pandas==0.13.1
# Install avro
cd /tmp/avro-1.7.6
/usr/local/bin/python2.7 setup.py install
