package com.latticeengines.domain.exposed.serviceapps.cdl;

public enum CDLJobType {
    IMPORT, //
    CONSOLIDATE, //
    PROFILE, //
    ORCHESTRATION, //
    PROCESSANALYZE, //
    DFEXECUTIONCLEANUP, //
    REDSHIFTCLEANUP, //
    EXPORT, //
    ENTITYSTATECORRECTION, //
    CAMPAIGNLAUNCHSCHEDULER, //
    SCHEDULINGPA,
    SCHEDULINGNOWPA,
    TRAYTESTTIMEOUT,
    SENDDNBINTENTALERTEMAIL,
    MOCK_BROKER
}
