#!/bin/bash -x
source /etc/profile
echo "getting environment information"
echo $LE_ENVIRONMENT
echo $LE_STACK
echo $STACK_PROFILE
echo $USE_AWS

if [ "${USE_AWS}" = "true"  ]; then
    LE_STACK="${LE_STACK}_aws"
fi
echo $LE_STACK

RPMFILE=`ls /tmp/le-config-hdfs-rpm-*.rpm`
VERSION=`echo $RPMFILE | cut -d \- -f 5`
SNAPSHOT=`echo $RPMFILE | cut -d \- -f 6`

if [[ $SNAPSHOT = SNAPSHOT* ]]
    then
        VERSION=$VERSION-"SNAPSHOT"
fi

if [ ! -z "$LE_STACK" -a "$LE_STACK" != " " ]; then
    VERSION=${LE_STACK}/${VERSION}
fi

echo $VERSION

echo "replace tokens"
cd /tmp/ledp

cat ${STACK_PROFILE}


su -l yarn -c "hdfs dfs -rm -r -f /app/${VERSION}/conf"
su -l yarn -c "hdfs dfs -mkdir -p /app/${VERSION}/conf"

if [ "${USE_AWS}" = "true"  ]; then
    python replace_token.py /tmp/ledp/${LE_ENVIRONMENT}_aws ${STACK_PROFILE}
    su -l yarn -c "hdfs dfs -copyFromLocal /tmp/ledp/${LE_ENVIRONMENT}_aws/*.properties /app/${VERSION}/conf"
else
    python replace_token.py /tmp/ledp/${LE_ENVIRONMENT} ${STACK_PROFILE}
    su -l yarn -c "hdfs dfs -copyFromLocal /tmp/ledp/${LE_ENVIRONMENT}/*.properties /app/${VERSION}/conf"
fi

echo "cleaning up"
rm -rf /tmp/ledp

echo "finishing"
hdfs dfs -ls /app/${VERSION}/conf
