#!/bin/bash -x
source /etc/profile
echo "getting environment information"
echo $LE_ENVIRONMENT
echo $LE_STACK
echo $STACK_PROFILE
echo $USE_AWS

RPMFILE=`ls /tmp/le-config-hdfs-rpm-*.rpm`
VERSION=`echo $RPMFILE | cut -d \- -f 5`
SNAPSHOT=`echo $RPMFILE | cut -d \- -f 6`

if [[ $SNAPSHOT = SNAPSHOT* ]]
    then
        VERSION=$VERSION-"SNAPSHOT"
fi

if [ ! -z "$LE_STACK" -a "$LE_STACK" != " " ]; then
    VERSION=${LE_STACK}/${VERSION}
fi

echo $VERSION

echo "replace tokens"
cd /tmp/ledp
ls -al

cat ${STACK_PROFILE}

su -l yarn -c "hdfs dfs -rm -r -f /app/${VERSION}/conf" || true
su -l yarn -c "hdfs dfs -mkdir -p /app/${VERSION}/conf"
su -l yarn -c "hdfs dfs -rm -r -f /app/${VERSION}/lib" || true
su -l yarn -c "hdfs dfs -mkdir -p /app/${VERSION}/lib"

python replace_token.py /tmp/ledp/${LE_ENVIRONMENT} ${STACK_PROFILE}
su -l yarn -c "hdfs dfs -put -f /tmp/ledp/${LE_ENVIRONMENT}/*.properties /app/${VERSION}/conf"
su -l yarn -c "hdfs dfs -put -f /tmp/ledp/jacocoagent.jar /app/${VERSION}/lib"

echo "cleaning up"
rm -rf /tmp/ledp

echo "finishing"
hdfs dfs -ls /app/${VERSION}/conf
hdfs dfs -ls /app/${VERSION}/lib
