#!/bin/bash -x
source /etc/profile
echo "getting environment information"
echo $ENV_TYPE
echo $CATALINA_HOME

cd /tmp/webapps/job
JAVAFILE=`ls le-job-*.war`
VERSION=`echo $JAVAFILE | cut -d\- -f3`
SNAPSHOT=`echo $JAVAFILE | cut -d\- -f4`
if test $SNAPSHOT='SNAPSHOT'
then
    VERSION=$VERSION-$SHAPSHOT
fi

echo "copying files"
cp le-job-*.war $CATALINA_HOME/webapps/job/job\#\#$VERSION.war
cp /etc/ledp/job/$ENV_TYPE/*.properties /etc/ledp/

echo "cleaning up"
rm -rf /home/yarn/job
rm -rf /etc/ledp/job

echo "finishing"
service jetty restart > /opt/jetty/logs/start.log 2>&1
