#!/bin/bash
rm -rf /tmp/webapps/job/le-job-*.war
rm -rf /etc/ledp/job.properties
rm -rf /etc/ledp/dataplatform.properties
rm -rf /etc/ledp/dataflow.properties
rm -rf /etc/ledp/db.properties
rm -rf /etc/ledp/propdata.properties
rm -rf /etc/ledp/scoring.properties
rm -rf /etc/ledp/dellebi.properties
rm -rf /etc/ledp/pls.properties
rm -rf /etc/ledp/security.properties
rm -rf /etc/ledp/proxy.properties
rm -rf /etc/ledp/camille.properties
rm -rf /etc/ledp/workflow.properties
rm -rf /etc/ledp/monitor.properties
rm -rf /home/yarn/job
adduser yarn
groupadd yarn
mkdir -p /var/log/ledp
mkdir -p /home/yarn/logs
chmod -R 755 /var/log/ledp
chmod -R 755 /home/yarn/logs
chown -R yarn:yarn /var/log/ledp
chown -R yarn:yarn /home/yarn/logs
