#!/bin/bash
echo 'Running Preinstall'
if [ ! -d "/tmp/app/dataflow" ]; then
    rm -rf /tmp/app/dataflow/le-propdata*-shaded.jar
else
    mkdir -p /tmp/app/dataflow
fi
hdfs dfs -mkdir -p /app/dataflow/lib
hdfs dfs -rm -f /app/dataflow/lib/le-propdata*-shaded.jar

