#!/bin/bash
source /etc/profile
rm -rf $CATALINA_HOME/webapps/scoringapi/le-scoringapi-*.war
rm -rf /tmp/webapps/scoringapi/le-scoringapi-*.war
rm -rf /etc/ledp/scoringapi.properties
rm -rf /etc/ledp/oauth2.properties
rm -rf /etc/ledp/monitor.properties
rm -rf /etc/ledp/proxy.properties
adduser yarn
groupadd yarn
groupadd tomcat
mkdir -p /var/log/ledp
mkdir -p /home/yarn/logs
chmod -R 755 /var/log/ledp
chmod -R 755 /home/yarn/logs
chown -R yarn:yarn /var/log/ledp
chown -R yarn:yarn /home/yarn/logs