#
# $LastChangedBy$
# $LastChangedDate$
# $Rev$
#

from liaison import *
from appsequence import Applicability, AppSequence, StepBase
from lxml import etree


class LP_020202_SupportBulkScoringWithoutWriteBack(StepBase):
  name = 'LP_020202_SupportBulkScoringWithoutWriteBack'
  description = 'Support bulk scoring without writing back'
  version = '$Rev$'

  def __init__(self, forceApply=False):
    super(LP_020202_SupportBulkScoringWithoutWriteBack, self).__init__(forceApply)

  def getApplicability(self, appseq):
    lgm = appseq.getLoadGroupMgr()
    if not (
          lgm.hasLoadGroup('LoadScoredLeads_Step1') and lgm.hasLoadGroup('LoadScoredLeads_Step2') and lgm.hasLoadGroup(
        'PushToLeadDestination_TimeStamp')):
      return Applicability.cannotApplyFail

    return Applicability.canApply

  def apply(self, appseq):
    lg_mgr = appseq.getLoadGroupMgr()
    conn_mgr = appseq.getConnectionMgr()
    # Modify the dataloader
    extract_queries_xml = '''
    <extractQueries>
        <extractQuery qw="Workspace" queryName="Q_Bard_LeadScoreStage_PreLoadScoredLeads"
        queryAlias="Q_Bard_LeadScoreStage_PreLoadScoredLeads" sw="Workspace" schemaName="Bard_LeadScoreStage"
        at="False" ucm="True">
          <schemas/>
          <specs/>
          <cms>
            <cm qcn="LeadID" itcn="LeadID"/>
            <cm qcn="Score" itcn="Score"/>
            <cm qcn="Bucket_Display_Name" itcn="Bucket_Display_Name"/>
            <cm qcn="Play_Display_Name" itcn="Play_Display_Name"/>
            <cm qcn="RawScore" itcn="RawScore"/>
            <cm qcn="Probability" itcn="Probability"/>
            <cm qcn="Lift" itcn="Lift"/>
            <cm qcn="Percentile" itcn="Percentile"/>
          </cms>
        </extractQuery>
      </extractQueries>
     '''
    lg_mgr.setLoadGroupFunctionality('LoadScoredLeads_Step1', extract_queries_xml)

    new_step_xml = '''
    <group name="BulkScoring_PullFromScoringDB" alias="BulkScoring_PullFromScoringDB" w="Workspace" type="1"
    scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000"
    launchExpiredDays="7" createdBy="lyan@lattice-engines.com" path="BulkScoring\Standard" autoGenerated="False"
    validationValidMinutes="120" autoClearOnFailure="True" mergeRulesSaved="True" ng="True">
      <schemas/>
      <ngs>
        <ng n="LoadScoredLeads_Step1"/>
        <ng n="LoadScoredLeads_Step2"/>
        <ng n="PushToLeadDestination_TimeStamp"/>
      </ngs>
    </group>
      '''
    lg_mgr.setLoadGroup(new_step_xml)

    # Add visiDB specs

    specs = 'SpecLatticeNamedElements(('
    specs += '''
    SpecLatticeNamedElement(
      SpecLatticeQuery(
        LatticeAddressSetPushforward(
          LatticeAddressExpressionFromLAS(
            LatticeAddressSetMeet(
              (
                LatticeAddressSetFcn(
                  LatticeFunctionExpression(
                    LatticeFunctionOperatorIdentifier("IsNullValue"),
                    LatticeFunctionExpressionConstant(
                      "1",
                      DataTypeInt
                    )
                  ),
                  LatticeAddressSetPi(
                    LatticeAddressExpressionAtomic(
                      LatticeAddressAtomicIdentifier(
                        ContainerElementName("Bard_LeadScoreStage")
                      )
                    )
                  )
                )
              )
            )
          ),
          LatticeAddressSetMeet(
            (
              LatticeAddressSetFcn(
                LatticeFunctionExpression(
                  LatticeFunctionOperatorIdentifier("IsNullValue"),
                  LatticeFunctionExpressionConstant(
                    "1",
                    DataTypeInt
                  )
                ),
                LatticeAddressSetPi(
                  LatticeAddressExpressionAtomic(
                    LatticeAddressAtomicIdentifier(
                      ContainerElementName("Bard_LeadScoreStage")
                    )
                  )
                )
              )
            )
          ),
          LatticeAddressExpressionMeet(
            (
              LatticeAddressExpressionAtomic(
                LatticeAddressAtomicIdentifier(
                  ContainerElementName("Bard_LeadScoreStage")
                )
              )
            )
          )
        ),
        SpecQueryNamedFunctions(
          SpecQueryNamedFunctionExpression(
            ContainerElementName("Bard_LeadScoreStage"),
            LatticeFunctionIdentifierAddressAtomic(
              LatticeAddressAtomicIdentifier(
                ContainerElementName("Bard_LeadScoreStage")
              )
            )
          )
          SpecQueryNamedFunctionEntityFunctionBoundary
          SpecQueryNamedFunctionExpression(
            ContainerElementName("LeadID"),
            LatticeFunctionExpressionTransform(
              LatticeFunctionIdentifier(
                ContainerElementNameTableQualifiedName(
                  LatticeSourceTableIdentifier(
                    ContainerElementName("Bard_LeadScoreStage")
                  ),
                  ContainerElementName("LeadID")
                )
              ),
              LatticeAddressSetFromFcnSupport(
                LatticeFunctionIdentifier(
                  ContainerElementNameTableQualifiedName(
                    LatticeSourceTableIdentifier(
                      ContainerElementName("Bard_LeadScoreStage")
                    ),
                    ContainerElementName("LeadID")
                  )
                )
              ),
              FunctionAggregationOperator("Sum")
            )
          )
          SpecQueryNamedFunctionExpression(
            ContainerElementName("Score"),
            LatticeFunctionExpressionTransform(
              LatticeFunctionIdentifier(
                ContainerElementNameTableQualifiedName(
                  LatticeSourceTableIdentifier(
                    ContainerElementName("Bard_LeadScoreStage")
                  ),
                  ContainerElementName("Score")
                )
              ),
              LatticeAddressSetFromFcnSupport(
                LatticeFunctionIdentifier(
                  ContainerElementNameTableQualifiedName(
                    LatticeSourceTableIdentifier(
                      ContainerElementName("Bard_LeadScoreStage")
                    ),
                    ContainerElementName("Score")
                  )
                )
              ),
              FunctionAggregationOperator("Sum")
            )
          )
          SpecQueryNamedFunctionExpression(
            ContainerElementName("Bucket_Display_Name"),
            LatticeFunctionExpressionTransform(
              LatticeFunctionIdentifier(
                ContainerElementNameTableQualifiedName(
                  LatticeSourceTableIdentifier(
                    ContainerElementName("Bard_LeadScoreStage")
                  ),
                  ContainerElementName("Bucket_Display_Name")
                )
              ),
              LatticeAddressSetFromFcnSupport(
                LatticeFunctionIdentifier(
                  ContainerElementNameTableQualifiedName(
                    LatticeSourceTableIdentifier(
                      ContainerElementName("Bard_LeadScoreStage")
                    ),
                    ContainerElementName("Bucket_Display_Name")
                  )
                )
              ),
              FunctionAggregationOperator("Max")
            )
          )
          SpecQueryNamedFunctionExpression(
            ContainerElementName("Play_Display_Name"),
            LatticeFunctionExpressionTransform(
              LatticeFunctionIdentifier(
                ContainerElementNameTableQualifiedName(
                  LatticeSourceTableIdentifier(
                    ContainerElementName("Bard_LeadScoreStage")
                  ),
                  ContainerElementName("Play_Display_Name")
                )
              ),
              LatticeAddressSetFromFcnSupport(
                LatticeFunctionIdentifier(
                  ContainerElementNameTableQualifiedName(
                    LatticeSourceTableIdentifier(
                      ContainerElementName("Bard_LeadScoreStage")
                    ),
                    ContainerElementName("Play_Display_Name")
                  )
                )
              ),
              FunctionAggregationOperator("Max")
            )
          )
          SpecQueryNamedFunctionExpression(
            ContainerElementName("RawScore"),
            LatticeFunctionExpressionTransform(
              LatticeFunctionIdentifier(
                ContainerElementNameTableQualifiedName(
                  LatticeSourceTableIdentifier(
                    ContainerElementName("Bard_LeadScoreStage")
                  ),
                  ContainerElementName("RawScore")
                )
              ),
              LatticeAddressSetFromFcnSupport(
                LatticeFunctionIdentifier(
                  ContainerElementNameTableQualifiedName(
                    LatticeSourceTableIdentifier(
                      ContainerElementName("Bard_LeadScoreStage")
                    ),
                    ContainerElementName("RawScore")
                  )
                )
              ),
              FunctionAggregationOperator("Sum")
            )
          )
          SpecQueryNamedFunctionExpression(
            ContainerElementName("Probability"),
            LatticeFunctionExpressionTransform(
              LatticeFunctionIdentifier(
                ContainerElementNameTableQualifiedName(
                  LatticeSourceTableIdentifier(
                    ContainerElementName("Bard_LeadScoreStage")
                  ),
                  ContainerElementName("Probability")
                )
              ),
              LatticeAddressSetFromFcnSupport(
                LatticeFunctionIdentifier(
                  ContainerElementNameTableQualifiedName(
                    LatticeSourceTableIdentifier(
                      ContainerElementName("Bard_LeadScoreStage")
                    ),
                    ContainerElementName("Probability")
                  )
                )
              ),
              FunctionAggregationOperator("Sum")
            )
          )
          SpecQueryNamedFunctionExpression(
            ContainerElementName("Lift"),
            LatticeFunctionExpressionTransform(
              LatticeFunctionIdentifier(
                ContainerElementNameTableQualifiedName(
                  LatticeSourceTableIdentifier(
                    ContainerElementName("Bard_LeadScoreStage")
                  ),
                  ContainerElementName("Lift")
                )
              ),
              LatticeAddressSetFromFcnSupport(
                LatticeFunctionIdentifier(
                  ContainerElementNameTableQualifiedName(
                    LatticeSourceTableIdentifier(
                      ContainerElementName("Bard_LeadScoreStage")
                    ),
                    ContainerElementName("Lift")
                  )
                )
              ),
              FunctionAggregationOperator("Sum")
            )
          )
          SpecQueryNamedFunctionExpression(
            ContainerElementName("Percentile"),
            LatticeFunctionExpressionTransform(
              LatticeFunctionIdentifier(
                ContainerElementNameTableQualifiedName(
                  LatticeSourceTableIdentifier(
                    ContainerElementName("Bard_LeadScoreStage")
                  ),
                  ContainerElementName("Percentile")
                )
              ),
              LatticeAddressSetFromFcnSupport(
                LatticeFunctionIdentifier(
                  ContainerElementNameTableQualifiedName(
                    LatticeSourceTableIdentifier(
                      ContainerElementName("Bard_LeadScoreStage")
                    ),
                    ContainerElementName("Percentile")
                  )
                )
              ),
              FunctionAggregationOperator("Sum")
            )
          )
        ),
        SpecQueryResultSetAll
      ),
      ContainerElementName("Q_Bard_LeadScoreStage_PreLoadScoredLeads")
    )
    '''

    specs += '))'

    conn_mgr.setSpec('Q_Bard_LeadScoreStage_PreLoadScoredLeads', specs)

    return True
