#!/bin/sh
echo "examine environment vars"
echo "getting environment information"
echo $LE_ENVIRONMENT
echo $LE_STACK
echo $STACK_PROFILE
echo $USE_AWS

HADOOP_CONF_DIR=/usr/hdp/current/hadoop-client/conf

echo $HADOOP_CONF_DIR

JARFILE=`ls /tmp/swlib/le-swlib-*-shaded.jar`
VERSION=`echo $JARFILE | cut -d \- -f 3`
SNAPSHOT=`echo $JARFILE | cut -d \- -f 4`

if test $SNAPSHOT = "SNAPSHOT"
    then
        VERSION=$VERSION-"SNAPSHOT"
fi

echo $VERSION

for sf in 'dataflowapi|prospectdiscovery' 'dataflowapi|leadprioritization' 'dataflowapi|cdl' 'workflowapi|prospectdiscovery' 'workflowapi|leadprioritization' 'workflowapi|cdl' 'workflowapi|datacloud'
do
    module=$(echo ${sf} | cut -d \| -f 1)
    library=$(echo ${sf} | cut -d \| -f 2)

    echo "clean up hdfs for module=${module} library=${library}"
    hdfs dfs -mkdir -p /app/${LE_STACK}/swlib/${module}/com/latticeengines/le-serviceflows-${library}/${VERSION}
    hdfs dfs -rm -r -f /app/${LE_STACK}/swlib/${module}/com/latticeengines/le-serviceflows-${library}/${VERSION}/*

    echo "install le-serviceflows-${library} for ${module}"
    java -cp $JARFILE:$HADOOP_CONF_DIR com.latticeengines.swlib.SwlibTool \
        -o install \
        -n ${library} \
        -m ${module} \
        -g com.latticeengines \
        -a le-serviceflows-${library} \
        -v ${VERSION} \
        -s ${LE_STACK} \
        -i com.latticeengines.${library}.Initializer \
        -f /tmp/swlib/le-serviceflows-${library}-*-shaded.jar
done


