#!/bin/sh
echo "examine environment vars"
HADOOP_CONF_DIR=/usr/hdp/current/hadoop-client/conf

echo $HADOOP_CONF_DIR

JARFILE=`ls /tmp/le-swlib-*-shaded.jar`
VERSION=`echo $JARFILE | cut -d \- -f 3`
SNAPSHOT=`echo $JARFILE | cut -d \- -f 4`

if test $SNAPSHOT = "SNAPSHOT"
    then
        VERSION=$VERSION-"SNAPSHOT"
fi

echo $VERSION

echo "clean up hdfs"
hdfs dfs -mkdir -p /app/swlib/dataflowapi/com/latticeengines/le-serviceflows-prospectdiscovery/$VERSION
hdfs dfs -mkdir -p /app/swlib/dataflowapi/com/latticeengines/le-serviceflows-leadprioritization/$VERSION

hdfs dfs -rm -r -f /app/swlib/dataflowapi/com/latticeengines/le-serviceflows-prospectdiscovery/$VERSION/*
hdfs dfs -rm -r -f /app/swlib/dataflowapi/com/latticeengines/le-serviceflows-leadprioritization/$VERSION/*

echo "install le-serviceflows-prospectdiscovery for dataflowapi"
java -cp $JARFILE:$HADOOP_CONF_DIR com.latticeengines.swlib.SwlibTool \
    -o install \
    -m dataflowapi \
    -g com.latticeengines \
    -a le-serviceflows-prospectdiscovery \
    -v $VERSION \
    -i com.latticeengines.prospectdiscovery.Initializer \
    -f /tmp/le-serviceflows-prospectdiscovery-*-shaded.jar

echo "install le-serviceflows-leadprioritization for dataflowapi"
java -cp $JARFILE:$HADOOP_CONF_DIR com.latticeengines.swlib.SwlibTool \
    -o install \
    -m dataflowapi \
    -g com.latticeengines \
    -a le-serviceflows-leadprioritization \
    -v $VERSION \
    -i com.latticeengines.leadprioritization.Initializer \
    -f /tmp/le-serviceflows-leadprioritization-*-shaded.jar


