#!/bin/sh
JARFILE=`ls /tmp/le-swlib-*-shaded.jar`
VERSION=`echo $JARFILE | cut -d \- -f 3`
SNAPSHOT=`echo $JARFILE | cut -d \- -f 4`

if test $SNAPSHOT = "SNAPSHOT"
    then
        VERSION=$VERSION-"SNAPSHOT"
fi

java -cp $JARFILE:$HADOOP_CONF_DIR com.latticeengines.swlib.SwlibTool \
    -o install \
    -m dataflowapi \
    -g com.latticeengines \
    -a le-serviceflows \
    -v $VERSION \
    -i com.latticeengines.prospectdiscovery.Initializer \
    -f /tmp/le-serviceflows-prospectdiscovery-*-shaded.jar

java -cp $JARFILE:$HADOOP_CONF_DIR com.latticeengines.swlib.SwlibTool \
    -o install \
    -m propdata \
    -g com.latticeengines \
    -a le-serviceflows \
    -v $VERSION \
    -i com.latticeengines.propdata.Initializer \
    -f /tmp/le-serviceflows-propdata-*-shaded.jar