#!/bin/sh -x

JARFILE=`ls /tmp/le-swlib-*-shaded.jar`
VERSION=`echo $JARFILE | cut -d \- -f 3`
SNAPSHOT=`echo $JARFILE | cut -d \- -f 4`

if test $SNAPSHOT = "SNAPSHOT"
    then
        VERSION=$VERSION-"SNAPSHOT"
fi

hdfs dfs -mkdir -p /app/swlib/dataflowapi/com/latticeengines/le-serviceflows-prospectdiscovery/$VERSION
hdfs dfs -mkdir -p /app/swlib/dataflowapi/com/latticeengines/le-serviceflows-leadprioritization/$VERSION
hdfs dfs -mkdir -p /app/swlib/propdata/com/latticeengines/le-serviceflows-propdata/$VERSION

hdfs dfs -rm -r -f /app/swlib/dataflowapi/com/latticeengines/le-serviceflows-prospectdiscovery/$VERSION/*
hdfs dfs -rm -r -f /app/swlib/dataflowapi/com/latticeengines/le-serviceflows-leadprioritization/$VERSION/*
hdfs dfs -rm -r -f /app/swlib/propdata/com/latticeengines/le-serviceflows-propdata/$VERSION/*