package com.latticeengines.perf.job.runnable.commandline.impl;

import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.ParseException;
import com.latticeengines.perf.cli.setup.CommandLineOption;
import com.latticeengines.perf.cli.setup.CommandLineSetup;
import com.latticeengines.perf.job.runnable.impl.GetJobStatus;

public class CommandLineGetJobStatus extends GetJobStatus implements CommandLineSetup {

    private CommandLine cl;

    public CommandLineGetJobStatus() {
    }

    public CommandLineGetJobStatus(CommandLine cl, String restEndpointHost) {
        super(cl.getOptionValue("appId"), restEndpointHost);
        this.cl = cl;
    }

    @Override
    public void setupOptions(String[] args) throws ParseException {
        Options ops = new Options();
        Option appId = new CommandLineOption("appId", "applicationId", true, true, "ApplicationId generated by yarn");
        ops.addOption(appId);
        cl = clp.parse(ops, args);

    }

    @Override
    public CommandLine getCommandLine() {
        return cl;
    }

}
