#!/bin/bash
echo "postinstalling now"
ln -s jetty-distribution-9.1.4.v20140401 jetty
chown -R yarn:yarn /opt/jetty
cd /etc/init.d
ln -s /opt/jetty/bin/jetty.sh jetty
chkconfig --add jetty
chkconfig --level 345 jetty on