
#
# $LastChangedBy: lyan $
# $LastChangedDate: 2015-11-19 19:51:40 +0800 (Thu, 19 Nov 2015) $
# $Rev: 71042 $
#

from liaison import *
from appsequence import Applicability, StepBase

Adhoc_LoadCRMData_FromSpecificDay = '''
<group name="Adhoc_LoadCRMData_FromSpecificDay" alias="Adhoc_LoadCRMData_FromSpecificDay" w="Workspace"
type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000"
launchExpiredDays="7" createdBy="lyan@lattice-engines.com" path="Adhoc" autoGenerated="False"
validationValidMinutes="120" autoClearOnFailure="True" mergeRulesSaved="True" ng="False">
  <schemas />
  <visiDBConfigurationWithMacros />
  <targetQueries />
  <targetQuerySequences />
  <gvqs />
  <rdss>
    <rds n="SFDC_Lead" w="Workspace" sn="SFDC_Lead" cn="SFDC_DataProvider" u="False" ss="" tn="Lead" nmo="1"
    f="LastModifiedDate &gt; 2016-03-12T00:00:00Z" ad="False" em="False" td="False" ic="" dd="" l="1000" tw="False"
    sr="50000" htw="24" mtw="60" emt="False" acd="False" mgf="False" eo="2" emd="False" eo_sftp="2">
      <mcs>
        <mc cn="AnnualRevenue" />
        <mc cn="City" />
        <mc cn="Company" />
        <mc cn="ConvertedOpportunityId" />
        <mc cn="Country" />
        <mc cn="CreatedDate" />
        <mc cn="Email" />
        <mc cn="FirstName" />
        <mc cn="Id" />
        <mc cn="Industry" />
        <mc cn="LastModifiedDate" />
        <mc cn="LastName" />
        <mc cn="LeadSource" />
        <mc cn="NumberOfEmployees" />
        <mc cn="OwnerId" />
        <mc cn="Phone" />
        <mc cn="State" />
        <mc cn="Title" />
      </mcs>
    </rds>
    <rds n="SFDC_Contact" w="Workspace" sn="SFDC_Contact" cn="SFDC_DataProvider" u="False" ss="" tn="Contact" nmo="1"
    f="LastModifiedDate &gt; 2016-03-12T00:00:00Z" ad="False" em="False" td="False" ic="" dd="" l="1000" tw="False"
    sr="50000" htw="24" mtw="60" emt="False" acd="False" mgf="False" eo="2" emd="False" eo_sftp="2">
      <mcs>
        <mc cn="AccountId" />
        <mc cn="CreatedDate" />
        <mc cn="Email" />
        <mc cn="FirstName" />
        <mc cn="Id" />
        <mc cn="LastModifiedDate" />
        <mc cn="LastName" />
        <mc cn="LeadSource" />
        <mc cn="MailingCity" />
        <mc cn="MailingCountry" />
        <mc cn="MailingState" />
        <mc cn="Phone" />
        <mc cn="Title" />
      </mcs>
    </rds>
    <rds n="SFDC_Account" w="Workspace" sn="SFDC_Account" cn="SFDC_DataProvider" u="False" ss="" tn="Account" nmo="1"
    f="LastModifiedDate &gt; 2016-03-12T00:00:00Z" ad="False" em="False" td="False" ic="" dd="" l="1000" tw="False"
    sr="50000" htw="24" mtw="60" emt="False" acd="False" mgf="False" eo="2" emd="False" eo_sftp="2">
      <mcs>
        <mc cn="AnnualRevenue" />
        <mc cn="BillingCity" />
        <mc cn="BillingCountry" />
        <mc cn="BillingState" />
        <mc cn="CreatedDate" />
        <mc cn="Id" />
        <mc cn="Industry" />
        <mc cn="Name" />
        <mc cn="NumberOfEmployees" />
      </mcs>
    </rds>
    <rds n="SFDC_Opportunity" w="Workspace" sn="SFDC_Opportunity" cn="SFDC_DataProvider" u="False" ss=""
    tn="Opportunity" nmo="1" f="LastModifiedDate &gt; 2016-03-12T00:00:00Z" ad="False" em="False" td="False" ic=""
    dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="False" mgf="False" eo="2" emd="False"
    eo_sftp="2">
      <mcs>
        <mc cn="AccountId" />
        <mc cn="Amount" />
        <mc cn="CampaignId" />
        <mc cn="CloseDate" />
        <mc cn="CreatedDate" />
        <mc cn="ExpectedRevenue" />
        <mc cn="ForecastCategory" />
        <mc cn="Id" />
        <mc cn="IsClosed" />
        <mc cn="IsDeleted" />
        <mc cn="IsWon" />
        <mc cn="LastActivityDate" />
        <mc cn="LastModifiedDate" />
        <mc cn="LeadSource" />
        <mc cn="Name" />
        <mc cn="OwnerId" />
        <mc cn="Probability" />
        <mc cn="StageName" />
        <mc cn="Type" />
      </mcs>
    </rds>
    <rds n="SFDC_OpportunityContactRole" w="Workspace" sn="SFDC_OpportunityContactRole" cn="SFDC_DataProvider"
    u="False" ss="" tn="OpportunityContactRole" nmo="1" f="LastModifiedDate &gt; 2016-03-12T00:00:00Z" ad="False"
    em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="False"
    mgf="False" eo="2" emd="False" eo_sftp="2">
      <mcs>
        <mc cn="ContactId" />
        <mc cn="CreatedById" />
        <mc cn="CreatedDate" />
        <mc cn="Id" />
        <mc cn="IsDeleted" />
        <mc cn="IsPrimary" />
        <mc cn="LastModifiedById" />
        <mc cn="LastModifiedDate" />
        <mc cn="OpportunityId" />
        <mc cn="Role" />
        <mc cn="SystemModstamp" />
      </mcs>
    </rds>
    <rds n="SFDC_User" w="Workspace" sn="SFDC_User" cn="SFDC_DataProvider" u="False" ss="" tn="User" nmo="1"
    f="LastModifiedDate &gt; 2016-03-12T00:00:00Z" ad="False" em="False" td="False" ic="" dd="" l="1000" tw="False"
    sr="50000" htw="24" mtw="60" emt="False" acd="False" mgf="False" eo="2" emd="False" eo_sftp="2">
      <mcs>
        <mc cn="Department" />
        <mc cn="Id" />
        <mc cn="LastModifiedDate" />
        <mc cn="Name" />
        <mc cn="Title" />
      </mcs>
    </rds>
  </rdss>
  <validationExtracts />
  <ces />
  <extractQueries>
    <extractQuery qw="Workspace" queryName="Q_Timestamp_Downloaded_Lead_Contact"
    queryAlias="Q_Timestamp_Downloaded_Lead_Contact" sw="Workspace" schemaName="Timestamp_Downloaded_Lead_Contact"
    at="False" ucm="True">
      <schemas />
      <specs />
      <cms>
        <cm qcn="SFDC_Lead_Contact_ID" itcn="SFDC_Lead_Contact_ID" />
        <cm qcn="Time_OfCompletion_DownloadedLeads" itcn="Time_OfCompletion_DownloadedLeads" />
        <cm qcn="Days_SinceLastScoreAtTimeOfDownload" itcn="Days_SinceLastScoreAtTimeOfDownload" />
      </cms>
    </extractQuery>
    <extractQuery qw="Workspace" queryName="Q_Timestamp_DownloadedOtherTables"
    queryAlias="Q_Timestamp_DownloadedOtherTables" sw="Workspace" schemaName="Timestamp_DownloadedOtherTables"
    at="False" ucm="True">
      <schemas />
      <specs />
      <cms>
        <cm qcn="Time_OfCompletion_DownladedOtherTables" itcn="Time_OfCompletion_DownladedOtherTables" />
      </cms>
    </extractQuery>
  </extractQueries>
  <extractQuerySequences />
  <leafExtracts />
  <launchExtracts />
  <jobs />
  <pdmatches />
  <leadscroings />
  <lssbardins />
  <lssbardouts />
  <lds />
  <ecs />
  <gCs />
</group>'''

Const_TimeZoneOffset = '''
SpecLatticeNamedElements((
SpecLatticeNamedElement(
	SpecLatticeFunction(
		LatticeFunctionExpressionConstant(
			"4",
			DataTypeInt
		),
		DataTypeUnknown,
		SpecFunctionTypeMetric,
		SpecFunctionSourceTypeCalculation,
		SpecDefaultValueNull,
		SpecDescription("")
	),
	ContainerElementName("Const_TimeZoneOffset")
)
))
'''


class LP_020401_ChangeTimezoneOffset( StepBase ):

  name        = 'LP_020401_ChangeTimezoneOffset'
  description = 'Change the Const_TimezoneOffset from 5 to 4 on SFDC template due to DST time change'
  version     = '$Rev: 71042 $'


  def __init__( self, forceApply = False ):
    super( LP_020401_ChangeTimezoneOffset, self ).__init__( forceApply )


  def getApplicability( self, appseq ):
    lgm = appseq.getLoadGroupMgr()
    type = appseq.getText('template_type')

    if type == 'SFDC':
      return Applicability.canApply
    return Applicability.cannotApplyPass


  def apply( self, appseq ):
    conn_mgr = appseq.getConnectionMgr()
    lgm = appseq.getLoadGroupMgr()
    type = appseq.getText('template_type')
    xml_lg = ''
    spec = ''
    if type == 'SFDC':
      xml_lg = Adhoc_LoadCRMData_FromSpecificDay
      spec = Const_TimeZoneOffset
      lgm.setLoadGroup( xml_lg )
      conn_mgr.setSpec('Adhoc_LoadCRMData_FromSpecificDay', spec)
    return True