#!/usr/bin/python

import os,sys,re
from liaison import *
from appsequence import Applicability, AppSequence, StepBase


def MissingLeadsReport(tenantName):
  
    #Apply the obtained filters to the missing lead queries: Q_Diagnostic_DownloadedUnscoredLeads and Q_Diagnostic_MissingDownloadedLeads
    conn_mgr = ConnectionMgrFactory.Create('visiDB', tenant_name=tenantName)
    lgm =conn_mgr.getLoadGroupMgr()
    q_scoring  = conn_mgr.getQuery('Q_PLS_Scoring_Incremental')
    q_unscored = conn_mgr.getQuery('Q_Diagnostic_DownloadedUnscoredLeads')
    q_missing  = conn_mgr.getQuery('Q_Diagnostic_MissingDownloadedLeads')

    for filter in q_scoring.getFilters():
        if filter.definition() not in [i.definition() for i in q_unscored.getFilters()]:
            q_unscored.filters_.append(filter)
        else:
            pass
    conn_mgr.setSpec('Q_Diagnostic_DownloadedUnscoredLeads',q_unscored.SpecLatticeNamedElements())

    for filter in q_scoring.getFilters():
        if filter.definition() not in [i.definition() for i in q_missing.getFilters()]:
            q_missing.filters_.append(filter)
        else:
            pass
    conn_mgr.setSpec('Q_Diagnostic_MissingDownloadedLeadss',q_missing.SpecLatticeNamedElements())

    #Get the customized score/score-date fields from the the LG PushLeadsLastScoredToDestination and then replace the fields in the related specs and LGs
    lgm =conn_mgr.getLoadGroupMgr()
    type = conn_mgr.getText('template_type')
    customerId = conn_mgr.getText('customer_id')
    scoreField = conn_mgr.getText('score_field')
    scoreDateField = conn_mgr.getText('score_date_field')
    sfdcLeadScoreField = conn_mgr.getText('sfdc_lead_score_field')
    sfdcContactScoreField = conn_mgr.getText('sfdc_contact_score_field')
    sfdcLeadScoreDateField = conn_mgr.getText('sfdc_lead_score_date_field')
    sfdcContactScoreDateField = conn_mgr.getText('sfdc_contact_score_date_field')

    # Modified score/score-date fields of Diagnostic_LoadLeads
    if type == 'MKTO':
      step1_xml = '''
      <group name="Diagnostic_LoadLeads" alias="Diagnostic_LoadLeads" w="Workspace" type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000" launchExpiredDays="7" createdBy="richard.liu@lattice-engines.com" path="Diagnostic" autoGenerated="False" validationValidMinutes="120" autoClearOnFailure="False" mergeRulesSaved="True" ng="False">
        <schemas />
        <visiDBConfigurationWithMacros />
        <targetQueries />
        <targetQuerySequences />
        <rdss>
          <rds n="MKTO_ActivityRecord_Validation" w="Workspace" sn="MKTO_ActivityRecord_Validation" cn="Marketo_DataProvider" u="False" ss="" tn="ActivityRecord" nmo="1" f="@recordCOUNT(5000) AND&#xD;&#xA;activityDateTime &gt; #Diagnostic_LowerLimitTime AND activityDateTime &lt; #Diagnostic_UpperLimitTime AND&#xD;&#xA;activityType in ('New Lead','Click Link','Visit Webpage','Interesting Moment','Open Email','Email Bounced Soft','Fill Out Form','Unsubscribe Email','Click Email')" ad="False" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="False" mgf="False" eo="2" emd="False" eo_sftp="1">
            <ts>
              <t n="Diagnostic_LowerLimitTime" t="1" qn="Q_Diagnostic_ExtractLeadsRange" cn="Diagnostic_LowerLimitTime" m="0">
                <schemas />
                <specs />
              </t>
              <t n="Diagnostic_UpperLimitTime" t="1" qn="Q_Diagnostic_ExtractLeadsRange" cn="Diagnostic_UpperLimitTime" m="0">
                <schemas />
                <specs />
              </t>
            </ts>
            <mcs>
              <mc cn="activityDateTime" />
              <mc cn="activityType" />
              <mc cn="campaign" />
              <mc cn="foreignSysId" />
              <mc cn="foreignSysOrgId" />
              <mc cn="id" />
              <mc cn="mktgAssetName" />
              <mc cn="mktPersonId" />
              <mc cn="orgName" />
              <mc cn="personName" />
            </mcs>
          </rds>
          <rds n="MKTO_LeadRecord_Validation" w="Workspace" sn="MKTO_LeadRecord_Validation" cn="Marketo_DataProvider" u="False" ss="" tn="LeadRecord" nmo="1" f="id in #IDs" ad="False" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="False" mgf="False" eo="2" emd="False" eo_sftp="1">
            <ts>
              <t n="IDs" t="2" qn="Q_Diagnostic_GetLeadRecordID" cn="MKTO_LeadRecord_ID" m="100">
                <schemas />
                <specs />
              </t>
            </ts>
            <mcs>
              <mc cn="Id" />
              <mc cn="__SCORE_DATE_FIELD__" />
              <mc cn="__SCORE_FIELD__" />
            </mcs>
          </rds>
        </rdss>
        <validationExtracts />
        <ces />
        <extractQueries />
        <extractQuerySequences />
        <leafExtracts />
        <launchExtracts />
        <jobs />
        <pdmatches />
        <leadscroings />
        <lssbardins />
        <lssbardouts />
        <lds />
        <ecs />
        <gCs />
      </group>
      '''
    elif type == 'ELQ':
      step1_xml = '''
          <group name="Diagnostic_LoadLeads" alias="Diagnostic_LoadLeads" w="Workspace" type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000" launchExpiredDays="7" createdBy="richard.liu@lattice-engines.com" path="Diagnostic" autoGenerated="False" validationValidMinutes="120" autoClearOnFailure="False" mergeRulesSaved="True" ng="False">
      <schemas />
      <visiDBConfigurationWithMacros />
      <targetQueries />
      <targetQuerySequences />
      <rdss>
        <rds n="ELQ_Contact_Validation" w="Workspace" sn="ELQ_Contact_Validation" cn="Eloqua_Bulk_DataProvider" u="False" ss="" tn="Contact" nmo="1" f="@recordCOUNT(1000) AND&#xD;&#xA;(C_DateModified &gt; #Diagnostic_LowerLimitTime AND C_DateModified &lt; #Diagnostic_UpperLimitTime AND (__SCORE_DATE_FIELD__ &lt; #Diagnostic_RescoreThreshold OR __SCORE_FIELD__ = 0 ))" ad="False" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="False" mgf="False" eo="2" emd="False" eo_sftp="1">
          <ts>
            <t n="Diagnostic_LowerLimitTime" t="1" qn="Q_Diagnostic_ExtractLeadsRange" cn="Diagnostic_LowerLimitTime" m="0">
              <schemas />
              <specs />
            </t>
            <t n="Diagnostic_UpperLimitTime" t="1" qn="Q_Diagnostic_ExtractLeadsRange" cn="Diagnostic_UpperLimitTime" m="0">
              <schemas />
              <specs />
            </t>
            <t n="Diagnostic_RescoreThreshold" t="1" qn="Q_Diagnostic_ExtractLeadsRange" cn="Diagnostic_RescoreThreshold" m="0">
              <schemas />
              <specs />
            </t>
          </ts>
          <mcs>
            <mc cn="C_DateCreated" />
            <mc cn="C_DateModified" />
            <mc cn="__SCORE_DATE_FIELD__" />
            <mc cn="__SCORE_FIELD__" />
            <mc cn="ContactID" />
          </mcs>
        </rds>
      </rdss>
      <validationExtracts />
      <ces />
      <extractQueries />
      <extractQuerySequences />
      <leafExtracts />
      <launchExtracts />
      <jobs />
      <pdmatches />
      <leadscroings />
      <lssbardins />
      <lssbardouts />
      <lds />
      <ecs />
      <gCs />
    </group>
    '''
    else :
      step1_xml = '''
      <group name="Diagnostic_LoadLeads" alias="Diagnostic_LoadLeads" w="Workspace" type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000" launchExpiredDays="7" createdBy="richard.liu@lattice-engines.com" path="Diagnostic" autoGenerated="False" validationValidMinutes="120" autoClearOnFailure="False" mergeRulesSaved="True" ng="False">
        <schemas />
        <visiDBConfigurationWithMacros />
        <targetQueries />
        <targetQuerySequences />
        <rdss>
          <rds n="SFDC_Contact_Validation" w="Workspace" sn="SFDC_Contact_Validation" cn="SFDC_DataProvider" u="False" ss="" tn="Contact" nmo="1" f="LastModifiedDate&gt; #Diagnostic_LowerLimitTime_Contact AND LastModifiedDate&lt; #Diagnostic_UpperLimitTime_Contact AND ( __SCORE_DATE_FIELD__ &lt; #Diagnostic_RescoreThreshold_Contact OR __SCORE_DATE_FIELD__ = null ) AND @RecordCOUNT(1000)" ad="False" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="False" mgf="False" eo="2" emd="False" eo_sftp="2">
            <ts>
              <t n="Diagnostic_LowerLimitTime_Contact" t="1" qn="Q_Diagnostic_ExtractLeadsRange" cn="Diagnostic_LowerLimitTime_Contact" m="0">
                <schemas />
                <specs />
              </t>
              <t n="Diagnostic_UpperLimitTime_Contact" t="1" qn="Q_Diagnostic_ExtractLeadsRange" cn="Diagnostic_UpperLimitTime_Contact" m="0">
                <schemas />
                <specs />
              </t>
              <t n="Diagnostic_RescoreThreshold_Contact" t="1" qn="Q_Diagnostic_ExtractLeadsRange" cn="Diagnostic_RescoreThreshold_Contact" m="0">
                <schemas />
                <specs />
              </t>
            </ts>
            <mcs>
              <mc cn="CreatedDate" />
              <mc cn="Id" />
              <mc cn="LastModifiedDate" />
              <mc cn="__SCORE_DATE_FIELD__" />
              <mc cn="__SCORE_FIELD__" />
            </mcs>
          </rds>
          <rds n="SFDC_Lead_Validation" w="Workspace" sn="SFDC_Lead_Validation" cn="SFDC_DataProvider" u="False" ss="" tn="Lead" nmo="1" f="LastModifiedDate&gt; #Diagnostic_LowerLimitTime_Lead AND LastModifiedDate&lt; #Diagnostic_UpperLimitTime_Lead AND ( __SCORE_DATE_FIELD__ &lt; #Diagnostic_RescoreThreshold_Lead OR __SCORE_DATE_FIELD__  = null ) AND @RecordCOUNT(1000)" ad="False" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="False" mgf="False" eo="2" emd="False" eo_sftp="2">
            <ts>
              <t n="Diagnostic_LowerLimitTime_Lead" t="1" qn="Q_Diagnostic_ExtractLeadsRange" cn="Diagnostic_LowerLimitTime_Lead" m="0">
                <schemas />
                <specs />
              </t>
              <t n="Diagnostic_UpperLimitTime_Lead" t="1" qn="Q_Diagnostic_ExtractLeadsRange" cn="Diagnostic_UpperLimitTime_Lead" m="0">
                <schemas />
                <specs />
              </t>
              <t n="Diagnostic_RescoreThreshold_Lead" t="1" qn="Q_Diagnostic_ExtractLeadsRange" cn="Diagnostic_RescoreThreshold_Lead" m="0">
                <schemas />
                <specs />
              </t>
            </ts>
            <mcs>
              <mc cn="CreatedDate" />
              <mc cn="Id" />
              <mc cn="LastModifiedDate" />
              <mc cn="__SCORE_DATE_FIELD__" />
              <mc cn="__SCORE_FIELD__" />
            </mcs>
          </rds>
        </rdss>
        <validationExtracts />
        <ces />
        <extractQueries />
        <extractQuerySequences />
        <leafExtracts />
        <launchExtracts />
        <jobs />
        <pdmatches />
        <leadscroings />
        <lssbardins />
        <lssbardouts />
        <lds />
        <ecs />
        <gCs />
      </group>
      '''

    step1_xml = step1_xml.replace('__SCORE_FIELD__', scoreField)
    step1_xml = step1_xml.replace('__SCORE_DATE_FIELD__', scoreDateField)

    lgm.setLoadGroup(step1_xml )

    # Modified score/score-date fields of Diagnostic_LoadLeads
    diag_rdss_xml = lgm.getLoadGroupFunctionality('Diagnostic_LoadLeads_Bulk', "rdss")

    if type == 'MKTO':

      diag_rdss_xml = re.sub(r' f=\"@.*?\"', ' f="@datediff(now, month(6)) AND&#xD;&#xA;activityType in (\'New Lead\','
                                             '\'Click Link\',\'Visit Webpage\',\'Interesting Moment\',\'Open Email\','
                                             '\'Email Bounced Soft\',\'Fill Out Form\',\'Unsubscribe Email\','
                                             '\'Click Email\')"',
                             diag_rdss_xml)
    elif type == 'ELQ':
      diag_rdss_xml = re.sub(r' f=\"@.*?\"',
                             ' f="@datediff(now, month(6)) AND (__SCORE_DATE_FIELD__ &lt; '
                             '#Diagnostic_RescoreThreshold OR __SCORE_FIELD__ = 0 )"',
                             diag_rdss_xml)
      diag_rdss_xml.replace('__SCORE_DATE_FIELD__', scoreDateField)
      diag_rdss_xml.replace('__SCORE_FIELD__', scoreField)

    elif type == 'SFDC':
      diag_rdss_xml = re.sub(r'<rds n=\"SFDC_Contact_Validation\".*f=\"@.*?\"',
                             ' f="@datediff(now, month(6)) AND ( __CONTACT_SCORE_DATE_FIELD__ &lt; '
                             '#Diagnostic_RescoreThreshold_Contact OR __CONTACT_SCORE_FIELD__ = null )"',
                             diag_rdss_xml)
      diag_rdss_xml.replace('__CONTACT_SCORE_DATE_FIELD__', sfdcContactScoreDateField)
      diag_rdss_xml.replace('__CONTACT_SCORE_FIELD__', sfdcContactScoreField)
      diag_rdss_xml = re.sub(r'<rds n=\"SFDC_Lead_Validation\".*f=\"@.*?\"',
                             ' f="@datediff(now, month(6)) AND ( __LEAD_SCORE_DATE_FIELD__ &lt; '
                             '#Diagnostic_RescoreThreshold_Contact OR __LEAD_SCORE_FIELD__ = null )"',
                             diag_rdss_xml)
      diag_rdss_xml.replace('__LEAD_SCORE_DATE_FIELD__', sfdcLeadScoreDateField)
      diag_rdss_xml.replace('__LEAD_SCORE_FIELD__', sfdcLeadScoreField)

    lgm.setLoadGroupFunctionality('Diagnostic_LoadLeads_Bulk', diag_rdss_xml)


def Usage( cmd, exit_code ):
    path = ''
    i = cmd.rfind('\\')
    if( i != -1 ):
        path = cmd[:i]
        cmd = cmd[i+1:]
    
    print ''
    print 'Usage: {0} <tenant>'.format( cmd )
    print ''
    
    exit( exit_code )


if __name__ == "__main__":

    if len(sys.argv) == 1:
        Usage( sys.argv[0], 0 )
    
    if len(sys.argv) != 2:
        Usage( sys.argv[0], 1 )

    tenantName = sys.argv[1]
    
MissingLeadsReport( tenantName )
