#!/bin/bash
chmod 755 /tmp/lib
hadoop fs -mkdir /lib
runuser -l yarn -c 'hadoop fs -copyFromLocal /tmp/lib/* /lib'

chmod 755 /tmp/app/dataplatform/scripts
chmod 755 /tmp/app/dataplatform/scripts/algorithm
hadoop fs -mkdir /app
runuser -l yarn -c 'hadoop fs -copyFromLocal /tmp/app/dataplatform /app/dataplatform'

# clean up
rm -rf /tmp/lib
rm -rf /tmp/app
