#!/bin/bash
chmod 755 /tmp/app/dataplatform/eai
chmod 755 /tmp/app/dataplatform/scripts
chmod 755 /tmp/app/dataplatform/scripts/algorithm
chmod 755 /tmp/app/playmaker/evmodel
rm /tmp/app/dataplatform/scripts/*.pyc
rm /tmp/app/dataplatform/scripts/*.pyo
rm /tmp/app/dataplatform/scripts/algorithm/*.pyc
rm /tmp/app/dataplatform/scripts/algorithm/*.pyo
rm /tmp/app/playmaker/evmodel/*.pyc
rm /tmp/app/playmaker/evmodel/*.pyo
hadoop fs -mkdir /app
runuser -l yarn -c 'hadoop fs -copyFromLocal /tmp/app/dataplatform /app/dataplatform'
runuser -l yarn -c 'hadoop fs -copyFromLocal /tmp/app/playmaker /app/playmaker'
rm -rf /tmp/app


