#!/bin/bash
chmod 755 /tmp/app/dataplatform/scripts
chmod 755 /tmp/app/dataplatform/scripts/algorithm
rm /tmp/app/dataplatform/scripts/*.pyc
rm /tmp/app/dataplatform/scripts/*.pyo
rm /tmp/app/dataplatform/scripts/algorithm/*.pyc
rm /tmp/app/dataplatform/scripts/algorithm/*.pyo
runuser -l smeng -c '/home/LATTICE/smeng/tools/hadoop-2.4.0/bin/hadoop fs -mkdir /app'
runuser -l smeng -c '/home/LATTICE/smeng/tools/hadoop-2.4.0/bin/hadoop fs -copyFromLocal /tmp/app/dataplatform /app/dataplatform'
rm -rf /tmp/app