#!/bin/bash
echo "getting environment information"
echo $LE_ENVIRONMENT
echo $LE_STACK
echo $STACK_PROFILE
echo $USE_AWS

JARFILE=`ls /tmp/app/dataplatform/lib/le-dataplatform*-shaded.jar`
VERSION=`echo $JARFILE | cut -d \- -f 3`
SNAPSHOT=`echo $JARFILE | cut -d \- -f 4`

if test $SNAPSHOT = "SNAPSHOT"
    then
        VERSION=$VERSION-"SNAPSHOT"
fi

if [ ! -z "$LE_STACK" -a "$LE_STACK" != " " ]; then
    VERSION=${LE_STACK}/${VERSION}
fi
echo $VERSION

chmod 755 /tmp/app/dataplatform/scripts
chmod 755 /tmp/app/dataplatform/lib
chmod 755 /tmp/app/dataplatform/scripts/algorithm
chmod 755 /tmp/app/playmaker/evmodel
chmod 755 /tmp/app/scoring/scripts
chmod 755 /tmp/app/scoring/lib

rm /tmp/app/dataplatform/scripts/*.pyc
rm /tmp/app/dataplatform/scripts/*.pyo
rm /tmp/app/dataplatform/scripts/algorithm/*.pyc
rm /tmp/app/dataplatform/scripts/algorithm/*.pyo
rm /tmp/app/playmaker/evmodel/*.pyc
rm /tmp/app/playmaker/evmodel/*.pyo
rm /tmp/app/scoring/scripts/*.pyc
rm /tmp/app/scoring/scripts/*.pyo

su -l yarn -c "hdfs dfs -copyFromLocal -f /tmp/app/dataplatform/scripts /app/$VERSION/dataplatform"
su -l yarn -c "hdfs dfs -copyFromLocal -f /tmp/app/dataplatform/lib /app/$VERSION/dataplatform"
su -l yarn -c "hdfs dfs -copyFromLocal -f /tmp/app/playmaker/* /app/$VERSION/playmaker"
su -l yarn -c "hdfs dfs -copyFromLocal -f /tmp/app/scoring/scripts /app/$VERSION/scoring"
su -l yarn -c "hdfs dfs -copyFromLocal -f /tmp/app/scoring/lib /app/$VERSION/scoring"

for microservice in 'eai' 'dataflowapi' 'workflowapi' 'sqoop'
do
    su -l yarn -c "hdfs dfs -copyFromLocal -f /tmp/app/dataplatform/le-$microservice*-shaded.jar /app/$VERSION/$microservice/lib"
done
su -l yarn -c "hdfs dfs -copyFromLocal -f /tmp/app/dataplatform/le-datacloud-yarn*-shaded.jar /app/$VERSION/datacloud/lib"
rm -rf /tmp/app/dataplatform
rm -rf /tmp/app/playmaker
rm -rf /tmp/app/scoring
