#!/bin/bash

RPMFILE=`ls /tmp/le-dataplatform-hdfs-*.rpm`
VERSION=`echo $RPMFILE | cut -d \- -f 4`
SNAPSHOT=`echo $RPMFILE | cut -d \- -f 5`

if [[ $SNAPSHOT = SNAPSHOT* ]]
    then
        VERSION=$VERSION-"SNAPSHOT"
fi

rm -rf /tmp/app/dataplatform
rm -rf /tmp/app/playmaker
rm -rf /tmp/datascientist

hdfs dfs -rm -f -r /app/$VERSION/dataflowapi || true
hdfs dfs -rm -f -r /app/$VERSION/dataplatform || true
hdfs dfs -rm -f -r /app/$VERSION/db || true
hdfs dfs -rm -f -r /app/$VERSION/eai || true
hdfs dfs -rm -f -r /app/$VERSION/playmaker || true
hdfs dfs -rm -f -r /app/$VERSION/security || true
hdfs dfs -rm -f -r /app/$VERSION/workflowapi || true
hdfs dfs -rm -f -r /datascientist

hdfs dfs -mkdir -p /app/$VERSION/dataflowapi/lib
hdfs dfs -mkdir -p /app/$VERSION/dataplatform
hdfs dfs -mkdir -p /app/$VERSION/dataplatform/lib
hdfs dfs -mkdir -p /app/$VERSION/db
hdfs dfs -mkdir -p /app/$VERSION/eai/lib
hdfs dfs -mkdir -p /app/$VERSION/playmaker
hdfs dfs -mkdir -p /app/$VERSION/security
hdfs dfs -mkdir -p /app/$VERSION/workflowapi/lib
hdfs dfs -mkdir -p /datascientist
