#!/bin/bash

echo "getting environment information"
echo $LE_ENVIRONMENT
echo $LE_STACK
echo $STACK_PROFILE
echo $USE_AWS

if [ "${USE_AWS}" = "true"  ]; then
    LE_STACK="${LE_STACK}_aws"
fi
echo $LE_STACK

RPMFILE=`ls /tmp/le-dataplatform-hdfs-rpm-*.rpm`
VERSION=`echo $RPMFILE | cut -d \- -f 5`
SNAPSHOT=`echo $RPMFILE | cut -d \- -f 6`

if [[ $SNAPSHOT = SNAPSHOT* ]]
    then
        VERSION=$VERSION-"SNAPSHOT"
fi

rm -rf /tmp/app/dataplatform
rm -rf /tmp/app/playmaker

if [ ! -z "$LE_STACK" -a "$LE_STACK" != " " ]; then
    VERSION=${LE_STACK}/${VERSION}
fi

echo $VERSION

hdfs dfs -rm -f -r /app/$VERSION/dataflowapi || true
hdfs dfs -rm -f -r /app/$VERSION/dataplatform || true
hdfs dfs -rm -f -r /app/$VERSION/eai || true
hdfs dfs -rm -f -r /app/$VERSION/playmaker || true
hdfs dfs -rm -f -r /app/$VERSION/workflowapi || true
hdfs dfs -rm -f -r /app/$VERSION/datacloud || true
hdfs dfs -rm -f -r /app/$VERSION/sqoop || true

hdfs dfs -mkdir -p /app/$VERSION/dataflowapi/lib
hdfs dfs -mkdir -p /app/$VERSION/dataplatform/lib
hdfs dfs -mkdir -p /app/$VERSION/eai/lib
hdfs dfs -mkdir -p /app/$VERSION/playmaker
hdfs dfs -mkdir -p /app/$VERSION/workflowapi/lib
hdfs dfs -mkdir -p /app/$VERSION/datacloud/lib
hdfs dfs -mkdir -p /app/$VERSION/sqoop/lib