CREATE PROCEDURE `UpdateDataFeedTables`()
  BEGIN
    CREATE TABLE `DATAFEED_EXECUTION` (
      `PID`         BIGINT       NOT NULL AUTO_INCREMENT UNIQUE,
      `STATUS`      VARCHAR(255) NOT NULL,
      `WORKFLOW_ID` BIGINT,
      FK_FEED_ID    BIGINT       NOT NULL,
      PRIMARY KEY (`PID`)
    )
      ENGINE = InnoDB;
    CREATE TABLE `DATAFEED_IMPORT` (
      `PID`             BIGINT        NOT NULL AUTO_INCREMENT UNIQUE,
      `ENTITY`          VARCHAR(255)  NOT NULL,
      `FEED_TYPE`       VARCHAR(255),
      `SOURCE`          VARCHAR(255)  NOT NULL,
      `SOURCE_CONFIG`   VARCHAR(1000) NOT NULL,
      `START_TIME`      DATETIME      NOT NULL,
      `FK_FEED_EXEC_ID` BIGINT        NOT NULL,
      FK_DATA_ID        BIGINT        NOT NULL,
      PRIMARY KEY (`PID`),
      UNIQUE (`SOURCE`, `ENTITY`, `FEED_TYPE`, `FK_FEED_EXEC_ID`)
    )
      ENGINE = InnoDB;
    CREATE TABLE `DATAFEED_TASK_TABLE` (
      `PID`         BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
      `FK_TASK_ID`  BIGINT NOT NULL,
      `FK_TABLE_ID` BIGINT NOT NULL,
      PRIMARY KEY (`PID`),
      UNIQUE (`FK_TASK_ID`, `FK_TABLE_ID`)
    )
      ENGINE = InnoDB;
    CREATE TABLE `DATAFEED_TASK` (
      `PID`           BIGINT        NOT NULL AUTO_INCREMENT UNIQUE,
      `ACTIVE_JOB`    VARCHAR(255)  NOT NULL,
      `ENTITY`        VARCHAR(255)  NOT NULL,
      `FEED_TYPE`     VARCHAR(255),
      `LAST_IMPORTED` DATETIME      NOT NULL,
      `SOURCE`        VARCHAR(255)  NOT NULL,
      `SOURCE_CONFIG` VARCHAR(1000) NOT NULL,
      `START_TIME`    DATETIME      NOT NULL,
      `STATUS`        VARCHAR(255)  NOT NULL,
      `FK_FEED_ID`    BIGINT        NOT NULL,
      FK_DATA_ID      BIGINT,
      FK_TEMPLATE_ID  BIGINT        NOT NULL,
      PRIMARY KEY (`PID`),
      UNIQUE (`SOURCE`, `ENTITY`, `FEED_TYPE`, `FK_FEED_ID`)
    )
      ENGINE = InnoDB;
    CREATE TABLE `DATAFEED` (
      `PID`              BIGINT       NOT NULL AUTO_INCREMENT UNIQUE,
      `ACTIVE_EXECUTION` BIGINT       NOT NULL,
      `NAME`             VARCHAR(255) NOT NULL,
      `STATUS`           VARCHAR(255) NOT NULL,
      `TENANT_ID`        BIGINT       NOT NULL,
      FK_COLLECTION_ID   BIGINT       NOT NULL,
      FK_TENANT_ID       BIGINT       NOT NULL,
      PRIMARY KEY (`PID`),
      UNIQUE (`TENANT_ID`, `NAME`)
    )
      ENGINE = InnoDB;

    ALTER TABLE `DATAFEED_EXECUTION`
      ADD INDEX FK3E5D3BC1679FF377 (FK_FEED_ID),
      ADD CONSTRAINT FK3E5D3BC1679FF377 FOREIGN KEY (FK_FEED_ID) REFERENCES `DATAFEED` (`PID`)
      ON DELETE CASCADE;
    ALTER TABLE `DATAFEED_IMPORT`
      ADD INDEX FKADAC237C56FF4425 (`FK_FEED_EXEC_ID`),
      ADD CONSTRAINT FKADAC237C56FF4425 FOREIGN KEY (`FK_FEED_EXEC_ID`) REFERENCES `DATAFEED_EXECUTION` (`PID`)
      ON DELETE CASCADE;
    ALTER TABLE `DATAFEED_IMPORT`
      ADD INDEX FKADAC237C525FEA17 (FK_DATA_ID),
      ADD CONSTRAINT FKADAC237C525FEA17 FOREIGN KEY (FK_DATA_ID) REFERENCES `METADATA_TABLE` (`PID`)
      ON DELETE CASCADE;
    ALTER TABLE `DATAFEED_TASK_TABLE`
      ADD INDEX FKF200D4CBD3C51D55 (`FK_TASK_ID`),
      ADD CONSTRAINT FKF200D4CBD3C51D55 FOREIGN KEY (`FK_TASK_ID`) REFERENCES `DATAFEED_TASK` (`PID`);
    ALTER TABLE `DATAFEED_TASK_TABLE`
      ADD INDEX FKF200D4CB68A6FB47 (`FK_TABLE_ID`),
      ADD CONSTRAINT FKF200D4CB68A6FB47 FOREIGN KEY (`FK_TABLE_ID`) REFERENCES `METADATA_TABLE` (`PID`);
    ALTER TABLE `DATAFEED_TASK`
      ADD INDEX FK7679F31C80AFF377 (`FK_FEED_ID`),
      ADD CONSTRAINT FK7679F31C80AFF377 FOREIGN KEY (`FK_FEED_ID`) REFERENCES `DATAFEED` (`PID`)
      ON DELETE CASCADE;
    ALTER TABLE `DATAFEED_TASK`
      ADD INDEX FK7679F31C525FEA17 (FK_DATA_ID),
      ADD CONSTRAINT FK7679F31C525FEA17 FOREIGN KEY (FK_DATA_ID) REFERENCES `METADATA_TABLE` (`PID`)
      ON DELETE CASCADE;
    ALTER TABLE `DATAFEED_TASK`
      ADD INDEX FK7679F31C15766847 (FK_TEMPLATE_ID),
      ADD CONSTRAINT FK7679F31C15766847 FOREIGN KEY (FK_TEMPLATE_ID) REFERENCES `METADATA_TABLE` (`PID`)
      ON DELETE CASCADE;
    CREATE INDEX IX_FEED_NAME
      ON `DATAFEED` (`NAME`);
    ALTER TABLE `DATAFEED`
      ADD INDEX FK9950E0487BF7C1B7 (FK_COLLECTION_ID),
      ADD CONSTRAINT FK9950E0487BF7C1B7 FOREIGN KEY (FK_COLLECTION_ID) REFERENCES `METADATA_DATA_COLLECTION` (`PID`)
      ON DELETE CASCADE;
    ALTER TABLE `DATAFEED`
      ADD INDEX FK9950E04836865BC (FK_TENANT_ID),
      ADD CONSTRAINT FK9950E04836865BC FOREIGN KEY (FK_TENANT_ID) REFERENCES `TENANT` (`TENANT_PID`)
      ON DELETE CASCADE;
  END;
//
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `UpdateModelNotes`()
  BEGIN
    CREATE TABLE `MODEL_NOTES` (
      `PID`                         BIGINT       NOT NULL AUTO_INCREMENT UNIQUE,
      `CREATED_BY_USER`             VARCHAR(255),
      `CREATION_TIMESTAMP`          BIGINT,
      `ID`                          VARCHAR(255) NOT NULL UNIQUE,
      `LAST_MODIFICATION_TIMESTAMP` BIGINT,
      `LAST_MODIFIED_BY_USER`       VARCHAR(255),
      `NOTES_CONTENTS`              VARCHAR(2048),
      `ORIGIN`                      VARCHAR(255),
      `PARENT_MODEL_ID`             VARCHAR(255),
      MODEL_ID                      BIGINT       NOT NULL,
      PRIMARY KEY (`PID`)
    )
      ENGINE = InnoDB;
    CREATE INDEX MODEL_NOTES_ID_IDX
      ON `MODEL_NOTES` (`ID`);
    ALTER TABLE `MODEL_NOTES`
      ADD INDEX FKE83891EB815935F7 (MODEL_ID),
      ADD CONSTRAINT FKE83891EB815935F7 FOREIGN KEY (MODEL_ID) REFERENCES `MODEL_SUMMARY` (`PID`)
      ON DELETE CASCADE;
  END;
//
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `UpdateSchema`()
  BEGIN
    START TRANSACTION;
    CALL `UpdatePLay`();
    CALL `UpdateMetadata`();
    CALL `UpdateDataFeedTables`();
    CALL `UpdateModelNotes`();
    COMMIT;
  END;
//
DELIMITER ;

CALL `UpdateSchema`();