package com.latticeengines.domain.exposed.datacloud.match;

public enum EntityMatchType {
    UNKNOWN,
    ACCOUNTID,
    CONTACTID,
    DOMAIN_COUNTRY,
    DUNS,
    EMAIL,
    EMAIL_ACCOUNTID,
    LDC_CACHED_DUNS_GUIDE_VALIDATE,
    LDC_CACHED_DUNS_VALIDATE,
    LDC_DOMAIN,
    LDC_DOMAIN_COUNTRY,
    LDC_DOMAIN_COUNTRY_STATE,
    LDC_DOMAIN_COUNTRY_ZIPCODE,
    LDC_DUNS,
    LDC_DUNS_DOMAIN,
    LDC_DUNS_GUIDE_VALIDATE,
    LDC_DUNS_VALIDATE,
    LDC_LOCATION_CACHED_DUNS,
    LDC_LOCATION_DUNS,
    LDC_MATCH,
    NAME_COUNTRY,
    NAME_PHONE,
    NAME_PHONE_ACCOUNTID,
    NO_MATCH,
    SYSTEMID
}
