#!/bin/bash
rm -rf /opt/jetty/webapps/le-admin-*.war
rm -rf /opt/jetty/webapps/le-pls-*.war
rm -rf /etc/ledp/admin.properties
rm -rf /opt/jetty/bin/jetty.sh
rm -rf /home/yarn/.bashrc

rm -rf /var/www/le-admin
mkdir -p /var/www/le-admin
chown -R apache:apache /var/www/le-admin

adduser yarn
groupadd yarn
mkdir -p /var/log/ledp
mkdir -p /home/yarn/logs
chmod -R 755 /var/log/ledp
chmod -R 755 /home/yarn/logs
chown -R yarn:yarn /var/log/ledp
chown -R yarn:yarn /home/yarn/logs
chown -R yarn:yarn /opt/jetty/logs