#!/bin/bash -x
source /etc/profile
echo "getting environment information"
echo $ENV_TYPE
echo $CATALINA_HOME
cd /tmp/webapps/admin

JARFILE=`ls le-admin-*.war`
VERSION=`echo $JARFILE | cut -d \- -f 3`
SNAPSHOT=`echo $JARFILE | cut -d \- -f 4`

if test $SNAPSHOT = "SNAPSHOT"
    then
        VERSION=$VERSION-"SNAPSHOT"
fi
echo $VERSION

echo "copying files"
cp /tmp/webapps/admin/le-admin-*.war $CATALINA_HOME/webapps/admin/ROOT.war
cp /etc/ledp/admin/$ENV_TYPE/*.properties /etc/ledp/
cp /etc/ledp/admin/$ENV_TYPE/laca-ldap.dev.lattice.local.jks /etc/ledp/
cp /etc/ledp/admin/$ENV_TYPE/404.html /etc/ledp/

echo "cleaning up"
rm -rf /tmp/webapps/admin/le-admin-*.war
rm -rf /etc/ledp/admin
rm -rf /home/yarn/admin
rm -rf /home/yarn/logs/*

echo "finishing"
chown -R root:tomcat $CATALINA_HOME/webapps
ls $CATALINA_HOME/webapps/admin/*.war
