#!/bin/bash
source /etc/profile
rm -rf $CATALINA_HOME/webapps/admin/*.war
rm -rf /tmp/webapps/admin/le-admin-*.war
rm -rf /etc/ledp/admin.properties
rm -rf /etc/ledp/db.properties
rm -rf /etc/ledp/security.properties
rm -rf /etc/ledp/camille.properties
rm -rf /etc/ledp/admin
rm -rf /etc/httpd/conf.d/admin
rm -rf /home/yarn/admin
adduser yarn
groupadd yarn
groupadd tomcat
mkdir -p /var/log/ledp
mkdir -p /home/yarn/logs
chmod -R 755 /var/log/ledp
chmod -R 755 /home/yarn/logs
chown -R yarn:yarn /var/log/ledp
chown -R yarn:yarn /home/yarn/logs
