USE [PLS_MultiTenant]

ALTER TABLE [METADATA_TABLE] ADD [NAMESPACE] NVARCHAR(255);

CREATE TABLE [METADATA_TABLE_TAG] (
  [PID]       BIGINT IDENTITY NOT NULL UNIQUE, 
  [NAME]      NVARCHAR(255)   NOT NULL, 
  [TENANT_ID] BIGINT          NOT NULL, 
  FK_TABLE_ID BIGINT          NOT NULL, 
  PRIMARY KEY ([PID]));

ALTER TABLE [METADATA_TABLE_TAG]
  ADD CONSTRAINT FK6BACA6595FC50F27 FOREIGN KEY (FK_TABLE_ID) REFERENCES [METADATA_TABLE] ON DELETE CASCADE;

CREATE NONCLUSTERED INDEX FK6BACA6595FC50F27 ON [METADATA_TABLE_TAG] (FK_TABLE_ID);

CREATE TABLE [METADATA_STORAGE] (
  [NAME]          NVARCHAR(31)    NOT NULL, 
  [PID]           BIGINT IDENTITY NOT NULL UNIQUE, 
  [TABLE_NAME]    NVARCHAR(255)   NOT NULL, 
  [DATABASE_NAME] INT, 
  FK_TABLE_ID     BIGINT          NOT NULL, 
  PRIMARY KEY ([PID]));

ALTER TABLE [METADATA_STORAGE] 
  ADD CONSTRAINT FKAAD4414B5FC50F27 FOREIGN KEY (FK_TABLE_ID) REFERENCES [METADATA_TABLE] ON DELETE CASCADE;
  
CREATE NONCLUSTERED INDEX FKAAD4414B5FC50F27 ON [METADATA_STORAGE] (FK_TABLE_ID);

INSERT INTO [METADATA_STORAGE] (NAME, TABLE_NAME, FK_TABLE_ID)
SELECT 'HDFS', NAME, PID FROM [METADATA_TABLE];

GO

