#!/bin/bash
echo "postinstalling now"

cd /opt
cp -rf jetty2-tmp/* jetty2
chown -R yarn:yarn jetty2
rm -rf jetty2-tmp
cd /etc/init.d
ln -s /opt/jetty2/bin/jetty.sh jetty2
chkconfig --add jetty2
chkconfig --level 345 jetty2 on

