use GlobalAuthentication;
alter table `GlobalAuthentication` add index FK5CD04D1B5073CB39 (User_ID), add constraint FK5CD04D1B5073CB39 foreign key (User_ID) references `GlobalUser` (`GlobalUser_ID`) on delete cascade;
create index IX_Ticket on `GlobalTicket` (`Ticket`);
alter table `GlobalUserTenantRight` add index FK3EDAC847D90CF19 (Tenant_ID), add constraint FK3EDAC847D90CF19 foreign key (Tenant_ID) references `GlobalTenant` (`GlobalTenant_ID`) on delete cascade;
alter table `GlobalUserTenantRight` add index FK3EDAC845073CB39 (User_ID), add constraint FK3EDAC845073CB39 foreign key (User_ID) references `GlobalUser` (`GlobalUser_ID`) on delete cascade;
create index IX_ENTITY_ID on `SECURITY_IDENTITY_PROVIDER` (`ENTITY_ID`);
alter table `SECURITY_IDENTITY_PROVIDER` add index FK1E96BD137D90CF19 (TENANT_ID), add constraint FK1E96BD137D90CF19 foreign key (TENANT_ID) references `GlobalTenant` (`GlobalTenant_ID`) on delete cascade;

use PLS_MultiTenant;

alter table `ALGORITHM` add index FKB388C44F5FB2DB1E (FK_MODEL_DEF_ID), add constraint FKB388C44F5FB2DB1E foreign key (FK_MODEL_DEF_ID) references `MODEL_DEFINITION` (`PID`);
create index IX_TENANT_ATTRIBUTENAME_USECASE on `ATTRIBUTE_CUSTOMIZATION_PROPERTY` (`ATTRIBUTE_NAME`, FK_TENANT_ID, `USE_CASE`);
alter table `ATTRIBUTE_CUSTOMIZATION_PROPERTY` add index FKBFFD520436865BC (FK_TENANT_ID), add constraint FKBFFD520436865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`) on delete cascade;
alter table `BUCKET_METADATA` add index FK398165E4815935F7 (MODEL_ID), add constraint FK398165E4815935F7 foreign key (MODEL_ID) references `MODEL_SUMMARY` (`PID`) on delete cascade;
create index IX_TENANT_ATTRIBUTECATEGORY_USECASE on `CATEGORY_CUSTOMIZATION_PROPERTY` (FK_TENANT_ID, `USE_CASE`);
alter table `CATEGORY_CUSTOMIZATION_PROPERTY` add index FK60EAD4236865BC (FK_TENANT_ID), add constraint FK60EAD4236865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`) on delete cascade;
alter table `DATAFLOW_JOB` add index FK4E6B9EB6E88B2327 (`JOB_PID`), add constraint FK4E6B9EB6E88B2327 foreign key (`JOB_PID`) references `JOB` (`JOB_PID`);
alter table `EAI_JOB` add index FKB529FB8BE88B2327 (`JOB_PID`), add constraint FKB529FB8BE88B2327 foreign key (`JOB_PID`) references `JOB` (`JOB_PID`);
alter table `ENRICHMENT` add index FKD6DBEFE336865BC (FK_TENANT_ID), add constraint FKD6DBEFE336865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`) on delete cascade;
create index KEY_VALUE_TENANT_ID_IDX on `KEY_VALUE` (`TENANT_ID`);
alter table `MARKETO_CREDENTIAL` add index FKE7A7408336865BC (FK_TENANT_ID), add constraint FKE7A7408336865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`) on delete cascade;
alter table `MARKETO_CREDENTIAL` add index FKE7A74083AC24AAE9 (FK_ENRICHMENT_ID), add constraint FKE7A74083AC24AAE9 foreign key (FK_ENRICHMENT_ID) references `ENRICHMENT` (`PID`) on delete cascade;
alter table `MARKETO_MATCH_FIELD` add index FKA86077146C0308E3 (ENRICHMENT_ID), add constraint FKA86077146C0308E3 foreign key (ENRICHMENT_ID) references `ENRICHMENT` (`PID`) on delete cascade;
alter table `MARKETO_MATCH_FIELD` add index FKA860771436865BC (FK_TENANT_ID), add constraint FKA860771436865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`) on delete cascade;
alter table `METADATA_ARTIFACT` add index FK1DE0E2A7AFF7AD (FK_MODULE_ID), add constraint FK1DE0E2A7AFF7AD foreign key (FK_MODULE_ID) references `METADATA_MODULE` (`PID`) on delete cascade;
alter table `METADATA_ATTRIBUTE` add index FKE2E7316C5FC50F27 (FK_TABLE_ID), add constraint FKE2E7316C5FC50F27 foreign key (FK_TABLE_ID) references `METADATA_TABLE` (`PID`) on delete cascade;
create index DATA_COLLECTION_PROPERTY_IDX on `METADATA_DATA_COLLECTION_PROPERTY` (`PROPERTY`);
alter table `METADATA_DATA_COLLECTION_PROPERTY` add index FKA6E03D51D089E196 (FK_DATA_COLLECTION_ID), add constraint FKA6E03D51D089E196 foreign key (FK_DATA_COLLECTION_ID) references `METADATA_DATA_COLLECTION` (`PID`) on delete cascade;
alter table `METADATA_DATA_COLLECTION` add index FKF69DFD4336865BC (FK_TENANT_ID), add constraint FKF69DFD4336865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`) on delete cascade;
alter table `METADATA_EXTRACT` add index FKCD56DB515FC50F27 (FK_TABLE_ID), add constraint FKCD56DB515FC50F27 foreign key (FK_TABLE_ID) references `METADATA_TABLE` (`PID`) on delete cascade;
alter table `METADATA_HIERARCHY` add index FK603219055FC50F27 (FK_TABLE_ID), add constraint FK603219055FC50F27 foreign key (FK_TABLE_ID) references `METADATA_TABLE` (`PID`) on delete cascade;
alter table `METADATA_LASTMODIFIED_KEY` add index FK56B5EC6F5FC50F27 (FK_TABLE_ID), add constraint FK56B5EC6F5FC50F27 foreign key (FK_TABLE_ID) references `METADATA_TABLE` (`PID`) on delete cascade;
alter table `METADATA_LEVEL` add index FK41081254F80C45B8 (FK_HIERARCHY_ID), add constraint FK41081254F80C45B8 foreign key (FK_HIERARCHY_ID) references `METADATA_HIERARCHY` (`PID`) on delete cascade;
alter table `METADATA_MODULE` add index FKE234097C36865BC (FK_TENANT_ID), add constraint FKE234097C36865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`) on delete cascade;
alter table `METADATA_PRIMARY_KEY` add index FKA4B6A5525FC50F27 (FK_TABLE_ID), add constraint FKA4B6A5525FC50F27 foreign key (FK_TABLE_ID) references `METADATA_TABLE` (`PID`) on delete cascade;
create index SEGMENT_PROPERTY_IDX on `METADATA_SEGMENT_PROPERTY` (`PROPERTY`);
alter table `METADATA_SEGMENT_PROPERTY` add index FKF9BE749179DE23EE (METADATA_SEGMENT_ID), add constraint FKF9BE749179DE23EE foreign key (METADATA_SEGMENT_ID) references `METADATA_SEGMENT` (`PID`) on delete cascade;
alter table `METADATA_SEGMENT` add index FK90C89E03D089E196 (FK_DATA_COLLECTION_ID), add constraint FK90C89E03D089E196 foreign key (FK_DATA_COLLECTION_ID) references `METADATA_DATA_COLLECTION` (`PID`) on delete cascade;
alter table `METADATA_STORAGE` add index FKAAD4414B5FC50F27 (FK_TABLE_ID), add constraint FKAAD4414B5FC50F27 foreign key (FK_TABLE_ID) references `METADATA_TABLE` (`PID`) on delete cascade;
alter table `METADATA_TABLE_RELATIONSHIP` add index FKE87FC63961584D17 (FK_SOURCE_TABLE_ID), add constraint FKE87FC63961584D17 foreign key (FK_SOURCE_TABLE_ID) references `METADATA_TABLE` (`PID`) on delete cascade;
alter table `METADATA_TABLE_TAG` add index FK6BACA6595FC50F27 (FK_TABLE_ID), add constraint FK6BACA6595FC50F27 foreign key (FK_TABLE_ID) references `METADATA_TABLE` (`PID`) on delete cascade;
alter table `METADATA_TABLE` add index FK4176B29E36865BC (FK_TENANT_ID), add constraint FK4176B29E36865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`) on delete cascade;
create index IX_EXTRACT_IDENTIFIER on `METADATA_VDB_EXTRACT` (`EXTRACT_IDENTIFIER`);
alter table `MODELING_JOB` add index FK92A4EA77AC061AB1 (FK_MODEL_ID), add constraint FK92A4EA77AC061AB1 foreign key (FK_MODEL_ID) references `MODEL` (`MODEL_PID`);
alter table `MODELING_JOB` add index FK92A4EA77E88B2327 (`JOB_PID`), add constraint FK92A4EA77E88B2327 foreign key (`JOB_PID`) references `JOB` (`JOB_PID`);
alter table `MODELQUALITY_ALGORITHM_PROPERTY_DEF` add index FKEB0CC514BF79A5CE (FK_ALGORITHM_ID), add constraint FKEB0CC514BF79A5CE foreign key (FK_ALGORITHM_ID) references `MODELQUALITY_ALGORITHM` (`PID`) on delete cascade;
alter table `MODELQUALITY_ALGORITHM_PROPERTY_VALUE` add index FK5BEBC6C02A32AA49 (FK_ALGORITHM_PROPDEF_ID), add constraint FK5BEBC6C02A32AA49 foreign key (FK_ALGORITHM_PROPDEF_ID) references `MODELQUALITY_ALGORITHM_PROPERTY_DEF` (`PID`) on delete cascade;
alter table `MODELQUALITY_ANALYTIC_PIPELINE` add index FK43F059CBBF79A5CE (FK_ALGORITHM_ID), add constraint FK43F059CBBF79A5CE foreign key (FK_ALGORITHM_ID) references `MODELQUALITY_ALGORITHM` (`PID`) on delete cascade;
alter table `MODELQUALITY_ANALYTIC_PIPELINE` add index FK43F059CBB84759E6 (FK_DATAFLOW_ID), add constraint FK43F059CBB84759E6 foreign key (FK_DATAFLOW_ID) references `MODELQUALITY_DATAFLOW` (`PID`) on delete cascade;
alter table `MODELQUALITY_ANALYTIC_PIPELINE` add index FK43F059CB5B24F986 (FK_PIPELINE_ID), add constraint FK43F059CB5B24F986 foreign key (FK_PIPELINE_ID) references `MODELQUALITY_PIPELINE` (`PID`) on delete cascade;
alter table `MODELQUALITY_ANALYTIC_PIPELINE` add index FK43F059CBFA8881C6 (FK_PROPDATA_ID), add constraint FK43F059CBFA8881C6 foreign key (FK_PROPDATA_ID) references `MODELQUALITY_PROPDATA` (`PID`) on delete cascade;
alter table `MODELQUALITY_ANALYTIC_PIPELINE` add index FK43F059CBBD563766 (FK_SAMPLING_ID), add constraint FK43F059CBBD563766 foreign key (FK_SAMPLING_ID) references `MODELQUALITY_SAMPLING` (`PID`) on delete cascade;
alter table `MODELQUALITY_AP_TEST_AP_PIPELINE` add index FK6830CA8C9E70019D (AP_PIPELINE_ID), add constraint FK6830CA8C9E70019D foreign key (AP_PIPELINE_ID) references `MODELQUALITY_ANALYTIC_PIPELINE` (`PID`);
alter table `MODELQUALITY_AP_TEST_AP_PIPELINE` add index FK6830CA8C1ECB851D (AP_TEST_ID), add constraint FK6830CA8C1ECB851D foreign key (AP_TEST_ID) references `MODELQUALITY_ANALYTIC_TEST` (`PID`);
alter table `MODELQUALITY_AP_TEST_DATASET` add index FK86EE7F32A3AF4654 (DATASET_ID), add constraint FK86EE7F32A3AF4654 foreign key (DATASET_ID) references `MODELQUALITY_DATASET` (`PID`);
alter table `MODELQUALITY_AP_TEST_DATASET` add index FK86EE7F321ECB851D (AP_TEST_ID), add constraint FK86EE7F321ECB851D foreign key (AP_TEST_ID) references `MODELQUALITY_ANALYTIC_TEST` (`PID`);
alter table `MODELQUALITY_MODELRUN` add index FK3A8D332B2F8BA35 (FK_ANALYTIC_PIPELINE_ID), add constraint FK3A8D332B2F8BA35 foreign key (FK_ANALYTIC_PIPELINE_ID) references `MODELQUALITY_ANALYTIC_PIPELINE` (`PID`) on delete cascade;
alter table `MODELQUALITY_MODELRUN` add index FK3A8D332B2402520E (FK_DATASET_ID), add constraint FK3A8D332B2402520E foreign key (FK_DATASET_ID) references `MODELQUALITY_DATASET` (`PID`) on delete cascade;
alter table `MODELQUALITY_PIPELINE_PIPELINE_STEP` add index FK2FAFF015D1168E00 (PIPELINE_ID), add constraint FK2FAFF015D1168E00 foreign key (PIPELINE_ID) references `MODELQUALITY_PIPELINE` (`PID`);
alter table `MODELQUALITY_PIPELINE_PIPELINE_STEP` add index FK2FAFF0151B797FE5 (PIPELINE_STEP_ID), add constraint FK2FAFF0151B797FE5 foreign key (PIPELINE_STEP_ID) references `MODELQUALITY_PIPELINE_STEP` (`PID`);
alter table `MODELQUALITY_PIPELINE_PROPERTY_DEF` add index FK1358AB2F255F581F (FK_PIPELINE_STEP_ID), add constraint FK1358AB2F255F581F foreign key (FK_PIPELINE_STEP_ID) references `MODELQUALITY_PIPELINE_STEP` (`PID`) on delete cascade;
alter table `MODELQUALITY_PIPELINE_PROPERTY_VALUE` add index FKA0D6921B47B756A3 (FK_PIPELINE_PROPDEF_ID), add constraint FKA0D6921B47B756A3 foreign key (FK_PIPELINE_PROPDEF_ID) references `MODELQUALITY_PIPELINE_PROPERTY_DEF` (`PID`) on delete cascade;
alter table `MODELQUALITY_SAMPLING_PROPERTY_DEF` add index FKC915FE0ABD563766 (FK_SAMPLING_ID), add constraint FKC915FE0ABD563766 foreign key (FK_SAMPLING_ID) references `MODELQUALITY_SAMPLING` (`PID`) on delete cascade;
alter table `MODELQUALITY_SAMPLING_PROPERTY_VALUE` add index FKDC8A9A366DEBF1D9 (FK_SAMPLING_PROPDEF_ID), add constraint FKDC8A9A366DEBF1D9 foreign key (FK_SAMPLING_PROPDEF_ID) references `MODELQUALITY_SAMPLING_PROPERTY_DEF` (`PID`) on delete cascade;
alter table `MODELQUALITY_SCORING_DATASET` add index FK6F2EFA3F2402520E (FK_DATASET_ID), add constraint FK6F2EFA3F2402520E foreign key (FK_DATASET_ID) references `MODELQUALITY_DATASET` (`PID`) on delete cascade;
create index IX_MODEL_ID on `MODELREVIEW_COLUMNRESULT` (`MODEL_ID`);
alter table `MODELREVIEW_COLUMNRESULT` add index FKFE9B7ED136865BC (FK_TENANT_ID), add constraint FKFE9B7ED136865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`) on delete cascade;
alter table `MODELREVIEW_DATARULE` add index FKCF2984845FC50F27 (FK_TABLE_ID), add constraint FKCF2984845FC50F27 foreign key (FK_TABLE_ID) references `METADATA_TABLE` (`PID`) on delete cascade;
create index IX_MODEL_ID on `MODELREVIEW_ROWRESULT` (`MODEL_ID`);
alter table `MODELREVIEW_ROWRESULT` add index FK9B12AF3936865BC (FK_TENANT_ID), add constraint FK9B12AF3936865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`) on delete cascade;
create index IX_MARK_TIME on `MODEL_SUMMARY_DOWNLOAD_FLAGS` (`MARK_TIME`);
create index IX_TENANT_ID on `MODEL_SUMMARY_DOWNLOAD_FLAGS` (`Tenant_ID`);
create index PROSPECT_DISCOVERY_OPTION_OPTION_IDX on `MODEL_SUMMARY_PROVENANCE_PROPERTY` (`OPTION`);
alter table `MODEL_SUMMARY_PROVENANCE_PROPERTY` add index FKE48A6FC468D2D330 (MODEL_SUMMARY_ID), add constraint FKE48A6FC468D2D330 foreign key (MODEL_SUMMARY_ID) references `MODEL_SUMMARY` (`PID`) on delete cascade;
create index MODEL_SUMMARY_ID_IDX on `MODEL_SUMMARY` (`ID`);
create index MODEL_SUMMARY_NAME_IDX on `MODEL_SUMMARY` (`NAME`);
alter table `MODEL_SUMMARY` add index FKCEB8C450AC2B0EB2 (FK_KEY_VALUE_ID), add constraint FKCEB8C450AC2B0EB2 foreign key (FK_KEY_VALUE_ID) references `KEY_VALUE` (`PID`) on delete cascade;
alter table `MODEL_SUMMARY` add index FKCEB8C45036865BC (FK_TENANT_ID), add constraint FKCEB8C45036865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`) on delete cascade;
alter table `MODEL` add index FK46203095FB2DB1E (FK_MODEL_DEF_ID), add constraint FK46203095FB2DB1E foreign key (FK_MODEL_DEF_ID) references `MODEL_DEFINITION` (`PID`);
alter table `OAUTH2_ACCESS_TOKEN` add index FK5FB0F86236865BC (FK_TENANT_ID), add constraint FK5FB0F86236865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`) on delete cascade;
alter table `PREDICTOR_ELEMENT` add index FKC39535F9F9802A4B (FK_PREDICTOR_ID), add constraint FKC39535F9F9802A4B foreign key (FK_PREDICTOR_ID) references `PREDICTOR` (`PID`) on delete cascade;
alter table `PREDICTOR` add index FK55BF005C8807F0C9 (FK_MODELSUMMARY_ID), add constraint FK55BF005C8807F0C9 foreign key (FK_MODELSUMMARY_ID) references `MODEL_SUMMARY` (`PID`) on delete cascade;
create index PROSPECT_DISCOVERY_OPTION_OPTION_IDX on `PROSPECT_DISCOVERY_OPTION` (`OPTION`);
create index PROSPECT_DISCOVERY_OPTION_TENANT_ID_IDX on `PROSPECT_DISCOVERY_OPTION` (`TENANT_ID`);
alter table `QUOTA` add index FK49D465836865BC (FK_TENANT_ID), add constraint FK49D465836865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`) on delete cascade;
alter table `REPORT` add index FK8FDF4934AC2B0EB2 (FK_KEY_VALUE_ID), add constraint FK8FDF4934AC2B0EB2 foreign key (FK_KEY_VALUE_ID) references `KEY_VALUE` (`PID`);
alter table `REPORT` add index FK8FDF493436865BC (FK_TENANT_ID), add constraint FK8FDF493436865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`) on delete cascade;
alter table `SEGMENT` add index FKA0702B1336865BC (FK_TENANT_ID), add constraint FKA0702B1336865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`) on delete cascade;
alter table `SELECTED_ATTRIBUTE` add index FKF65251D836865BC (FK_TENANT_ID), add constraint FKF65251D836865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`) on delete cascade;
alter table `SOURCE_FILE` add index FK7D04A32036865BC (FK_TENANT_ID), add constraint FK7D04A32036865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`) on delete cascade;
create index PROSPECT_DISCOVERY_OPTION_OPTION_IDX on `TARGET_MARKET_DATA_FLOW_OPTION` (`OPTION`);
alter table `TARGET_MARKET_DATA_FLOW_OPTION` add index FK18B26886AFC9B7C6 (TARGET_MARKET_ID), add constraint FK18B26886AFC9B7C6 foreign key (TARGET_MARKET_ID) references `TARGET_MARKET` (`PID`) on delete cascade;
alter table `TARGET_MARKET_REPORT_MAP` add index FK16FEE466799FEF17 (REPORT_ID), add constraint FK16FEE466799FEF17 foreign key (REPORT_ID) references `REPORT` (`PID`);
alter table `TARGET_MARKET_REPORT_MAP` add index FK16FEE466AFC9B7C6 (TARGET_MARKET_ID), add constraint FK16FEE466AFC9B7C6 foreign key (TARGET_MARKET_ID) references `TARGET_MARKET` (`PID`);
alter table `TARGET_MARKET` add index FKDD9CEAAA36865BC (FK_TENANT_ID), add constraint FKDD9CEAAA36865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`);
alter table `WORKFLOW_JOB` add index FKE7361F1D36865BC (FK_TENANT_ID), add constraint FKE7361F1D36865BC foreign key (FK_TENANT_ID) references `TENANT` (`TENANT_PID`) on delete cascade;
alter table `WORKFLOW_JOB_EXECUTION` add constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID) references WORKFLOW_JOB_INSTANCE(JOB_INSTANCE_ID);
alter table `WORKFLOW_JOB_EXECUTION_PARAMS` add constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID) references WORKFLOW_JOB_EXECUTION(JOB_EXECUTION_ID);
alter table `WORKFLOW_STEP_EXECUTION` add constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID) references WORKFLOW_JOB_EXECUTION(JOB_EXECUTION_ID);
alter table `WORKFLOW_STEP_EXECUTION_CONTEXT` add constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID) references WORKFLOW_STEP_EXECUTION(STEP_EXECUTION_ID);
alter table `WORKFLOW_JOB_EXECUTION_CONTEXT` add constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID) references WORKFLOW_JOB_EXECUTION(JOB_EXECUTION_ID);