UPDATE `PLS_MultiTenant`.`WORKFLOW_JOB_EXECUTION_SEQ` SET `UNIQUE_KEY`='0' WHERE `UNIQUE_KEY`='';

UPDATE `PLS_MultiTenant`.`WORKFLOW_JOB_SEQ` SET `UNIQUE_KEY`='0' WHERE `UNIQUE_KEY`='';

UPDATE `PLS_MultiTenant`.`WORKFLOW_STEP_EXECUTION_SEQ` SET `UNIQUE_KEY`='0' WHERE `UNIQUE_KEY`='';