#!/bin/bash
source /etc/profile
rm -rf $CATALINA_HOME/webapps/playmaker/le-playmaker-*.war
rm -rf /tmp/webapps/playmaker/le-playmaker-*.war
rm -rf $CATALINA_HOME/webapps/playmaker/ROOT.war
rm -rf /tmp/webapps/playmaker/ROOT.war
rm -rf /etc/ledp/playmaker.properties
rm -rf /etc/ledp/oauth2.properties
adduser yarn
groupadd yarn
groupadd tomcat
mkdir -p /var/log/ledp
mkdir -p /home/yarn/logs
chmod -R 755 /var/log/ledp
chmod -R 755 /home/yarn/logs
chown -R yarn:yarn /var/log/ledp
chown -R yarn:yarn /home/yarn/logs