CREATE TABLE WORKFLOW_JOB_EXECUTION_PARAMS  (
	PID BIGINT identity NOT NULL unique,
	JOB_EXECUTION_ID BIGINT NOT NULL ,
	TYPE_CD VARCHAR(6) NOT NULL ,
	KEY_NAME VARCHAR(1000) NOT NULL ,
	STRING_VAL VARCHAR(MAX) ,
	DATE_VAL DATETIME DEFAULT NULL ,
	LONG_VAL BIGINT ,
	DOUBLE_VAL DOUBLE PRECISION ,
	IDENTIFYING CHAR(1) NOT NULL ,
	primary key ([PID]),
	constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
	references WORKFLOW_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;