CREATE TABLE WORKFLOW_JOB_EXECUTION_PARAMS  (	
	PID BIGINT  NOT NULL auto_increment unique PRIMARY KEY ,
	JOB_EXECUTION_ID BIGINT NOT NULL ,
	TYPE_CD VARCHAR(6) NOT NULL ,
	KEY_NAME TEXT NOT NULL ,
	STRING_VAL MEDIUMTEXT ,
	DATE_VAL DATETIME DEFAULT NULL ,
	LONG_VAL BIGINT ,
	DOUBLE_VAL DOUBLE PRECISION ,
	IDENTIFYING CHAR(1) NOT NULL ,
	constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
	references WORKFLOW_JOB_EXECUTION(JOB_EXECUTION_ID)
) ENGINE=InnoDB;