SpecLatticeNamedElement(
  SpecLatticeFunction(
    LatticeFunctionExpression(
 
      LatticeFunctionOperatorIdentifier("IF")
     ,LatticeFunctionIdentifier(ContainerElementName("DefnSegment_US"))
     ,LatticeFunctionExpressionConstant("GUID-US",DataTypeVarChar(7))
 
     ,LatticeFunctionExpression(
 
        LatticeFunctionOperatorIdentifier("IF")
       ,LatticeFunctionIdentifier(ContainerElementName("DefnSegment_Spain"))
       ,LatticeFunctionExpressionConstant("GUID-Spain",DataTypeVarChar(10))
 
       ,LatticeFunctionExpressionConstant("Unknown",DataTypeVarChar(7))
      )
    )
   ,DataTypeUnknown
   ,SpecFunctionTypeMetric
   ,SpecFunctionSourceTypeCalculation
   ,SpecDefaultValueNull
   ,SpecDescription("")
  )
,ContainerElementName("AppData_Model_GUID")
)
