USE `LDC_ManageDB`;

SET SQL_SAFE_UPDATES = 0;

DROP PROCEDURE IF EXISTS `UpdateDataCloudVersionTable`;

DROP PROCEDURE IF EXISTS `UpdateDecisionGraphTable`;

DROP PROCEDURE IF EXISTS `UpdateSchema`;

DELIMITER //
CREATE PROCEDURE `UpdateDataCloudVersionTable`()
  BEGIN
  END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `UpdateDecisionGraphTable`()
  BEGIN
  END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `CreatePatchBookTable`()
  BEGIN
  END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `UpdateSchema`()
  BEGIN

  END //
DELIMITER ;

CALL `UpdateSchema`();



