#!/bin/bash
echo 'Running Postinstall'

echo 'check env var STACK_NAME'
echo $STACK_NAME

JARFILE=`ls /tmp/app/dataflow/le-dataflow*-shaded.jar`
VERSION=`echo $JARFILE | cut -d \- -f 3`
SNAPSHOT=`echo $JARFILE | cut -d \- -f 4`

if test $SNAPSHOT = "SNAPSHOT"
    then
        VERSION=$VERSION-"SNAPSHOT"
fi

if [ ! -z "$STACK_NAME" -a "$STACK_NAME" != " " ]; then
    VERSION=${STACK_NAME}/${VERSION}
fi

hdfs dfs -rm -r -f /app/$VERSION/dataflow/lib/*
hdfs dfs -put /tmp/app/dataflow/le-dataflow*-shaded.jar /app/$VERSION/dataflow/lib
hdfs dfs -copyFromLocal /tmp/app/dataflow/dataflow.properties /app/$VERSION/dataflow
rm -rf /tmp/app/dataflow/
