#!/bin/bash
echo 'Running Postinstall'

echo "getting environment information"
echo $LE_ENVIRONMENT
echo $LE_STACK
echo $STACK_PROFILE
echo $USE_AWS

JARFILE=`ls /tmp/app/dataflow/le-dataflow*-shaded.jar`
VERSION=`echo $JARFILE | cut -d \- -f 3`
SNAPSHOT=`echo $JARFILE | cut -d \- -f 4`

if test $SNAPSHOT = "SNAPSHOT"
    then
        VERSION=$VERSION-"SNAPSHOT"
fi

if [ ! -z "$LE_STACK" -a "$LE_STACK" != " " ]; then
    VERSION=${LE_STACK}/${VERSION}
fi

echo $VERSION

hdfs dfs -rm -r -f /app/$VERSION/dataflow/lib/*
hdfs dfs -put /tmp/app/dataflow/le-dataflow*-shaded.jar /app/$VERSION/dataflow/lib
hdfs dfs -copyFromLocal /tmp/app/dataflow/dataflow.properties /app/$VERSION/dataflow
rm -rf /tmp/app/dataflow/
