#!/bin/bash
echo 'Running Preinstall'

echo "getting environment information"
echo $LE_ENVIRONMENT
echo $LE_STACK
echo $STACK_PROFILE
echo $USE_AWS

RPMFILE=`ls /tmp/le-dataflow-hdfs-*.rpm`
VERSION=`echo $RPMFILE | cut -d \- -f 5`
SNAPSHOT=`echo $RPMFILE | cut -d \- -f 6`

if [[ $SNAPSHOT = SNAPSHOT* ]]
    then
        VERSION=$VERSION-"SNAPSHOT"
fi

if [ ! -z "$LE_STACK" -a "$LE_STACK" != " " ]; then
    VERSION=${LE_STACK}/${VERSION}
fi

echo $VERSION


if [ -d "/tmp/app/dataflow" ]; then
    rm -rf /tmp/app/dataflow/le-dataflow*-shaded.jar
else
    mkdir -p /tmp/app/dataflow
fi
hdfs dfs -mkdir -p /app/$VERSION/dataflow/lib || true
hdfs dfs -rm -f /app/$VERSION/dataflow/lib/le-dataflow*-shaded.jar || true
hdfs dfs -rm -f /app/$VERSION/dataflow/dataflow.properties || true

