package com.latticeengines.domain.exposed;

public final class StringTemplateConstants {

    protected StringTemplateConstants() {
        throw new UnsupportedOperationException();
    }

    // Template tokens/values
    public static final String ACTIVITY_METRICS_GROUP_TIME_RANGE_TOKEN = "TimeRange";
    public static final String ACTIVITY_METRICS_GROUP_PERIOD_STRATEGY_TOKEN = "periodStrategy";
    public static final String ACTIVITY_METRICS_GROUP_TIME_RANGE_PERIOD_ONLY_TOKEN = "PeriodOnly";
    public static final String ACTIVITY_METRICS_GROUP_NEXT_RANGE_PERIOD_ONLY_TOKEN = "NextPeriodOnly"; // only compatible with single param time filter
    public static final String ACTIVITY_METRICS_GROUP_TIME_RANGE = "${operator}_${params?join(\"_\")}_${period}";
    public static final String ACTIVITY_METRICS_GROUP_TIME_RANGE_NO_VAL = "${operator}_${period}";
    public static final String TILL_CURRENT_DESC = "<#if params[0] == '0'>Current<#else>${params[0]}</#if> ${period} till today";
    public static final String SINGLE_VAL_TIME_RANGE_DESC = "${operator} ${params[0]} ${period}";
    public static final String DOUBLE_VAL_TIME_RANGE_DESC = "${operator} ${params?join(\" and \")} ${period}";
    public static final String ACTIVITY_METRICS_GROUP_PERIOD_ONLY = "${params[0]} ${period}";
    public static final String ACTIVITY_METRICS_GROUP_ATTRNAME = "am_${GroupId}__${RollupDimIds?join(\"_\")}__${" + ACTIVITY_METRICS_GROUP_TIME_RANGE_TOKEN + "}";
    public static final String ACTIVITY_METRICS_ATTR_SECONDARY_DISPLAYNAME = "(%s to %s)";

    // Names in DB
    public static final String ACTIVITY_METRICS_GROUP_TOTAL_VISIT_DISPLAYNAME = "ACTIVITY_METRICS_GROUP_TOTAL_VISIT_DISPLAYNAME";
    public static final String ACTIVITY_METRICS_GROUP_TOTAL_VISIT_DESCRIPTION = "ACTIVITY_METRICS_GROUP_TOTAL_VISIT_DESCRIPTION";
    public static final String ACTIVITY_METRICS_GROUP_TOTAL_VISIT_DESCRIPTION_CW = "ACTIVITY_METRICS_GROUP_TOTAL_VISIT_DESCRIPTION_CW";
    public static final String ACTIVITY_METRICS_GROUP_SUBCATEGORY = "ACTIVITY_METRICS_GROUP_SUBCATEGORY";
    public static final String ACTIVITY_METRICS_GROUP_SOURCEMEDIUM_DISPLAYNAME = "ACTIVITY_METRICS_GROUP_SOURCEMEDIUM_DISPLAYNAME" ;
    public static final String ACTIVITY_METRICS_GROUP_SOURCEMEDIUM_DESCRIPTION = "ACTIVITY_METRICS_GROUP_SOURCEMEDIUM_DESCRIPTION";
    public static final String ACTIVITY_METRICS_GROUP_SOURCEMEDIUM_DESCRIPTION_CW = "ACTIVITY_METRICS_GROUP_SOURCEMEDIUM_DESCRIPTION_CW";
    public static final String ACTIVITY_METRICS_GROUP_SECONDARY_SUBCATEGORY = "ACTIVITY_METRICS_GROUP_SECONDARY_SUBCATEGORY";
    public static final String ACTIVITY_METRICS_GROUP_SOURCEMEDIUMNAME_DISPLAYNAME = "ACTIVITY_METRICS_GROUP_SOURCEMEDIUMNAME_DISPLAYNAME";

    public static final String OPPORTUNITY_METRICS_GROUP_STAGENAME_DISPLAYNAME = "OPPORTUNITY_METRICS_GROUP_STAGENAME_DISPLAYNAME";
    public static final String OPPORTUNITY_METRICS_GROUP_NAME_DISPLAYNAME = "OPPORTUNITY_METRICS_GROUP_NAME_DISPLAYNAME";
    public static final String OPPORTUNITY_METRICS_GROUP_STAGENAME_DESCRIPTION = "OPPORTUNITY_METRICS_GROUP_STAGENAME_DESCRIPTION";
    public static final String OPPORTUNITY_METRICS_GROUP_SUBCATEGORY = "OPPORTUNITY_METRICS_GROUP_SUBCATEGORY";

    public static final String MARKETING_METRICS_GROUP_ACTIVITYTYPE_DISPLAYNAME = "MARKETING_METRICS_GROUP_ACTIVITYTYPE_DISPLAYNAME";
    public static final String MARKETING_METRICS_GROUP_ACTIVITYTYPE_DESCRIPTION = "MARKETING_METRICS_GROUP_ACTIVITYTYPE_DESCRIPTION";
    public static final String MARKETING_METRICS_GROUP_ACTIVITYTYPE_DESCRIPTION_CW = "MARKETING_METRICS_GROUP_ACTIVITYTYPE_DESCRIPTION_CW";
    public static final String MARKETING_METRICS_GROUP_ACTIVITYTYPE_SUBCATEGORY = "MARKETING_METRICS_GROUP_ACTIVITYTYPE_SUBCATEGORY";
    public static final String MARKETING_METRICS_GROUP_SECONDARY_SUBCATEGORY = "MARKETING_METRICS_GROUP_SECONDARY_SUBCATEGORY";

    public static final String DNBINTENTDATA_METRICS_GROUP_INTENT_DISPLAYNAME = "DNBINTENTDATA_METRICS_GROUP_INTENT_DISPLAYNAME";
    public static final String DNBINTENTDATA_METRICS_GROUP_INTENT_DESCRIPTION = "DNBINTENTDATA_METRICS_GROUP_INTENT_DESCRIPTION";
    public static final String DNBINTENTDATA_METRICS_GROUP_INTENT_SUBCATEGORY = "DNBINTENTDATA_METRICS_GROUP_INTENT_SUBCATEGORY";
    public static final String DNBINTENTDATA_METRICS_GROUP_CURRENT_WEEK_DESCRIPTION = "DNBINTENTDATA_METRICS_GROUP_CURRENT_WEEK_DESCRIPTION";

    public static final String DNBINTENTDATA_METRICS_GROUP_MODEL_DISPLAYNAME = "DNBINTENTDATA_METRICS_GROUP_MODEL_DISPLAYNAME";
    public static final String DNBINTENTDATA_METRICS_GROUP_MODEL_DESCRIPTION = "DNBINTENTDATA_METRICS_GROUP_MODEL_DESCRIPTION";
    public static final String DNBINTENTDATA_METRICS_GROUP_MODEL_SUBCATEGORY = "DNBINTENTDATA_METRICS_GROUP_MODEL_SUBCATEGORY";

    public static final String BUYINGSCORE_METRICS_GROUP_DISPLAYNAME = "BUYINGSCORE_METRICS_GROUP_DISPLAYNAME";
    public static final String BUYINGSCORE_METRICS_GROUP_DESCRIPTION = "BUYINGSCORE_METRICS_GROUP_DESCRIPTION";
    public static final String BUYINGSCORE_METRICS_GROUP_SUBCATEGORY = "BUYINGSCORE_METRICS_GROUP_SUBCATEGORY";

    public static final String DERIVED_DIMENSION_GROUP_DISPLAYNAME = "DERIVED_DIMENSION_GROUP_DISPLAYNAME";
    public static final String DERIVED_DIMENSION_GROUP_SUBCATEGORY = "DERIVED_DIMENSION_GROUP_SUBCATEGORY";
}
