#
# $LastChangedBy: mwilson $
# $LastChangedDate: 2015-11-13 14:56:48 +0800 (Fri, 13 Nov 2015) $
# $Rev: 70934 $
#

from lxml import etree
from appsequence import Applicability, StepBase


class LP_020200_DL_POC_Model(StepBase):
  name = 'LP_020200_DL_POC_Model'
  description = 'Create a series LGs to go live POL model'
  version = '$Rev: 70934 $'

  def __init__(self, forceApply=False):
    super(LP_020200_DL_POC_Model, self).__init__(forceApply)

  def getApplicability(self, appseq):

    lgm = appseq.getLoadGroupMgr()
    if lgm.hasLoadGroup('Download_BasicModelingSet') \
      and lgm.hasLoadGroup('Initialize') \
      and lgm.hasLoadGroup('Model') \
      and lgm.hasLoadGroup('Score_ConfiguredDateRange') \
      and lgm.hasLoadGroup('Upload_LatestScoredLeadsToCustomer'):
      return Applicability.alreadyAppliedPass
    return Applicability.canApply

  def apply(self, appseq):

    success = False

    lgm = appseq.getLoadGroupMgr()
    type = appseq.getText('template_type')

    if type == 'MKTO':
      # POC MKTO 1: Change filter for LoadCRMDataForModeling
      lgm.createLoadGroup('LoadCRMDataForModeling', 'ModelBuild\Standard', 'LoadCRMDataForModeling', True, False)
      step1xml = ''
      step1xml = '''
    <group name="LoadCRMDataForModeling" alias="LoadCRMDataForModeling" w="Workspace" type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000" launchExpiredDays="7" createdBy="tiyu@lattice-engines.com" path="ModelBuild\Standard" autoGenerated="False" validationValidMinutes="120" autoClearOnFailure="False" mergeRulesSaved="True" ng="False">
      <schemas />
      <visiDBConfigurationWithMacros />
      <targetQueries />
      <targetQuerySequences />
      <rdss>
        <rds n="SFDC_User" w="Workspace" sn="SFDC_User" cn="SFDC_DataProvider" u="False" ss="" tn="User" nmo="1" f="@datediff(now, month(12))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="False" eo_sftp="1">
          <mcs>
            <mc cn="Id" />
            <mc cn="LastModifiedDate" />
          </mcs>
        </rds>
        <rds n="SFDC_Contact" w="Workspace" sn="SFDC_Contact" cn="SFDC_DataProvider" u="False" ss="" tn="Contact" nmo="1" f="@datediff(now, month(12))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="False" eo_sftp="1">
          <mcs>
            <mc cn="Id" />
            <mc cn="LastModifiedDate" />
          </mcs>
        </rds>
        <rds n="SFDC_Lead" w="Workspace" sn="SFDC_Lead" cn="SFDC_DataProvider" u="False" ss="" tn="Lead" nmo="1" f="@datediff(now, month(12))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="False" eo_sftp="1">
          <mcs>
            <mc cn="Id" />
            <mc cn="LastModifiedDate" />
          </mcs>
        </rds>
        <rds n="SFDC_Opportunity" w="Workspace" sn="SFDC_Opportunity" cn="SFDC_DataProvider" u="False" ss="" tn="Opportunity" nmo="1" f="@datediff(now, month(12))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="False" eo_sftp="1">
          <mcs>
            <mc cn="Id" />
            <mc cn="LastModifiedDate" />
          </mcs>
        </rds>
        <rds n="SFDC_OpportunityContactRole" w="Workspace" sn="SFDC_OpportunityContactRole" cn="SFDC_DataProvider" u="False" ss="" tn="OpportunityContactRole" nmo="1" f="@datediff(now, month(12))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="False" eo_sftp="1">
          <mcs>
            <mc cn="Id" />
            <mc cn="LastModifiedDate" />
          </mcs>
        </rds>
      </rdss>
      <validationExtracts />
      <ces />
      <extractQueries>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_DownloadedSFDC_Leads" queryAlias="Q_Timestamp_DownloadedSFDC_Leads" sw="Workspace" schemaName="Timestamp_DownloadedSFDC_Leads" at="False" ucm="True">
          <schemas />
          <specs />
          <cms>
            <cm qcn="SFDC_Lead_ID" itcn="SFDC_Lead_ID" />
            <cm qcn="Time_OfComepletion_DownloadedSFDC_Leads" itcn="Time_OfComepletion_DownloadedSFDC_Leads" />
          </cms>
        </extractQuery>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_DownloadedSFDC_Contacts" queryAlias="Q_Timestamp_DownloadedSFDC_Contacts" sw="Workspace" schemaName="Timestamp_DownloadedSFDC_Contacts" at="False" ucm="True">
          <schemas />
          <specs />
          <cms>
            <cm qcn="SFDC_Contact_ID" itcn="SFDC_Contact_ID" />
            <cm qcn="Time_OfComepletion_DownloadedSFDC_Contacts" itcn="Time_OfComepletion_DownloadedSFDC_Contacts" />
          </cms>
        </extractQuery>
      </extractQueries>
      <extractQuerySequences />
      <leafExtracts />
      <launchExtracts />
      <jobs />
      <pdmatches />
      <leadscroings />
      <lssbardins />
      <lssbardouts />
      <lds />
      <ecs />
      <gCs />
    </group>'''
      lgm.setLoadGroup(step1xml)

      # POC MKTO 2: Change Filter for LoadMAPDataForModeling_ActivityRecord_NewLead
      lgm.createLoadGroup('LoadMAPDataForModeling_ActivityRecord_NewLead', 'ModelBuild\Standard',
                          'LoadMAPDataForModeling_ActivityRecord_NewLead', True, False)
      step3xml = ''
      step3xml = '''
      <group name="LoadMAPDataForModeling_ActivityRecord_NewLead" alias="LoadMAPDataForModeling_ActivityRecord_NewLead" w="Workspace" type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000" launchExpiredDays="7" createdBy="richard.liu@lattice-engines.com" path="ModelBuild\Standard" autoGenerated="False" validationValidMinutes="120" autoClearOnFailure="False" mergeRulesSaved="True" ng="False">
      <schemas />
      <visiDBConfigurationWithMacros />
      <targetQueries />
      <targetQuerySequences />
      <rdss>
        <rds n="ActivityRecord_NewLead" w="Workspace" sn="MKTO_ActivityRecord" cn="Marketo_DataProvider" u="False" ss="" tn="ActivityRecord" nmo="1" f="activityType = 'New Lead'" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="True" sr="50000" htw="24" mtw="60" emt="True" acd="True" mgf="True" eo="1" emd="True" eo_sftp="1">
          <mcs>
            <mc cn="activityDateTime" />
            <mc cn="activityType" />
            <mc cn="campaign" />
            <mc cn="foreignSysId" />
            <mc cn="foreignSysOrgId" />
            <mc cn="id" />
            <mc cn="mktgAssetName" />
            <mc cn="mktPersonId" />
            <mc cn="orgName" />
            <mc cn="personName" />
          </mcs>
        </rds>
      </rdss>
      <validationExtracts />
      <ces />
      <extractQueries>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_DownloadedActivity" queryAlias="Q_Timestamp_DownloadedActivity" sw="Workspace" schemaName="Timestamp_DownloadedActivity" at="False" ucm="True">
          <schemas />
          <specs />
          <cms>
            <cm qcn="MKTO_ActivityRecord_ID" itcn="MKTO_ActivityRecord_ID" />
            <cm qcn="Time_OfCompletion_DownloadedActivity" itcn="Time_OfCompletion_DownloadedActivity" />
          </cms>
        </extractQuery>
      </extractQueries>
      <extractQuerySequences />
      <leafExtracts />
      <launchExtracts />
      <jobs />
      <pdmatches />
      <leadscroings />
      <lssbardins />
      <lssbardouts />
      <lds />
      <ecs />
      <gCs />
    </group>'''
      lgm.setLoadGroup(step3xml)

      # POC MKTO 3: Seperate 8 activity types for LoadMAPDataForModeling_ActivityRecord_OtherThanNewLead
      lgm.createLoadGroup('LoadMAPDataForModeling_ActivityRecord_OtherThanNewLead', 'ModelBuild\Standard',
                          'LoadMAPDataForModeling_ActivityRecord_OtherThanNewLead', True, False)
      step4xml = ''
      step4xml = '''
      <group name="LoadMAPDataForModeling_ActivityRecord_OtherThanNewLead" alias="LoadMAPDataForModeling_ActivityRecord_OtherThanNewLead" w="Workspace" type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000" launchExpiredDays="7" createdBy="richard.liu@lattice-engines.com" path="ModelBuild\Standard" autoGenerated="False" validationValidMinutes="120" autoClearOnFailure="False" mergeRulesSaved="False" ng="False">
      <schemas />
      <visiDBConfigurationWithMacros />
      <targetQueries />
      <targetQuerySequences />
      <rdss>
        <rds n="ActivityRecord_OtherThanNewLead" w="Workspace" sn="MKTO_ActivityRecord" cn="Marketo_DataProvider" u="False" ss="" tn="ActivityRecord" nmo="1" f="@datediff(now, month(12)) AND activityType = 'Click Link'" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="True" sr="50000" htw="24" mtw="60" emt="True" acd="True" mgf="False" eo="1" emd="True" eo_sftp="1">
          <mcs>
            <mc cn="activityDateTime" />
            <mc cn="activityType" />
            <mc cn="campaign" />
            <mc cn="foreignSysId" />
            <mc cn="foreignSysOrgId" />
            <mc cn="id" />
            <mc cn="mktgAssetName" />
            <mc cn="mktPersonId" />
            <mc cn="orgName" />
            <mc cn="personName" />
          </mcs>
        </rds>
        <rds n="ActivityRecord_OtherThanNewLead_2" w="Workspace" sn="MKTO_ActivityRecord" cn="Marketo_DataProvider" u="False" ss="" tn="ActivityRecord" nmo="1" f="@datediff(now, month(12)) AND activityType = 'Visit Webpage'" ad="True" em="False" td="False" ic="50000" dd="24" l="1000" tw="True" sr="50000" htw="24" mtw="60" emt="True" acd="True" mgf="True" eo="1" emd="True" eo_sftp="2" />
        <rds n="ActivityRecord_OtherThanNewLead_3" w="Workspace" sn="MKTO_ActivityRecord" cn="Marketo_DataProvider" u="False" ss="" tn="ActivityRecord" nmo="1" f="@datediff(now, month(12)) AND activityType = 'Interesting Moment'" ad="True" em="False" td="False" ic="50000" dd="24" l="1000" tw="True" sr="50000" htw="24" mtw="60" emt="True" acd="True" mgf="True" eo="1" emd="True" eo_sftp="2" />
        <rds n="ActivityRecord_OtherThanNewLead_4" w="Workspace" sn="MKTO_ActivityRecord" cn="Marketo_DataProvider" u="False" ss="" tn="ActivityRecord" nmo="1" f="@datediff(now, month(12)) AND activityType = 'Open Email'" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="True" sr="50000" htw="24" mtw="60" emt="True" acd="True" mgf="True" eo="1" emd="True" eo_sftp="2" />
        <rds n="ActivityRecord_OtherThanNewLead_5" w="Workspace" sn="MKTO_ActivityRecord" cn="Marketo_DataProvider" u="False" ss="" tn="ActivityRecord" nmo="1" f="@datediff(now, month(12)) AND activityType = 'Email Bounced Soft'" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="True" sr="50000" htw="24" mtw="60" emt="True" acd="True" mgf="True" eo="1" emd="True" eo_sftp="2" />
        <rds n="ActivityRecord_OtherThanNewLead_6" w="Workspace" sn="MKTO_ActivityRecord" cn="Marketo_DataProvider" u="False" ss="" tn="ActivityRecord" nmo="1" f="@datediff(now, month(12)) AND activityType = 'Fill Out Form'" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="True" sr="50000" htw="24" mtw="60" emt="True" acd="True" mgf="True" eo="1" emd="True" eo_sftp="2" />
        <rds n="ActivityRecord_OtherThanNewLead_7" w="Workspace" sn="MKTO_ActivityRecord" cn="Marketo_DataProvider" u="False" ss="" tn="ActivityRecord" nmo="1" f="@datediff(now, month(12)) AND activityType = 'Unsubscribe Email'" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="True" sr="50000" htw="24" mtw="60" emt="True" acd="True" mgf="True" eo="1" emd="True" eo_sftp="2" />
        <rds n="ActivityRecord_OtherThanNewLead_8" w="Workspace" sn="MKTO_ActivityRecord" cn="Marketo_DataProvider" u="False" ss="" tn="ActivityRecord" nmo="1" f="@datediff(now, month(12)) AND activityType = 'Click Email'" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="True" sr="50000" htw="24" mtw="60" emt="True" acd="True" mgf="True" eo="1" emd="True" eo_sftp="2" />
      </rdss>
      <validationExtracts />
      <ces />
      <extractQueries>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_DownloadedActivity" queryAlias="Q_Timestamp_DownloadedActivity" sw="Workspace" schemaName="Timestamp_DownloadedActivity" at="False" ucm="True">
          <schemas />
          <specs />
          <cms>
            <cm qcn="MKTO_ActivityRecord_ID" itcn="MKTO_ActivityRecord_ID" />
            <cm qcn="Time_OfCompletion_DownloadedActivity" itcn="Time_OfCompletion_DownloadedActivity" />
          </cms>
        </extractQuery>
      </extractQueries>
      <extractQuerySequences />
      <leafExtracts />
      <launchExtracts />
      <jobs />
      <pdmatches />
      <leadscroings />
      <lssbardins />
      <lssbardouts />
      <lds />
      <ecs />
      <gCs />
    </group>'''
      lgm.setLoadGroup(step4xml)

      # POC MKTO 4: Create New LG: LoadCRMData_2Days
      lgm.createLoadGroup('LoadCRMData_2Days', 'Provisioning', 'LoadCRMData_2Days', True, False)
      step5xml = ''
      step5xml = '''
      <group name="LoadCRMData_2Days" alias="LoadCRMData_2Days" w="Workspace" type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000" launchExpiredDays="7" createdBy="YTian@Lattice-Engines.com" path="Provisioning" autoGenerated="False" validationValidMinutes="120" autoClearOnFailure="False" mergeRulesSaved="True" ng="False">
      <schemas />
      <visiDBConfigurationWithMacros />
      <targetQueries />
      <targetQuerySequences />
      <rdss>
        <rds n="SFDC_Lead" w="Workspace" sn="SFDC_Lead" cn="SFDC_DataProvider" u="False" ss="" tn="Lead" nmo="1" f="@datediff(now, day(2))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="False" eo="1" emd="True" eo_sftp="1">
          <mcs>
            <mc cn="Id" />
          </mcs>
        </rds>
        <rds n="SFDC_Opportunity" w="Workspace" sn="SFDC_Opportunity" cn="SFDC_DataProvider" u="False" ss="" tn="Opportunity" nmo="1" f="@datediff(now, day(2))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="False" eo="1" emd="True" eo_sftp="1">
          <mcs>
            <mc cn="Id" />
          </mcs>
        </rds>
        <rds n="SFDC_User" w="Workspace" sn="SFDC_User" cn="SFDC_DataProvider" u="False" ss="" tn="User" nmo="1" f="@datediff(now, day(2))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="False" eo="1" emd="False" eo_sftp="1">
          <mcs>
            <mc cn="Id" />
          </mcs>
        </rds>
        <rds n="SFDC_Contact" w="Workspace" sn="SFDC_Contact" cn="SFDC_DataProvider" u="False" ss="" tn="Contact" nmo="1" f="@datediff(now, day(2))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="False" eo="1" emd="True" eo_sftp="1">
          <mcs>
            <mc cn="Id" />
          </mcs>
        </rds>
        <rds n="SFDC_OpportunityContactRole" w="Workspace" sn="SFDC_OpportunityContactRole" cn="SFDC_DataProvider" u="False" ss="" tn="OpportunityContactRole" nmo="1" f="@datediff(now, day(2))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="False" eo="1" emd="True" eo_sftp="1">
          <mcs>
            <mc cn="ContactId" />
            <mc cn="CreatedById" />
            <mc cn="CreatedDate" />
            <mc cn="Id" />
            <mc cn="IsDeleted" />
            <mc cn="IsPrimary" />
            <mc cn="LastModifiedById" />
            <mc cn="LastModifiedDate" />
            <mc cn="OpportunityId" />
            <mc cn="Role" />
            <mc cn="SystemModstamp" />
          </mcs>
        </rds>
      </rdss>
      <validationExtracts />
      <ces />
      <extractQueries>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_DownloadedSFDC_Leads" queryAlias="Q_Timestamp_DownloadedSFDC_Leads" sw="Workspace" schemaName="Timestamp_DownloadedSFDC_Leads" at="False" ucm="True">
          <schemas />
          <specs />
          <cms>
            <cm qcn="SFDC_Lead_ID" itcn="SFDC_Lead_ID" />
            <cm qcn="Time_OfComepletion_DownloadedSFDC_Leads" itcn="Time_OfComepletion_DownloadedSFDC_Leads" />
          </cms>
        </extractQuery>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_DownloadedSFDC_Contacts" queryAlias="Q_Timestamp_DownloadedSFDC_Contacts" sw="Workspace" schemaName="Timestamp_DownloadedSFDC_Contacts" at="False" ucm="True">
          <schemas />
          <specs />
          <cms>
            <cm qcn="SFDC_Contact_ID" itcn="SFDC_Contact_ID" />
            <cm qcn="Time_OfComepletion_DownloadedSFDC_Contacts" itcn="Time_OfComepletion_DownloadedSFDC_Contacts" />
          </cms>
        </extractQuery>
      </extractQueries>
      <extractQuerySequences />
      <leafExtracts />
      <launchExtracts />
      <jobs />
      <pdmatches />
      <leadscroings />
      <lssbardins />
      <lssbardouts />
      <lds />
      <ecs />
      <gCs />
    </group>'''
      lgm.setLoadGroup(step5xml)

      # POC MKTO 5: Create New LG: LoadMAPDataForModeling_ActivityRecord_2Days
      lgm.createLoadGroup('LoadMAPDataForModeling_ActivityRecord_2Days', 'Provisioning',
                          'LoadMAPDataForModeling_ActivityRecord_2Days', True, False)
      step6xml = ''
      step6xml = '''
      <group name="LoadMAPDataForModeling_ActivityRecord_2Days" alias="LoadMAPDataForModeling_ActivityRecord_2Days" w="Workspace" type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000" launchExpiredDays="7" createdBy="YTian@Lattice-Engines.com" path="Provisioning" autoGenerated="False" validationValidMinutes="120" autoClearOnFailure="False" mergeRulesSaved="True" ng="False">
      <schemas />
      <visiDBConfigurationWithMacros />
      <targetQueries />
      <targetQuerySequences />
      <rdss>
        <rds n="ActivityRecord_OtherThanNewLead" w="Workspace" sn="MKTO_ActivityRecord" cn="Marketo_DataProvider" u="False" ss="" tn="ActivityRecord" nmo="1" f="@datediff(now, day(2)) AND activityType in ('Click Link','Visit Webpage','Interesting Moment','Open Email','Email Bounced Soft','Fill Out Form','Unsubscribe Email','Click Email')" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="True" sr="50000" htw="24" mtw="60" emt="True" acd="True" mgf="False" eo="1" emd="True" eo_sftp="1">
          <mcs>
            <mc cn="activityDateTime" />
            <mc cn="activityType" />
            <mc cn="campaign" />
            <mc cn="foreignSysId" />
            <mc cn="foreignSysOrgId" />
            <mc cn="id" />
            <mc cn="mktgAssetName" />
            <mc cn="mktPersonId" />
            <mc cn="orgName" />
            <mc cn="personName" />
          </mcs>
        </rds>
      </rdss>
      <validationExtracts />
      <ces />
      <extractQueries>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_DownloadedActivity" queryAlias="Q_Timestamp_DownloadedActivity" sw="Workspace" schemaName="Timestamp_DownloadedActivity" at="False" ucm="True">
          <schemas />
          <specs />
          <cms>
            <cm qcn="MKTO_ActivityRecord_ID" itcn="MKTO_ActivityRecord_ID" />
            <cm qcn="Time_OfCompletion_DownloadedActivity" itcn="Time_OfCompletion_DownloadedActivity" />
          </cms>
        </extractQuery>
      </extractQueries>
      <extractQuerySequences />
      <leafExtracts />
      <launchExtracts />
      <jobs />
      <pdmatches />
      <leadscroings />
      <lssbardins />
      <lssbardouts />
      <lds />
      <ecs />
      <gCs />
    </group>'''
      lgm.setLoadGroup(step6xml)

      # Create POC Nested LGs as Servies
      lgm.createLoadGroup('Download_BasicModelingSet', 'Services', 'Download_BasicModelingSet', True, False)
      POC_MKTO1 = etree.fromstring(lgm.getLoadGroup('Download_BasicModelingSet').encode('ascii', 'xmlcharrefreplace'))
      POC_MKTO1.set('ng', 'True')
      lgm.setLoadGroup(etree.tostring(POC_MKTO1))
      ngsxml_POC_MKTO1 = '<ngs><ng n="LoadCRMDataForModeling"/><ng n="LoadMAPDataForModeling_ActivityRecord_OtherThanNewLead"/><ng n="LoadMAPDataForModeling_LeadRecord"/><ng n="PropDataMatch"/></ngs>'
      lgm.setLoadGroupFunctionality('Download_BasicModelingSet', ngsxml_POC_MKTO1)

      lgm.createLoadGroup('Initialize', 'Services', 'Initialize', True, False)
      POC_MKTO2 = etree.fromstring(lgm.getLoadGroup('Initialize').encode('ascii', 'xmlcharrefreplace'))
      POC_MKTO2.set('ng', 'True')
      lgm.setLoadGroup(etree.tostring(POC_MKTO2))
      ngsxml_POC_MKTO2 = '<ngs><ng n="ImportMetaData"/><ng n="ImportCfgTables"/><ng n="LoadCRMData_2Days"/><ng n="LoadMAPDataForModeling_ActivityRecord_NewLead"/>\
      <ng n="LoadMAPDataForModeling_ActivityRecord_2Days"/><ng n="LoadMAPDataForModeling_LeadRecord"/><ng n="PropDataMatch"/><ng n="CreateEventTableQueries"/></ngs>'
      lgm.setLoadGroupFunctionality('Initialize', ngsxml_POC_MKTO2)

      lgm.createLoadGroup('Model', 'Services', 'Model', True, False)
      POC_MKTO3 = etree.fromstring(lgm.getLoadGroup('Model').encode('ascii', 'xmlcharrefreplace'))
      POC_MKTO3.set('ng', 'True')
      lgm.setLoadGroup(etree.tostring(POC_MKTO3))
      ngsxml_POC_MKTO3 = '<ngs><ng n="CreateAnalyticPlay"/></ngs>'
      lgm.setLoadGroupFunctionality('Model', ngsxml_POC_MKTO3)

    elif type == 'ELQ':

      # POC ELQ 1: Only for ELQ. Change CRMData before MAPData
      ptld = etree.fromstring(lgm.getLoadGroup('ExecuteModelBuilding').encode('ascii', 'xmlcharrefreplace'))
      ptld.set('ng', 'True')
      lgm.setLoadGroup(etree.tostring(ptld))
      ngsxml = '<ngs><ng n="LoadCRMDataForModeling"/><ng n="LoadMAPDataForModeling"/><ng n="ModelBuild_PropDataMatch"/><ng n="CreateEventTableQueries"/><ng n="CreateAnalyticPlay"/></ngs>'
      lgm.setLoadGroupFunctionality('ExecuteModelBuilding', ngsxml)

      # POC ELQ 2: Change filter for LoadCRMDataForModeling
      step1xml = '''
    <group name="LoadCRMDataForModeling" alias="LoadCRMDataForModeling" w="Workspace" type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000" launchExpiredDays="7" createdBy="tiyu@lattice-engines.com" path="ModelBuild\Standard" autoGenerated="False" validationValidMinutes="120" autoClearOnFailure="False" mergeRulesSaved="True" ng="False">
      <schemas />
      <visiDBConfigurationWithMacros />
      <targetQueries />
      <targetQuerySequences />
      <rdss>
        <rds n="SFDC_User" w="Workspace" sn="SFDC_User" cn="SFDC_DataProvider" u="False" ss="" tn="User" nmo="1" f="@datediff(now, month(12))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="False" eo_sftp="1">
          <mcs>
            <mc cn="Id" />
            <mc cn="LastModifiedDate" />
          </mcs>
        </rds>
        <rds n="SFDC_Contact" w="Workspace" sn="SFDC_Contact" cn="SFDC_DataProvider" u="False" ss="" tn="Contact" nmo="1" f="@datediff(now, month(12))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="False" eo_sftp="1">
          <mcs>
            <mc cn="Id" />
            <mc cn="LastModifiedDate" />
          </mcs>
        </rds>
        <rds n="SFDC_Lead" w="Workspace" sn="SFDC_Lead" cn="SFDC_DataProvider" u="False" ss="" tn="Lead" nmo="1" f="@datediff(now, month(12))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="False" eo_sftp="1">
          <mcs>
            <mc cn="Id" />
            <mc cn="LastModifiedDate" />
          </mcs>
        </rds>
        <rds n="SFDC_Opportunity" w="Workspace" sn="SFDC_Opportunity" cn="SFDC_DataProvider" u="False" ss="" tn="Opportunity" nmo="1" f="@datediff(now, month(12))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="False" eo_sftp="1">
          <mcs>
            <mc cn="Id" />
            <mc cn="LastModifiedDate" />
          </mcs>
        </rds>
        <rds n="SFDC_OpportunityContactRole" w="Workspace" sn="SFDC_OpportunityContactRole" cn="SFDC_DataProvider" u="False" ss="" tn="OpportunityContactRole" nmo="1" f="@datediff(now, month(12))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="False" eo_sftp="1">
          <mcs>
            <mc cn="Id" />
            <mc cn="LastModifiedDate" />
          </mcs>
        </rds>
      </rdss>
      <validationExtracts />
      <ces />
      <extractQueries>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_DownloadedSFDC_Leads" queryAlias="Q_Timestamp_DownloadedSFDC_Leads" sw="Workspace" schemaName="Timestamp_DownloadedSFDC_Leads" at="False" ucm="True">
          <schemas />
          <specs />
          <cms>
            <cm qcn="SFDC_Lead_ID" itcn="SFDC_Lead_ID" />
            <cm qcn="Time_OfComepletion_DownloadedSFDC_Leads" itcn="Time_OfComepletion_DownloadedSFDC_Leads" />
          </cms>
        </extractQuery>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_DownloadedSFDC_Contacts" queryAlias="Q_Timestamp_DownloadedSFDC_Contacts" sw="Workspace" schemaName="Timestamp_DownloadedSFDC_Contacts" at="False" ucm="True">
          <schemas />
          <specs />
          <cms>
            <cm qcn="SFDC_Contact_ID" itcn="SFDC_Contact_ID" />
            <cm qcn="Time_OfComepletion_DownloadedSFDC_Contacts" itcn="Time_OfComepletion_DownloadedSFDC_Contacts" />
          </cms>
        </extractQuery>
      </extractQueries>
      <extractQuerySequences />
      <leafExtracts />
      <launchExtracts />
      <jobs />
      <pdmatches />
      <leadscroings />
      <lssbardins />
      <lssbardouts />
      <lds />
      <ecs />
      <gCs />
    </group>'''
      lgm.setLoadGroup(step1xml)

      # POC ELQ 3: Only for ELQ. Change Filter for LoadMAPDataForModeling
      lgm.createLoadGroup('LoadMAPDataForModeling', 'ModelBuild\Standard', 'LoadMAPDataForModeling', True, False)
      step2xml = ''
      step2xml = '''
      <group name="LoadMAPDataForModeling" alias="LoadMAPDataForModeling" w="Workspace" type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000" launchExpiredDays="7" createdBy="tiyu@lattice-engines.com" path="ModelBuild\Standard" autoGenerated="False" validationValidMinutes="120" autoClearOnFailure="False" mergeRulesSaved="True" ng="False">
      <schemas />
      <visiDBConfigurationWithMacros />
      <targetQueries />
      <targetQuerySequences />
      <rdss>
        <rds n="ELQ_Contact" w="Workspace" sn="ELQ_Contact" cn="Eloqua_DataProvider" u="False" ss="" tn="Contact" nmo="1" f="@datediff(now, month(12)) AND @recordcount(1000000)" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="True" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="True" eo_sftp="1">
          <mcs>
            <mc cn="C_Address1" />
            <mc cn="C_Annual_Revenue1" />
            <mc cn="C_BusPhone" />
            <mc cn="C_City" />
            <mc cn="C_Company" />
            <mc cn="C_Company_Size1" />
            <mc cn="C_Country" />
            <mc cn="C_DateCreated" />
            <mc cn="C_DateModified" />
            <mc cn="C_EmailAddress" />
            <mc cn="C_FirstName" />
            <mc cn="C_Industry1" />
            <mc cn="C_Job_Role1" />
            <mc cn="C_LastName" />
            <mc cn="C_Lead_Source___Most_Recent1" />
            <mc cn="C_Lead_Source___Original1" />
            <mc cn="C_Product_Solution_of_Interest1" />
            <mc cn="C_SFDC_EmailOptOut1" />
            <mc cn="C_SFDCLeadID" />
            <mc cn="C_State_Prov" />
            <mc cn="C_Title" />
            <mc cn="C_Zip_Postal" />
            <mc cn="ContactID" />
          </mcs>
        </rds>
      </rdss>
      <validationExtracts />
      <ces />
      <extractQueries>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_DownloadedLeads" queryAlias="Q_Timestamp_DownloadedLeads" sw="Workspace" schemaName="Timestamp_DownloadedLeads" at="False" ucm="True">
          <schemas />
          <specs />
          <cms>
            <cm qcn="ELQ_Contact_ContactID" itcn="ELQ_Contact_ContactID" />
            <cm qcn="Time_OfCompletion_DownloadedLeads" itcn="Time_OfCompletion_DownloadedLeads" />
            <cm qcn="Days_SinceLastScoreAtTimeOfDownload" itcn="Days_SinceLastScoreAtTimeOfDownload" />
          </cms>
        </extractQuery>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_PreScoringIncr" queryAlias="Q_Timestamp_PreScoringIncr" sw="Workspace" schemaName="Timestamp_PushToScoring" at="False" ucm="True">
          <schemas />
          <specs />
          <cms>
            <cm qcn="ELQ_Contact_ContactID" itcn="ELQ_Contact_ContactID" />
            <cm qcn="Time_OfSubmission_PushToScoring" itcn="Time_OfSubmission_PushToScoring" />
          </cms>
        </extractQuery>
      </extractQueries>
      <extractQuerySequences />
      <leafExtracts />
      <launchExtracts />
      <jobs />
      <pdmatches />
      <leadscroings />
      <lssbardins />
      <lssbardouts />
      <lds />
      <ecs />
      <gCs />
    </group>'''
      lgm.setLoadGroup(step2xml)

      # POC ELQ 4: Create New LG: LoadCRMData_2Days
      lgm.createLoadGroup('LoadCRMData_2Days', 'Provisioning', 'LoadCRMData_2Days', True, False)
      step5xml = ''
      step5xml = '''
      <group name="LoadCRMData_2Days" alias="LoadCRMData_2Days" w="Workspace" type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000" launchExpiredDays="7" createdBy="YTian@Lattice-Engines.com" path="Provisioning" autoGenerated="False" validationValidMinutes="120" autoClearOnFailure="False" mergeRulesSaved="True" ng="False">
      <schemas />
      <visiDBConfigurationWithMacros />
      <targetQueries />
      <targetQuerySequences />
      <rdss>
        <rds n="SFDC_User" w="Workspace" sn="SFDC_User" cn="SFDC_DataProvider" u="False" ss="" tn="User" nmo="1" f="@datediff(now, day(2)) AND @recordcount(1000000)" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="1" emd="False" eo_sftp="1" />
        <rds n="SFDC_Contact" w="Workspace" sn="SFDC_Contact" cn="SFDC_DataProvider" u="False" ss="" tn="Contact" nmo="1" f="@datediff(now, day(2))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="1" emd="False" eo_sftp="1">
          <mcs>
            <mc cn="Id" />
          </mcs>
        </rds>
        <rds n="SFDC_Lead" w="Workspace" sn="SFDC_Lead" cn="SFDC_DataProvider" u="False" ss="" tn="Lead" nmo="1" f="@datediff(now, day(2))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="1" emd="False" eo_sftp="1" />
        <rds n="SFDC_Opportunity" w="Workspace" sn="SFDC_Opportunity" cn="SFDC_DataProvider" u="False" ss="" tn="Opportunity" nmo="1" f="@datediff(now, day(2))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="1" emd="False" eo_sftp="1" />
        <rds n="SFDC_OpportunityContactRole" w="Workspace" sn="SFDC_OpportunityContactRole" cn="SFDC_DataProvider" u="False" ss="" tn="OpportunityContactRole" nmo="1" f="@datediff(now, day(2))" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="1" emd="False" eo_sftp="1" />
      </rdss>
      <validationExtracts />
      <ces />
      <extractQueries>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_DownloadedSFDC_Leads" queryAlias="Q_Timestamp_DownloadedSFDC_Leads" sw="Workspace" schemaName="Timestamp_DownloadedSFDC_Leads" at="False" ucm="True">
          <schemas />
          <specs />
          <cms>
            <cm qcn="SFDC_Lead_ID" itcn="SFDC_Lead_ID" />
            <cm qcn="Time_OfComepletion_DownloadedSFDC_Leads" itcn="Time_OfComepletion_DownloadedSFDC_Leads" />
          </cms>
        </extractQuery>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_DownloadedSFDC_Contacts" queryAlias="Q_Timestamp_DownloadedSFDC_Contacts" sw="Workspace" schemaName="Timestamp_DownloadedSFDC_Contacts" at="False" ucm="True">
          <schemas />
          <specs />
          <cms>
            <cm qcn="SFDC_Contact_ID" itcn="SFDC_Contact_ID" />
            <cm qcn="Time_OfComepletion_DownloadedSFDC_Contacts" itcn="Time_OfComepletion_DownloadedSFDC_Contacts" />
          </cms>
        </extractQuery>
      </extractQueries>
      <extractQuerySequences />
      <leafExtracts />
      <launchExtracts />
      <jobs />
      <pdmatches />
      <leadscroings />
      <lssbardins />
      <lssbardouts />
      <lds />
      <ecs />
      <gCs />
    </group>'''
      lgm.setLoadGroup(step5xml)

      # POC ELQ 4: Create New LG: LoadMAPData_2Days
      lgm.createLoadGroup('LoadMAPData_2Days', 'Provisioning', 'LoadMAPData_2Days', True, False)
      step6xml = ''
      step6xml = '''
      <group name="LoadMAPData_2Days" alias="LoadMAPData_2Days" w="Workspace" type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000" launchExpiredDays="7" createdBy="YTian@Lattice-Engines.com" path="Provisioning" autoGenerated="False" validationValidMinutes="120" autoClearOnFailure="False" mergeRulesSaved="True" ng="False">
      <schemas />
      <visiDBConfigurationWithMacros />
      <targetQueries />
      <targetQuerySequences />
      <rdss>
        <rds n="ELQ_Contact" w="Workspace" sn="ELQ_Contact" cn="Eloqua_DataProvider" u="False" ss="" tn="Contact" nmo="1" f="@datediff(now, day(2)) AND @recordcount(1000000)" ad="True" em="False" td="False" ic="" dd="" l="1000" tw="True" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="True" eo_sftp="1">
          <mcs>
            <mc cn="C_Address1" />
            <mc cn="C_Annual_Revenue1" />
            <mc cn="C_BusPhone" />
            <mc cn="C_City" />
            <mc cn="C_Company" />
            <mc cn="C_Company_Size1" />
            <mc cn="C_Country" />
            <mc cn="C_DateCreated" />
            <mc cn="C_DateModified" />
            <mc cn="C_EmailAddress" />
            <mc cn="C_FirstName" />
            <mc cn="C_Industry1" />
            <mc cn="C_Job_Role1" />
            <mc cn="C_LastName" />
            <mc cn="C_Lead_Source___Most_Recent1" />
            <mc cn="C_Lead_Source___Original1" />
            <mc cn="C_Product_Solution_of_Interest1" />
            <mc cn="C_SFDC_EmailOptOut1" />
            <mc cn="C_SFDCLeadID" />
            <mc cn="C_State_Prov" />
            <mc cn="C_Title" />
            <mc cn="C_Zip_Postal" />
            <mc cn="ContactID" />
          </mcs>
        </rds>
      </rdss>
      <validationExtracts />
      <ces />
      <extractQueries>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_DownloadedLeads" queryAlias="Q_Timestamp_DownloadedLeads" sw="Workspace" schemaName="Timestamp_DownloadedLeads" at="False" ucm="True">
          <schemas />
          <specs />
          <cms>
            <cm qcn="ELQ_Contact_ContactID" itcn="ELQ_Contact_ContactID" />
            <cm qcn="Time_OfCompletion_DownloadedLeads" itcn="Time_OfCompletion_DownloadedLeads" />
            <cm qcn="Days_SinceLastScoreAtTimeOfDownload" itcn="Days_SinceLastScoreAtTimeOfDownload" />
          </cms>
        </extractQuery>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_PreScoringIncr" queryAlias="Q_Timestamp_PreScoringIncr" sw="Workspace" schemaName="Timestamp_PushToScoring" at="False" ucm="True">
          <schemas />
          <specs />
          <cms>
            <cm qcn="ELQ_Contact_ContactID" itcn="ELQ_Contact_ContactID" />
            <cm qcn="Time_OfSubmission_PushToScoring" itcn="Time_OfSubmission_PushToScoring" />
          </cms>
        </extractQuery>
      </extractQueries>
      <extractQuerySequences />
      <leafExtracts />
      <launchExtracts />
      <jobs />
      <pdmatches />
      <leadscroings />
      <lssbardins />
      <lssbardouts />
      <lds />
      <ecs />
      <gCs />
    </group>'''
      lgm.setLoadGroup(step6xml)

      # Create POC Nested LGs as Servies
      lgm.createLoadGroup('Download_BasicModelingSet', 'Services', 'Download_BasicModelingSet', True, False)
      POC_ELQ1 = etree.fromstring(lgm.getLoadGroup('Download_BasicModelingSet').encode('ascii', 'xmlcharrefreplace'))
      POC_ELQ1.set('ng', 'True')
      lgm.setLoadGroup(etree.tostring(POC_ELQ1))
      ngsxml_POC_ELQ1 = '<ngs><ng n="LoadCRMDataForModeling"/><ng n="LoadMAPDataForModeling"/><ng n="PropDataMatch"/></ngs>'
      lgm.setLoadGroupFunctionality('Download_BasicModelingSet', ngsxml_POC_ELQ1)

      lgm.createLoadGroup('Initialize', 'Services', 'Initialize', True, False)
      POC_ELQ2 = etree.fromstring(lgm.getLoadGroup('Initialize').encode('ascii', 'xmlcharrefreplace'))
      POC_ELQ2.set('ng', 'True')
      lgm.setLoadGroup(etree.tostring(POC_ELQ2))
      ngsxml_POC_ELQ2 = '<ngs><ng n="ImportMetaData"/><ng n="ImportCfgTables"/><ng n="LoadCRMData_2Days"/><ng n="LoadMAPData_2Days"/><ng n="PropDataMatch"/><ng n="CreateEventTableQueries"/></ngs>'
      lgm.setLoadGroupFunctionality('Initialize', ngsxml_POC_ELQ2)

      lgm.createLoadGroup('Model', 'Services', 'Model', True, False)
      POC_ELQ3 = etree.fromstring(lgm.getLoadGroup('Model').encode('ascii', 'xmlcharrefreplace'))
      POC_ELQ3.set('ng', 'True')
      lgm.setLoadGroup(etree.tostring(POC_ELQ3))
      ngsxml_POC_ELQ3 = '<ngs><ng n="CreateAnalyticPlay"/></ngs>'
      lgm.setLoadGroupFunctionality('Model', ngsxml_POC_ELQ3)

    else:
      # POC SFDC 1: Change filter for LoadCRMDataForModeling
      lgm.createLoadGroup('LoadCRMDataForModeling', 'ModelBuild\Standard', 'LoadCRMDataForModeling', True, False)
      step2xml = ''
      step1xml = '''
    <group name="LoadCRMDataForModeling" alias="LoadCRMDataForModeling" w="Workspace" type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000" launchExpiredDays="7" createdBy="tiyu@lattice-engines.com" path="ModelBuild\Standard" autoGenerated="False" validationValidMinutes="120" autoClearOnFailure="False" mergeRulesSaved="True" ng="False">
      <schemas />
      <visiDBConfigurationWithMacros />
      <targetQueries />
      <targetQuerySequences />
      <rdss>
        <rds n="SFDC_Contact" w="Workspace" sn="SFDC_Contact" cn="SFDC_DataProvider" u="False" ss="" tn="Contact" nmo="1" f="@datediff(now, month(12)) " ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="True" eo_sftp="2">
          <mcs>
            <mc cn="Id" />
            <mc cn="LastModifiedDate" />
          </mcs>
        </rds>
        <rds n="SFDC_Lead" w="Workspace" sn="SFDC_Lead" cn="SFDC_DataProvider" u="False" ss="" tn="Lead" nmo="1" f="@datediff(now, month(12)) " ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="False" eo_sftp="2">
          <mcs>
            <mc cn="Id" />
            <mc cn="LastModifiedDate" />
          </mcs>
        </rds>
        <rds n="SFDC_Account" w="Workspace" sn="SFDC_Account" cn="SFDC_DataProvider" u="False" ss="" tn="Account" nmo="1" f="@datediff(now, month(12)) " ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="True" eo_sftp="2">
          <mcs>
            <mc cn="Id" />
          </mcs>
        </rds>
        <rds n="SFDC_Opportunity" w="Workspace" sn="SFDC_Opportunity" cn="SFDC_DataProvider" u="False" ss="" tn="Opportunity" nmo="1" f="@datediff(now, month(12)) " ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="True" eo_sftp="2">
          <mcs>
            <mc cn="Id" />
            <mc cn="LastModifiedDate" />
          </mcs>
        </rds>
        <rds n="SFDC_User" w="Workspace" sn="SFDC_User" cn="SFDC_DataProvider" u="False" ss="" tn="User" nmo="1" f="@datediff(now, month(12)) " ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="False" eo_sftp="2">
          <mcs>
            <mc cn="Id" />
            <mc cn="LastModifiedDate" />
          </mcs>
        </rds>
        <rds n="SFDC_OpportunityContactRole" w="Workspace" sn="SFDC_OpportunityContactRole" cn="SFDC_DataProvider" u="False" ss="" tn="OpportunityContactRole" nmo="1" f="@datediff(now, month(12)) " ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="True" eo_sftp="2">
          <mcs>
            <mc cn="Id" />
            <mc cn="LastModifiedDate" />
          </mcs>
        </rds>
      </rdss>
      <validationExtracts />
      <ces />
      <extractQueries>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_Downloaded_Lead_Contact" queryAlias="Q_Timestamp_Downloaded_Lead_Contact" sw="Workspace" schemaName="Timestamp_Downloaded_Lead_Contact" at="False" ucm="True">
          <schemas />
          <specs />
          <cms>
            <cm qcn="SFDC_Lead_Contact_ID" itcn="SFDC_Lead_Contact_ID" />
            <cm qcn="Time_OfCompletion_DownloadedLeads" itcn="Time_OfCompletion_DownloadedLeads" />
            <cm qcn="Days_SinceLastScoreAtTimeOfDownload" itcn="Days_SinceLastScoreAtTimeOfDownload" />
            <cm qcn="ContactID" itcn="ContactID" />
          </cms>
        </extractQuery>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_DownloadedOtherTables" queryAlias="Q_Timestamp_DownloadedOtherTables" sw="Workspace" schemaName="Timestamp_DownloadedOtherTables" at="False" ucm="True">
          <schemas />
          <specs />
          <cms>
            <cm qcn="Time_OfCompletion_DownladedOtherTables" itcn="Time_OfCompletion_DownladedOtherTables" />
          </cms>
        </extractQuery>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_PreScoringIncr" queryAlias="Q_Timestamp_PreScoringIncr" sw="Workspace" schemaName="Timestamp_PushToScoring" at="False" ucm="True">
          <schemas />
          <specs />
          <cms>
            <cm qcn="SFDC_Lead_Contact_ID" itcn="SFDC_Lead_Contact_ID" />
            <cm qcn="Time_OfSubmission_PushToScoring" itcn="Time_OfSubmission_PushToScoring" />
            <cm qcn="ContactID" itcn="ContactID" />
          </cms>
        </extractQuery>
      </extractQueries>
      <extractQuerySequences />
      <leafExtracts />
      <launchExtracts />
      <jobs />
      <pdmatches />
      <leadscroings />
      <lssbardins />
      <lssbardouts />
      <lds />
      <ecs />
      <gCs />
    </group>'''
      lgm.setLoadGroup(step1xml)

      # POC SFDC 2: Create New LG: LoadCRMData_2Days
      lgm.createLoadGroup('LoadCRMData_2Days', 'Provisioning', 'LoadCRMData_2Days', True, False)
      step2xml = ''
      step2xml = '''
      <group name="LoadCRMData_2Days" alias="LoadCRMData_2Days" w="Workspace" type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000" launchExpiredDays="7" createdBy="YTian@Lattice-Engines.com" path="Provisioning" autoGenerated="False" validationValidMinutes="120" autoClearOnFailure="False" mergeRulesSaved="True" ng="False">
      <schemas />
      <visiDBConfigurationWithMacros />
      <targetQueries />
      <targetQuerySequences />
      <rdss>
        <rds n="SFDC_Contact" w="Workspace" sn="SFDC_Contact" cn="SFDC_DataProvider" u="False" ss="" tn="Contact" nmo="1" f="@datediff(now, day(2)) " ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="True" eo_sftp="2">
          <mcs>
            <mc cn="AccountId" />
            <mc cn="CreatedDate" />
            <mc cn="Email" />
            <mc cn="FirstName" />
            <mc cn="Id" />
            <mc cn="LastModifiedDate" />
            <mc cn="LastName" />
            <mc cn="LeadSource" />
            <mc cn="MailingCity" />
            <mc cn="MailingCountry" />
            <mc cn="MailingState" />
            <mc cn="Phone" />
            <mc cn="Title" />
          </mcs>
        </rds>
        <rds n="SFDC_Lead" w="Workspace" sn="SFDC_Lead" cn="SFDC_DataProvider" u="False" ss="" tn="Lead" nmo="1" f="@datediff(now, day(2)) " ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="False" eo_sftp="2">
          <mcs>
            <mc cn="AnnualRevenue" />
            <mc cn="City" />
            <mc cn="Company" />
            <mc cn="ConvertedOpportunityId" />
            <mc cn="Country" />
            <mc cn="CreatedDate" />
            <mc cn="Email" />
            <mc cn="FirstName" />
            <mc cn="Id" />
            <mc cn="Industry" />
            <mc cn="LastModifiedDate" />
            <mc cn="LastName" />
            <mc cn="LeadSource" />
            <mc cn="NumberOfEmployees" />
            <mc cn="OwnerId" />
            <mc cn="Phone" />
            <mc cn="State" />
            <mc cn="Title" />
          </mcs>
        </rds>
        <rds n="SFDC_Account" w="Workspace" sn="SFDC_Account" cn="SFDC_DataProvider" u="False" ss="" tn="Account" nmo="1" f="@datediff(now, day(2)) " ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="True" eo_sftp="2">
          <mcs>
            <mc cn="AnnualRevenue" />
            <mc cn="BillingCity" />
            <mc cn="BillingCountry" />
            <mc cn="BillingState" />
            <mc cn="Id" />
            <mc cn="Industry" />
            <mc cn="Name" />
            <mc cn="NumberOfEmployees" />
          </mcs>
        </rds>
        <rds n="SFDC_Opportunity" w="Workspace" sn="SFDC_Opportunity" cn="SFDC_DataProvider" u="False" ss="" tn="Opportunity" nmo="1" f="@datediff(now, day(2)) " ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="True" eo_sftp="2">
          <mcs>
            <mc cn="AccountId" />
            <mc cn="Amount" />
            <mc cn="CampaignId" />
            <mc cn="CloseDate" />
            <mc cn="CreatedDate" />
            <mc cn="ExpectedRevenue" />
            <mc cn="ForecastCategory" />
            <mc cn="Id" />
            <mc cn="IsClosed" />
            <mc cn="IsDeleted" />
            <mc cn="IsWon" />
            <mc cn="LastActivityDate" />
            <mc cn="LastModifiedDate" />
            <mc cn="LeadSource" />
            <mc cn="Name" />
            <mc cn="OwnerId" />
            <mc cn="Probability" />
            <mc cn="StageName" />
            <mc cn="Type" />
          </mcs>
        </rds>
        <rds n="SFDC_User" w="Workspace" sn="SFDC_User" cn="SFDC_DataProvider" u="False" ss="" tn="User" nmo="1" f="@datediff(now, day(2)) " ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="False" eo_sftp="2">
          <mcs>
            <mc cn="Department" />
            <mc cn="Id" />
            <mc cn="LastModifiedDate" />
            <mc cn="Name" />
            <mc cn="Title" />
          </mcs>
        </rds>
        <rds n="SFDC_OpportunityContactRole" w="Workspace" sn="SFDC_OpportunityContactRole" cn="SFDC_DataProvider" u="False" ss="" tn="OpportunityContactRole" nmo="1" f="@datediff(now, day(2)) " ad="True" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="True" mgf="True" eo="2" emd="True" eo_sftp="2">
          <mcs>
            <mc cn="ContactId" />
            <mc cn="CreatedById" />
            <mc cn="CreatedDate" />
            <mc cn="Id" />
            <mc cn="IsDeleted" />
            <mc cn="IsPrimary" />
            <mc cn="LastModifiedById" />
            <mc cn="LastModifiedDate" />
            <mc cn="OpportunityId" />
            <mc cn="Role" />
            <mc cn="SystemModstamp" />
          </mcs>
        </rds>
      </rdss>
      <validationExtracts />
      <ces />
      <extractQueries>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_Downloaded_Lead_Contact" queryAlias="Q_Timestamp_Downloaded_Lead_Contact" sw="Workspace" schemaName="Timestamp_Downloaded_Lead_Contact" at="False" ucm="True">
          <schemas />
          <specs />
          <cms>
            <cm qcn="SFDC_Lead_Contact_ID" itcn="SFDC_Lead_Contact_ID" />
            <cm qcn="Time_OfCompletion_DownloadedLeads" itcn="Time_OfCompletion_DownloadedLeads" />
            <cm qcn="Days_SinceLastScoreAtTimeOfDownload" itcn="Days_SinceLastScoreAtTimeOfDownload" />
            <cm qcn="ContactID" itcn="ContactID" />
          </cms>
        </extractQuery>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_DownloadedOtherTables" queryAlias="Q_Timestamp_DownloadedOtherTables" sw="Workspace" schemaName="Timestamp_DownloadedOtherTables" at="False" ucm="True">
          <schemas />
          <specs />
          <cms>
            <cm qcn="Time_OfCompletion_DownladedOtherTables" itcn="Time_OfCompletion_DownladedOtherTables" />
          </cms>
        </extractQuery>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_PreScoringIncr" queryAlias="Q_Timestamp_PreScoringIncr" sw="Workspace" schemaName="Timestamp_PushToScoring" at="False" ucm="True">
          <schemas />
          <specs />
          <cms>
            <cm qcn="SFDC_Lead_Contact_ID" itcn="SFDC_Lead_Contact_ID" />
            <cm qcn="Time_OfSubmission_PushToScoring" itcn="Time_OfSubmission_PushToScoring" />
            <cm qcn="ContactID" itcn="ContactID" />
          </cms>
        </extractQuery>
      </extractQueries>
      <extractQuerySequences />
      <leafExtracts />
      <launchExtracts />
      <jobs />
      <pdmatches />
      <leadscroings />
      <lssbardins />
      <lssbardouts />
      <lds />
      <ecs />
      <gCs />
    </group>'''
      lgm.setLoadGroup(step2xml)

      # Create POC Nested LGs as Servies
      lgm.createLoadGroup('Download_BasicModelingSet', 'Services', 'Download_BasicModelingSet', True, False)
      POC_SFDC1 = etree.fromstring(lgm.getLoadGroup('Download_BasicModelingSet').encode('ascii', 'xmlcharrefreplace'))
      POC_SFDC1.set('ng', 'True')
      lgm.setLoadGroup(etree.tostring(POC_SFDC1))
      ngsxml_POC_SFDC1 = '<ngs><ng n="LoadCRMDataForModeling"/><ng n="PropDataMatch"/></ngs>'
      lgm.setLoadGroupFunctionality('Download_BasicModelingSet', ngsxml_POC_SFDC1)

      lgm.createLoadGroup('Initialize', 'Services', 'Initialize', True, False)
      POC_SFDC2 = etree.fromstring(lgm.getLoadGroup('Initialize').encode('ascii', 'xmlcharrefreplace'))
      POC_SFDC2.set('ng', 'True')
      lgm.setLoadGroup(etree.tostring(POC_SFDC2))
      ngsxml_POC_SFDC2 = '<ngs><ng n="ImportMetaData"/><ng n="ImportCfgTables"/><ng n="LoadCRMData_2Days"/><ng n="PropDataMatch"/><ng n="CreateEventTableQueries"/></ngs>'
      lgm.setLoadGroupFunctionality('Initialize', ngsxml_POC_SFDC2)

      lgm.createLoadGroup('Model', 'Services', 'Model', True, False)
      POC_SFDC3 = etree.fromstring(lgm.getLoadGroup('Model').encode('ascii', 'xmlcharrefreplace'))
      POC_SFDC3.set('ng', 'True')
      lgm.setLoadGroup(etree.tostring(POC_SFDC3))
      ngsxml_POC_SFDC3 = '<ngs><ng n="CreateAnalyticPlay"/></ngs>'
      lgm.setLoadGroupFunctionality('Model', ngsxml_POC_SFDC3)

    # Create POC LG for All MKTO, ELQ and SFDC
    POC_Score = lgm.getLoadGroup('BulkScoring_PushToScoringDB')
    step1 = etree.fromstring(POC_Score.encode('ascii', 'xmlcharrefreplace'))
    step1.set('name', 'Score_ConfiguredDateRange')
    step1.set('alias', 'Score_ConfiguredDateRange')
    step1.set('path', 'Services')
    lgm.setLoadGroup(etree.tostring(step1))

    POC_Score = lgm.getLoadGroup('PushToLeadDestination')
    step2 = etree.fromstring(POC_Score.encode('ascii', 'xmlcharrefreplace'))
    step2.set('name', 'Upload_LatestScoredLeadsToCustomer')
    step2.set('alias', 'Upload_LatestScoredLeadsToCustomer')
    step2.set('path', 'Services')
    lgm.setLoadGroup(etree.tostring(step2))

    success = True

    return success
