#
# $LastChangedBy: mwilson $
# $LastChangedDate: 2015-11-13 14:56:48 +0800 (Fri, 13 Nov 2015) $
# $Rev: 70934 $
#

from lxml import etree
from appsequence import Applicability, StepBase


class LP_020200_DL_PushToLeadDestination(StepBase):
  name = 'LP_020200_DL_PushToLeadDestination'
  description = 'Add PushLeadsLastScoredToDestination,PushToLeadDestination_TimeStamp,PushToLeadDestination_Validation, delete PushLeadsInDanteToDestination'
  version = '$Rev: 70934 $'

  def __init__(self, forceApply=False):
    super(LP_020200_DL_PushToLeadDestination, self).__init__(forceApply)

  def getApplicability(self, appseq):

    lgm = appseq.getLoadGroupMgr()
    if lgm.hasLoadGroup('PushToLeadDestination_Validation') and lgm.hasLoadGroup('PushToLeadDestination_TimeStamp'):
      return Applicability.alreadyAppliedPass
    return Applicability.canApply

  def apply(self, appseq):

    success = False

    lgm = appseq.getLoadGroupMgr()
    type = appseq.getText('template_type')

    lgm.createLoadGroup('PushToLeadDestination_Validation', 'OperationalProcess\Standard',
                        'PushToLeadDestination_Validation', True, False)
    step1xml = ''
    if type == 'MKTO':
      step1xml = '''
    <group name="PushToLeadDestination_Validation" alias="PushToLeadDestination_Validation" w="Workspace" type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000" launchExpiredDays="7" createdBy="VZhao@Lattice-Engines.com" path="OperationalProcess\Standard" autoGenerated="False" validationValidMinutes="120" autoClearOnFailure="False" mergeRulesSaved="True" ng="False">
      <schemas />
      <visiDBConfigurationWithMacros />
      <targetQueries>
        <targetQuery w="Workspace" t="2" name="Q_Summary_Lead_Status" alias="Q_Summary_Lead_Status" isc="False" threshold="10000" fsTableName="Summary_Lead_Status" sourceType="1" jobType="20" ignoreOptionsValue="0" exportToDestDirectly="True" exportRule="4" fileExt="bcp" rowTerminator="\\0\\r" columnTerminator="\\0" edts="False" destType="SQL" destDataProvider="SQL_LeadValidation_DataProvider" cto="0">
          <schemas />
          <specs />
          <fsColumnMappings>
            <fsColumnMapping queryColumnName="Const_TenantName" fsColumnName="TenantName" formatter="" type="0" ignoreType="0" ignoreOptions="0" formatColumnName="False" charsToFormat="" />
            <fsColumnMapping queryColumnName="Lead_Status" fsColumnName="Lead_Status" formatter="" type="0" ignoreType="0" ignoreOptions="0" formatColumnName="False" charsToFormat="" />
            <fsColumnMapping queryColumnName="Time_OfSubmission_PushToScoring" fsColumnName="Time_OfSubmission_PushToScoring" formatter="" type="0" ignoreType="0" ignoreOptions="0" formatColumnName="False" charsToFormat="" />
            <fsColumnMapping queryColumnName="Time_OfCompletion_LoadScoredLeads" fsColumnName="Time_OfCompletion_LoadScoredLeads" formatter="" type="0" ignoreType="0" ignoreOptions="0" formatColumnName="False" charsToFormat="" />
            <fsColumnMapping queryColumnName="Time_OfCompletion_PushToDestination" fsColumnName="Time_OfCompletion_PushToDestination" formatter="" type="0" ignoreType="0" ignoreOptions="0" formatColumnName="False" charsToFormat="" />
            <fsColumnMapping queryColumnName="MKTO_LeadRecord_ID" fsColumnName="LeadID" formatter="" type="0" ignoreType="0" ignoreOptions="0" formatColumnName="False" charsToFormat="" />
          </fsColumnMappings>
          <excludeColumns />
          <validationQueries>
            <validationQuery name="Q_Validation_Lead_Status" alias="Q_Validation_Lead_Status" type="2">
              <schemas />
              <specs />
            </validationQuery>
          </validationQueries>
          <constantRows />
          <kcs>
            <kc n="LeadID" />
          </kcs>
          <fut dn="" d="" n="" iet="False" iets="False" t="1" />
        </targetQuery>
      </targetQueries>
      <targetQuerySequences>
        <sequence w="Workspace" queryName="Q_Summary_Lead_Status" sequence="1" />
      </targetQuerySequences>
      <rdss />
      <validationExtracts />
      <ces />
      <extractQueries />
      <extractQuerySequences />
      <leafExtracts />
      <launchExtracts />
      <jobs />
      <pdmatches />
      <leadscroings />
      <lssbardins />
      <lssbardouts />
      <lds />
      <ecs />
      <gCs />
    </group>'''

    elif type == 'ELQ':
      step1xml = '''
    <group name="PushToLeadDestination_Validation" alias="PushToLeadDestination_Validation" w="Workspace" type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000" launchExpiredDays="7" createdBy="VZhao@Lattice-Engines.com" path="OperationalProcess\Standard" autoGenerated="False" validationValidMinutes="120" autoClearOnFailure="False" mergeRulesSaved="True" ng="False">
      <schemas />
      <visiDBConfigurationWithMacros />
      <targetQueries>
        <targetQuery w="Workspace" t="2" name="Q_Summary_Lead_Status" alias="Q_Summary_Lead_Status" isc="False" threshold="10000" fsTableName="Summary_Lead_Status" sourceType="1" jobType="20" ignoreOptionsValue="0" exportToDestDirectly="True" exportRule="4" fileExt="bcp" rowTerminator="\\0\\r" columnTerminator="\\0" edts="False" destType="SQL" destDataProvider="SQL_LeadValidation_DataProvider" cto="1">
          <schemas />
          <specs />
          <fsColumnMappings>
            <fsColumnMapping queryColumnName="Const_TenantName" fsColumnName="TenantName" formatter="" type="0" ignoreType="0" ignoreOptions="0" formatColumnName="False" charsToFormat="" />
            <fsColumnMapping queryColumnName="Lead_Status" fsColumnName="Lead_Status" formatter="" type="0" ignoreType="0" ignoreOptions="0" formatColumnName="False" charsToFormat="" />
            <fsColumnMapping queryColumnName="Time_OfSubmission_PushToScoring" fsColumnName="Time_OfSubmission_PushToScoring" formatter="" type="0" ignoreType="0" ignoreOptions="0" formatColumnName="False" charsToFormat="" />
            <fsColumnMapping queryColumnName="Time_OfCompletion_LoadScoredLeads" fsColumnName="Time_OfCompletion_LoadScoredLeads" formatter="" type="0" ignoreType="0" ignoreOptions="0" formatColumnName="False" charsToFormat="" />
            <fsColumnMapping queryColumnName="Time_OfCompletion_PushToDestination" fsColumnName="Time_OfCompletion_PushToDestination" formatter="" type="0" ignoreType="0" ignoreOptions="0" formatColumnName="False" charsToFormat="" />
            <fsColumnMapping queryColumnName="ELQ_Contact_ContactID" fsColumnName="LeadID" formatter="" type="0" ignoreType="0" ignoreOptions="0" formatColumnName="False" charsToFormat="" />
          </fsColumnMappings>
          <excludeColumns />
          <validationQueries>
            <validationQuery name="Q_Validation_Lead_Status" alias="Q_Validation_Lead_Status" type="2">
              <schemas />
              <specs />
            </validationQuery>
          </validationQueries>
          <constantRows />
          <kcs>
            <kc n="LeadID" />
          </kcs>
          <fut dn="" d="" n="" iet="False" iets="False" t="1" />
        </targetQuery>
      </targetQueries>
      <targetQuerySequences>
        <sequence w="Workspace" queryName="Q_Summary_Lead_Status" sequence="1" />
      </targetQuerySequences>
      <rdss />
      <validationExtracts />
      <ces />
      <extractQueries />
      <extractQuerySequences />
      <leafExtracts />
      <launchExtracts />
      <jobs />
      <pdmatches />
      <leadscroings />
      <lssbardins />
      <lssbardouts />
      <lds />
      <ecs />
      <gCs />
    </group>'''

    else:
      step1xml = '''
    <group name="PushToLeadDestination_Validation" alias="PushToLeadDestination_Validation" w="Workspace" type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000" launchExpiredDays="7" createdBy="VZhao@Lattice-Engines.com" path="OperationalProcess\Standard" autoGenerated="False" validationValidMinutes="120" autoClearOnFailure="False" mergeRulesSaved="True" ng="False">
      <schemas />
      <visiDBConfigurationWithMacros />
      <targetQueries>
        <targetQuery w="Workspace" t="2" name="Q_Summary_Lead_Status" alias="Q_Summary_Lead_Status" isc="False" threshold="10000" fsTableName="Summary_Lead_Status" sourceType="1" jobType="20" ignoreOptionsValue="0" exportToDestDirectly="True" exportRule="4" fileExt="bcp" rowTerminator="\\0\\r" columnTerminator="\\0" edts="False" destType="SQL" destDataProvider="SQL_LeadValidation_DataProvider" cto="0">
          <schemas />
          <specs />
          <fsColumnMappings>
            <fsColumnMapping queryColumnName="Const_TenantName" fsColumnName="TenantName" formatter="" type="0" ignoreType="0" ignoreOptions="0" formatColumnName="False" charsToFormat="" />
            <fsColumnMapping queryColumnName="Lead_Status" fsColumnName="Lead_Status" formatter="" type="0" ignoreType="0" ignoreOptions="0" formatColumnName="False" charsToFormat="" />
            <fsColumnMapping queryColumnName="Time_OfSubmission_PushToScoring" fsColumnName="Time_OfSubmission_PushToScoring" formatter="" type="0" ignoreType="0" ignoreOptions="0" formatColumnName="False" charsToFormat="" />
            <fsColumnMapping queryColumnName="Time_OfCompletion_LoadScoredLeads" fsColumnName="Time_OfCompletion_LoadScoredLeads" formatter="" type="0" ignoreType="0" ignoreOptions="0" formatColumnName="False" charsToFormat="" />
            <fsColumnMapping queryColumnName="Time_OfCompletion_PushToDestination" fsColumnName="Time_OfCompletion_PushToDestination" formatter="" type="0" ignoreType="0" ignoreOptions="0" formatColumnName="False" charsToFormat="" />
            <fsColumnMapping queryColumnName="SFDC_Lead_Contact_ID" fsColumnName="LeadID" formatter="" type="0" ignoreType="0" ignoreOptions="0" formatColumnName="False" charsToFormat="" />
          </fsColumnMappings>
          <excludeColumns />
          <validationQueries>
            <validationQuery name="Q_Validation_Lead_Status" alias="Q_Validation_Lead_Status" type="2">
              <schemas />
              <specs />
            </validationQuery>
          </validationQueries>
          <constantRows />
          <kcs>
            <kc n="LeadID" />
          </kcs>
          <fut dn="" d="" n="" iet="False" iets="False" t="1" />
        </targetQuery>
      </targetQueries>
      <targetQuerySequences>
        <sequence w="Workspace" queryName="Q_Summary_Lead_Status" sequence="1" />
      </targetQuerySequences>
      <rdss />
      <validationExtracts />
      <ces />
      <extractQueries />
      <extractQuerySequences />
      <leafExtracts />
      <launchExtracts />
      <jobs />
      <pdmatches />
      <leadscroings />
      <lssbardins />
      <lssbardouts />
      <lds />
      <ecs />
      <gCs />
    </group>'''

    lgm.setLoadGroup(step1xml)

    lgm.createLoadGroup('PushToLeadDestination_TimeStamp', 'OperationalProcess\Standard',
                        'PushToLeadDestination_TimeStamp', True, False)

    step2xml = ''
    if type == 'MKTO':
      step2xml = '''<extractQueries>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_PushToDestination_LastScored" queryAlias="Q_Timestamp_PushToDestination_LastScored" sw="Workspace" schemaName="Timestamp_PushToDestination" at="False" ucm="True">
          <schemas />
          <specs />
          <cms>
            <cm qcn="MKTO_LeadRecord_ID" itcn="MKTO_LeadRecord_ID" />
            <cm qcn="Time_OfCompletion_PushToDestination" itcn="Time_OfCompletion_PushToDestination" />
          </cms>
        </extractQuery>
      </extractQueries>'''

    elif type == 'ELQ':
      step2xml = '''<extractQueries>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_PushToDestination_LastScored" queryAlias="Q_Timestamp_PushToDestination_LastScored" sw="Workspace" schemaName="Timestamp_PushToDestination" at="False" ucm="True">
          <schemas />
          <specs />
          <cms>
            <cm qcn="ELQ_Contact_ContactID" itcn="ELQ_Contact_ContactID" />
            <cm qcn="Time_OfCompletion_PushToDestination" itcn="Time_OfCompletion_PushToDestination" />
          </cms>
        </extractQuery>
      </extractQueries>'''

    else:
      step2xml = '''<extractQueries>
        <extractQuery qw="Workspace" queryName="Q_Timestamp_PushToDestination_LastScored" queryAlias="Q_Timestamp_PushToDestination_LastScored" sw="Workspace" schemaName="Timestamp_PushToDestination" at="False" ucm="True">
          <schemas />
          <specs />
          <cms>
            <cm qcn="SFDC_Lead_Contact_ID" itcn="SFDC_Lead_Contact_ID" />
            <cm qcn="Time_OfCompletion_PushToDestination" itcn="Time_OfCompletion_PushToDestination" />
          </cms>
        </extractQuery>
      </extractQueries>'''

    lgm.setLoadGroupFunctionality('PushToLeadDestination_TimeStamp', step2xml)

    psdb_ngs_xml = lgm.getLoadGroupFunctionality('PushLeadsLastScoredToDestination','extractQueries')
    psdb_ngs = etree.fromstring( psdb_ngs_xml )
    for eq in psdb_ngs:
      if eq.get('queryAlias') == 'Q_Timestamp_PushToDestination_LastScored':
        psdb_ngs.remove( eq )

    lgm.setLoadGroupFunctionality( 'PushLeadsLastScoredToDestination', etree.tostring(psdb_ngs) )

    ptld = etree.fromstring(lgm.getLoadGroup('PushToLeadDestination').encode('ascii', 'xmlcharrefreplace'))

    ptld.set('ng', 'True')
    lgm.setLoadGroup(etree.tostring(ptld))
    ngsxml = '<ngs><ng n="LoadScoredLeads_Step1"/><ng n="LoadScoredLeads_Step2"/><ng n="PushDataToDante_Hourly"/><ng n="InsightsAllSteps"/><ng n="PushLeadsLastScoredToDestination"/><ng n="PushToLeadDestination_TimeStamp"/><ng n="PushToLeadDestination_Validation"/></ngs>'
    lgm.setLoadGroupFunctionality('PushToLeadDestination', ngsxml)

    success = True

    return success
