package com.latticeengines.domain.exposed.datacloud.match.dnbbulkrequest;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.10.04 at 12:20:30 AM CST
//


import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.lattice.domain.datacloud.transformation.dnbbulkrequest package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.lattice.domain.datacloud.transformation.dnbbulkrequest
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BatProcessBatchRequest }
     *
     */
    public BatProcessBatchRequest createBatProcessBatchRequest() {
        return new BatProcessBatchRequest();
    }

    /**
     * Create an instance of {@link BatProcessBatchRequest.InputDetail }
     *
     */
    public BatProcessBatchRequest.InputDetail createBatProcessBatchRequestInputDetail() {
        return new BatProcessBatchRequest.InputDetail();
    }

    /**
     * Create an instance of {@link BatProcessBatchRequest.BatchSpecification }
     *
     */
    public BatProcessBatchRequest.BatchSpecification createBatProcessBatchRequestBatchSpecification() {
        return new BatProcessBatchRequest.BatchSpecification();
    }

    /**
     * Create an instance of {@link BatProcessBatchRequest.BatchDetail }
     *
     */
    public BatProcessBatchRequest.BatchDetail createBatProcessBatchRequestBatchDetail() {
        return new BatProcessBatchRequest.BatchDetail();
    }

    /**
     * Create an instance of {@link BatProcessBatchRequest.OutputSpecification }
     *
     */
    public BatProcessBatchRequest.OutputSpecification createBatProcessBatchRequestOutputSpecification() {
        return new BatProcessBatchRequest.OutputSpecification();
    }

    /**
     * Create an instance of {@link BatProcessBatchRequest.InputDetail.InputObjectDetail }
     *
     */
    public BatProcessBatchRequest.InputDetail.InputObjectDetail createBatProcessBatchRequestInputDetailInputObjectDetail() {
        return new BatProcessBatchRequest.InputDetail.InputObjectDetail();
    }

    /**
     * Create an instance of {@link BatProcessBatchRequest.BatchSpecification.BatchSpecificationObject }
     *
     */
    public BatProcessBatchRequest.BatchSpecification.BatchSpecificationObject createBatProcessBatchRequestBatchSpecificationBatchSpecificationObject() {
        return new BatProcessBatchRequest.BatchSpecification.BatchSpecificationObject();
    }

}

