//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.01 at 01:01:17 PM PDT 
//


package com.latticeengines.dataplatform.fairscheduler.generator;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}queue" maxOccurs="unbounded"/>
 *         &lt;element ref="{}defaultMinSharePreemptionTimeout"/>
 *         &lt;element ref="{}fairSharePreemptionTimeout"/>
 *         &lt;element ref="{}user"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "queue",
    "defaultMinSharePreemptionTimeout",
    "fairSharePreemptionTimeout",
    "user"
})
@XmlRootElement(name = "allocations")
public class Allocations {

    @XmlElement(required = true)
    protected List<Queue> queue;
    @XmlElement(required = true)
    protected BigInteger defaultMinSharePreemptionTimeout;
    @XmlElement(required = true)
    protected BigInteger fairSharePreemptionTimeout;
    @XmlElement(required = true)
    protected User user;

    /**
     * Gets the value of the queue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the queue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQueue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Queue }
     * 
     * 
     */
    public List<Queue> getQueue() {
        if (queue == null) {
            queue = new ArrayList<Queue>();
        }
        return this.queue;
    }

    /**
     * Gets the value of the defaultMinSharePreemptionTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDefaultMinSharePreemptionTimeout() {
        return defaultMinSharePreemptionTimeout;
    }

    /**
     * Sets the value of the defaultMinSharePreemptionTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDefaultMinSharePreemptionTimeout(BigInteger value) {
        this.defaultMinSharePreemptionTimeout = value;
    }

    /**
     * Gets the value of the fairSharePreemptionTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFairSharePreemptionTimeout() {
        return fairSharePreemptionTimeout;
    }

    /**
     * Sets the value of the fairSharePreemptionTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFairSharePreemptionTimeout(BigInteger value) {
        this.fairSharePreemptionTimeout = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setUser(User value) {
        this.user = value;
    }

}
