#!/bin/bash
source /etc/profile
rm -rf $CATALINA_HOME/webapps/saml/*.war
rm -rf /usr/share/tomcat/work/SamlEngine

id -u tomcat &>/dev/null || useradd tomcat
getent group tomcat || groupadd tomcat
mkdir -p /var/log/saml
mkdir -p /var/cache/saml
chown -R tomcat:tomcat /var/log/saml
chown -R tomcat:tomcat /var/cache/saml
chmod -R 755 /var/cache/saml
chmod -R 777 /var/log/saml
