
#
# $LastChangedBy$
# $LastChangedDate$
# $Rev$
#

from liaison import *
from appsequence import Applicability, AppSequence, StepBase

class LP_020002_ImportCfgTables( StepBase ):

    name        = 'LP_020002_ImportCfgTables'
    description = 'Creates a new Load Group: ImportCfgTables'
    version     = '$Rev$'


    def __init__( self, forceApply = False ):
        super( LP_020002_ImportCfgTables, self ).__init__( forceApply )


    def getApplicability( self, appseq ):
        lg_mgr = appseq.getLoadGroupMgr()

        if not lg_mgr.hasLoadGroup( 'ImportCfgTables' ):
            return Applicability.canApply

        return Applicability.alreadyAppliedPass


    def apply( self, appseq ):
        template_type = appseq.getText( 'template_type' )
        lg_mgr = appseq.getLoadGroupMgr()

        importCfgTables_xml = '''
        <group name="ImportCfgTables" alias="ImportCfgTables" w="Workspace" type="1" scheduleType="0" allowUserChangeScheduleType="False" visibleForEndUser="True" threshold="10000" launchExpiredDays="7" createdBy="mwilson@lattice-engines.com" path="Provisioning" autoGenerated="False" validationValidMinutes="120" autoClearOnFailure="False" mergeRulesSaved="True" ng="False">
            <schemas />
            <visiDBConfigurationWithMacros />
            <targetQueries />
            <targetQuerySequences />
            <rdss>
                <rds n="Cfg_PLS_EventTableQueries" w="Workspace" sn="Cfg_PLS_EventTableQueries" cn="SQL_ProvisioningMeta" u="False" ss="" tn="Cfg_PLS_EventTableQueries" nmo="1" ad="False" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="False" mgf="False" eo="1" emd="False" eo_sftp="2" />
                <rds n="Cfg_PLS_Event" w="Workspace" sn="Cfg_PLS_Event" cn="SQL_ProvisioningMeta" u="False" ss="" tn="Cfg_PLS_Event_TEMPLATETYPE" nmo="1" ad="False" em="False" td="False" ic="" dd="" l="1000" tw="False" sr="50000" htw="24" mtw="60" emt="False" acd="False" mgf="False" eo="1" emd="False" eo_sftp="2" />
            </rdss>
            <validationExtracts />
            <ces />
            <extractQueries />
            <extractQuerySequences />
            <leafExtracts />
            <launchExtracts />
            <jobs />
            <pdmatches />
            <leadscroings />
            <lssbardins />
            <lssbardouts />
            <lds />
            <ecs />
            <gCs />
        </group>
        '''

        importCfgTables_xml = importCfgTables_xml.replace( 'TEMPLATETYPE', template_type )

        lg_mgr.setLoadGroup( importCfgTables_xml )

        return True
