#!/bin/bash -x

source /etc/profile

echo CATALINA_HOME=$CATALINA_HOME

mkdir -p $CATALINA_HOME/webapps
rm -rf $CATALINA_HOME/webapps/*.war

cd /tmp/webapps

JARFILE=`ls le-microservice-*.war`
VERSION=`echo $JARFILE | cut -d \- -f 3`
SNAPSHOT=`echo $JARFILE | cut -d \- -f 4`

if test $SNAPSHOT = "SNAPSHOT"
    then
        VERSION=$VERSION-"SNAPSHOT"
fi

for f in $(find . -name "*.war"); do
    fn=`echo $f | cut -d - -f 2`
    if [ $fn = "microservice" ]
    then
        fn=ROOT
    fi
    cp $f $CATALINA_HOME/webapps/$fn\#\#$VERSION.war;
done

ls $CATALINA_HOME/webapps/*.war
