#!/bin/bash

source /etc/profile
echo "getting environment information"
echo "LE_ENVIRONMENT=${LE_ENVIRONMENT}"
echo "WITH_QUARTZ_MICROSERVICE=${WITH_QUARTZ_MICROSERVICE:=false}"

rm -rf /usr/share/tomcat/webapps/ms/*.war
mkdir -p /usr/share/tomcat/webapps/ms
rm -rf /usr/share/tomcat/work/MicrosereviceEngine

echo "repackaging wars"
cd /tmp/le-microservice-tc-rpm/ms

for f in $(find . -name "*.war");
do
    fn=`echo $f | cut -d / -f 2 | cut -d . -f 1`

    if [ "${fn}" = "quartz" -a "${WITH_QUARTZ_MICROSERVICE}" = "false" ]; then
        echo "skipping quartz war"
        continue;
    fi

    echo "repackaging ${fn}.war"
    mkdir $fn

    pushd $fn
    jar xvf ../$fn.war
    popd
    rm -rf $fn.war

    if [ -f "/tmp/le-microservice-tc-rpm/env/${LE_ENVIRONMENT}/${fn}_log4j.properties" ]
    then
        echo "replacing log4j.properties for ${fn}.war"
        cp -f /tmp/le-microservice-tc-rpm/env/${LE_ENVIRONMENT}/${fn}_log4j.properties ${fn}/WEB-INF/classes/log4j.properties
    fi

    jar cvf $fn.war -C $fn/ .
    cp -f $fn.war /usr/share/tomcat/webapps/ms/$fn.war
done

chown -R tomcat:tomcat /usr/share/tomcat/webapps/ms
chmod -R 775 /usr/share/tomcat/webapps/ms

rm -rf /tmp/le-microservice-tc-rpm

echo "finishing"
ll /usr/share/tomcat/webapps/ms/*.war
