package com.latticeengines.perf.job.properties;

public interface CommandLineProperties {

    public static final char LIST_DELIMETER = ';';

    public static final String VALUE_DELIMETER = ",";

    public static final String ALGORITHM_NAME_DT = "dt";

    public static final String ALGORITHM_NAME_LR = "lr";

    public static final String ALGORITHM_NAME_RF = "rf";

    public static final String ALGORITHM_PROP_DEF = "Algorithm Properties(Algorithm Name, virtual cores, memory, priority)";

    public static final String ALGORITHM_PROP_OPT = "alg";

    public static final String ALGORITHM_PROP_LONGOPT = "algorithmproperties";

    public static final String ALGORITHM_RF_PROP = "criterion=gini n_estimators=100 n_jobs=4 min_samples_split=25 "
            + "min_samples_leaf=10 bootstrap=True";

    public static final String APPLICATIONID_DEF = "ApplicationId generated by yarn";

    public static final String APPLICATIONID_OPT = "appId";

    public static final String APPLICATIONID_LONGOPT = "applicationId";

    public static final String CUSTOMER_DEF = "Number OF Customers sending requests";

    public static final String CUSTOMER_OPT = "c";

    public static final String CUSTOMER_LONGOPT = "customer";

    public static final String DATABASE_DEF = "Datasource Database Name";

    public static final String DATABASE_OPT = "db";

    public static final String DATABASE_LONGOPT = "database";

    public static final String DATABASE_TYPE_DEF = "Datasource type";

    public static final String DATABASE_TYPE_OPT = "dbtp";

    public static final String DATABASE_TYPE_LONGOPT = "databasetype";

    public static final String DATA_FORMAT = "avro";

    public static final String HOST_DEF = "Datasource Host Address";

    public static final String HOST_OPT = "H";

    public static final String HOST_LONGOPT = "host";

    public static final String KEYCOLUMN_DEF = "Key Column Name";

    public static final String KEYCOLUMN_OPT = "kc";

    public static final String KEYCOLUMN_LONGOPT = "keycolumn";

    public static final String METADATA_TABLE_DEF = "Metadata Table Name";

    public static final String METADATA_TABLE_OPT = "mt";

    public static final String METADATA_TABLE_LONGOPT = "metadatatable";

    public static final String NUMOFSAMPLES_DEF = "Number of Samples to create";

    public static final String NUMOFSAMPLES_OPT = "N";

    public static final String NUMOFSAMPLES_LONGOPT = "numberofsamples";

    public static final String OPERATION_CREATE_SAMPLES = "createsamples";

    public static final String OPERATION_LOAD = "load";

    public static final String OPERATION_PROFILE = "profile";

    public static final String OPERATION_SUBMIT_MODEL = "submitmodel";

    public static final String PORT_DEF = "Datasource port";

    public static final String PORT_OPT = "P";

    public static final String PORT_LONGOPT = "port";

    public static final String PASSWORD_DEF = "Datasource password";

    public static final String PASSWORD_OPT = "ps";

    public static final String PASSWORD_LONGOPT = "password";

    public static final String TABLE_DEF = "Table Name";

    public static final String TABLE_OPT = "t";

    public static final String TABLE_LONGOPT = "table";

    public static final String TARGET_DEF = "Target Column Name";

    public static final String TARGET_OPT = "T";

    public static final String TARGET_LONGOPT = "target";

    public static final String TRAINING_PERCENTAGE_DEF = "Training Percentage";

    public static final String TRAINING_PERCENTAGE_OPT = "tp";

    public static final String TRAINING_PERCENTAGE_LONGOPT = "trainingpercentage";

    public static final String USER_DEF = "Datasource User Name";

    public static final String USER_OPT = "u";

    public static final String USER_LONGOPT = "user";

}
