
CREATE TABLE RealtimeMarketo(
	[RealtimeMarketoID] INT IDENTITY(1,1) NOT NULL,
	[ID] INT NOT NULL,
	[AnnualRevenue] FLOAT NULL,
	[AnonymousIP] NVARCHAR(255) NULL,
	[Company] NVARCHAR(255) NULL,
	[Email] NVARCHAR(80) NULL,
	[Country] NVARCHAR(255) NULL,
	[Department] NVARCHAR(255) NULL,
	[DoNotCall] BIT NULL,
	[DoNotCallReason] NVARCHAR(2000) NULL,
	[Industry] NVARCHAR(255) NULL,
	[InferredCompany] NVARCHAR(255) NULL,
	[InferredCountry] NVARCHAR(255) NULL,
	[LeadRole] NVARCHAR(50) NULL,
	[LeadScore] INT NULL,
	[LeadSource] NVARCHAR(255) NULL,
	[LeadStatus] NVARCHAR(255) NULL,
	[MarketoJigsawCompanyStatus] NVARCHAR(50) NULL,
	[MarketoJigsawContactStatus] NVARCHAR(50) NULL,
	[MarketoSocialFacebookReach] INT NULL,
	[MarketoSocialFacebookReferredEnrollments] INT NULL,
	[MarketoSocialFacebookReferredVisits] INT NULL,
	[MarketoSocialLinkedInReach] INT NULL,
	[MarketoSocialLinkedInReferredEnrollments] INT NULL,
	[MarketoSocialLinkedInReferredVisits] INT NULL,
	[MarketoSocialTotalReferredEnrollments] INT NULL,
	[MarketoSocialTotalReferredVisits] INT NULL,
	[MarketoSocialTwitterReach] INT NULL,
	[MarketoSocialTwitterReferredEnrollments] INT NULL,
	[MarketoSocialTwitterReferredVisits] INT NULL,
	[MarketoSocialYahooReach] INT NULL,
	[MarketoSocialYahooReferredEnrollments] INT NULL,
	[MarketoSocialYahooReferredVisits] INT NULL,
	[NumberOfEmployees] INT NULL,
	[SAP_CRM_Person_Type] NVARCHAR(50) NULL,
	[SAP_CRM_Qualification] NVARCHAR(2000) NULL,
	[SicCode] NVARCHAR(40) NULL,
	[Title] NVARCHAR(255) NULL,
	[Unsubscribed] BIT NULL,
	[UnsubscribedReason] NVARCHAR(2000) NULL,
	[Website] NVARCHAR(255) NULL,
	CONSTRAINT PK_RealtimeMarketo PRIMARY KEY CLUSTERED ([RealtimeMarketoID])
)