package com.latticeengines.dataplatform.controller;

import javax.inject.Inject;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.latticeengines.dataplatform.entitymanager.ModelDownloadFlagEntityMgr;
import com.latticeengines.dataplatform.exposed.service.ModelingService;
import com.latticeengines.domain.exposed.SimpleBooleanResponse;
import com.latticeengines.domain.exposed.api.AppSubmission;
import com.latticeengines.domain.exposed.api.StringList;
import com.latticeengines.domain.exposed.camille.CustomerSpace;
import com.latticeengines.domain.exposed.dataplatform.JobStatus;
import com.latticeengines.domain.exposed.modeling.DataProfileConfiguration;
import com.latticeengines.domain.exposed.modeling.EventCounterConfiguration;
import com.latticeengines.domain.exposed.modeling.Model;
import com.latticeengines.domain.exposed.modeling.ModelReviewConfiguration;
import com.latticeengines.domain.exposed.modeling.SamplingConfiguration;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;

@Api(value = "REST resource for machine learning models")
@RestController
public class ModelResource {

    @Inject
    private ModelingService modelingService;

    @Inject
    private ModelDownloadFlagEntityMgr modelDownloadFlagEntityMgr;

    @PostMapping("/models")
    @ResponseBody
    @ApiOperation(value = "Submit models")
    public AppSubmission submit(@RequestBody Model model) {
        return new AppSubmission(modelingService.submitModel(model));
    }

   @PostMapping("/samples")
    @ResponseBody
    @ApiOperation(value = "Create named samples to be used by profiling or modeling")
    public AppSubmission createSamples(@RequestBody SamplingConfiguration config) {
       return new AppSubmission(modelingService.createSamples(config));
    }

    @PostMapping("/eventcounter")
    @ResponseBody
    @ApiOperation(value = "Create named event counter to be used by profiling or modeling")
    public AppSubmission createEventCounter(@RequestBody EventCounterConfiguration config) {
        return new AppSubmission(modelingService.createEventCounter(config));
    }

    @GetMapping("/modelingjobs/{applicationId}")
    @ResponseBody
    @ApiOperation(value = "Get status about a submitted job")
    public JobStatus getJobStatus(@PathVariable String applicationId) {
        return modelingService.getJobStatus(applicationId);
    }

    @PostMapping("/profiles")
    @ResponseBody
    @ApiOperation(value = "Profile data")
    public AppSubmission profile(@RequestBody DataProfileConfiguration config) {
        return new AppSubmission(modelingService.profileData(config));
    }

    @PostMapping("/reviews")
    @ResponseBody
    @ApiOperation(value = "Review data")
    public AppSubmission review(@RequestBody ModelReviewConfiguration config) {
        return new AppSubmission(modelingService.reviewData(config));
    }

    @PostMapping("/features")
    @ResponseBody
    @ApiOperation(value = "Get list of features generated by the data profile")
    public StringList getFeatures(@RequestBody Model model) {
        return new StringList(modelingService.getFeatures(model, false));
    }

    @GetMapping("/model/{modelId}")
    @ResponseBody
    @ApiOperation(value = "Get model by modelId")
    public Model getModel(@PathVariable String modelId) {
        return modelingService.getModel(modelId);
    }

    @PostMapping("/downloadflags/{tenantId}")
    @ResponseBody
    @ApiOperation(value = "Flag a tenant has models to download")
    public SimpleBooleanResponse flagToDownload(@PathVariable String tenantId) {
        String fullTenantId = CustomerSpace.parse(tenantId).toString();
        modelDownloadFlagEntityMgr.addDownloadFlag(fullTenantId);
        return SimpleBooleanResponse.successResponse();
    }

}
